-- =====================================================================
-- PRODUCT MASTER - ADD TRUCK_ID SUPPORT
-- Run ALTER TABLE first (already applied on the DB):
--
--   ALTER TABLE VMASTER.TBL_PRODUCT_MASTER
--     ADD TRUCK_ID INT CONSTRAINT FK_TRUCK_ID_PROD_MAS
--       FOREIGN KEY REFERENCES VMASTER.TBL_TRUCK_MASTER_HDR(TRUCK_ID); -- BY DEFAULT NULL
--
-- Then run the ALTER PROCEDURE scripts below.
-- TRUCK_ID is optional - pass NULL when no truck is assigned.
-- =====================================================================

USE [TBGS]
GO

/****** Object:  StoredProcedure [VMASTER].[SAVE_PRODUCT_MASTER]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [VMASTER].[SAVE_PRODUCT_MASTER]
(
    @PRODUCT_ID INT,
    @PRODUCT_NAME VARCHAR(1500),
    @TBS_PRODUCT_NAME VARCHAR(MAX),
    @MAIN_CATEGORY_ID INT,
    @SUB_CATEGORY_ID INT,
    @UOM_ID INT,
    @NO_OF_PCS_PER_PACKING DECIMAL(15,2),
    @ALTERNATE_UOM_ID INT,
    @COST_CENTRE_ID INT,
    @COMPANY_ID INT,
    @PRODUCTION_COST DECIMAL(15,2),
    @VAT_PERCENTAGE DECIMAL(15,2),
    @REMARKS VARCHAR(2000),
    @STATUS_MASTER VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50),
    @TRUCK_ID INT = NULL
)
AS
BEGIN
    SET NOCOUNT ON

    IF EXISTS   (
        SELECT 'CHECK EXISTS' FROM [VMaster].[TBL_PRODUCT_MASTER]
        WHERE UPPER(PRODUCT_NAME)=UPPER(@PRODUCT_NAME)  AND COMPANY_ID=@COMPANY_ID
    )
    BEGIN
        SELECT 'error','Product Name Already Exists',''
    END
	ELSE BEGIN

    INSERT INTO [VMaster].[TBL_PRODUCT_MASTER]
    (
        PRODUCT_NAME,
        TBS_PRODUCT_NAME,
        MAIN_CATEGORY_ID,
        SUB_CATEGORY_ID,
        UOM_ID,
        NO_OF_PCS_PER_PACKING,
        ALTERNATE_UOM_ID,
        COST_CENTRE_ID,
        COMPANY_ID,
        TRUCK_ID,
        PRODUCTION_COST,
        VAT_PERCENTAGE,
        REMARKS,
        STATUS_MASTER,
        CREATED_BY,
        CREATED_DATE,
        CREATED_MAC_ADDRESS,
        MODIFIED_BY,
        MODIFIED_DATE,
        MODIFIED_MAC_ADDRESS
    )
    VALUES
    (
        @PRODUCT_NAME,
        @TBS_PRODUCT_NAME,
        @MAIN_CATEGORY_ID,
        @SUB_CATEGORY_ID,
        @UOM_ID,
        @NO_OF_PCS_PER_PACKING,
        @ALTERNATE_UOM_ID,
        @COST_CENTRE_ID,
        @COMPANY_ID,
        @TRUCK_ID,
        @PRODUCTION_COST,
        @VAT_PERCENTAGE,
        @REMARKS,
        @STATUS_MASTER,
        @USER,
        GETDATE(),
        @MAC_ADDRESS,
        @USER,
        GETDATE(),
        @MAC_ADDRESS
    )

    SELECT '', 'Data Saved Successfully', SCOPE_IDENTITY()
END
 END
GO

/****** Object:  StoredProcedure [VMASTER].[UPDATE_PRODUCT_MASTER]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [VMASTER].[UPDATE_PRODUCT_MASTER]
(
    @PRODUCT_ID INT,
    @PRODUCT_NAME VARCHAR(1500),
    @TBS_PRODUCT_NAME VARCHAR(MAX),
    @MAIN_CATEGORY_ID INT,
    @SUB_CATEGORY_ID INT,
    @UOM_ID INT,
    @NO_OF_PCS_PER_PACKING DECIMAL(15,2),
    @ALTERNATE_UOM_ID INT,
    @COST_CENTRE_ID INT,
    @COMPANY_ID INT,
    @PRODUCTION_COST DECIMAL(15,2),
    @VAT_PERCENTAGE DECIMAL(15,2),
    @REMARKS VARCHAR(2000),
    @STATUS_MASTER VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50),
    @TRUCK_ID INT = NULL
)
AS
BEGIN
    SET NOCOUNT ON

    IF EXISTS
    (
        SELECT 'CHECK'
        FROM [VMaster].[TBL_PRODUCT_MASTER]
        WHERE UPPER(PRODUCT_NAME)=UPPER(@PRODUCT_NAME)
        AND COMPANY_ID=@COMPANY_ID
        AND PRODUCT_ID<>@PRODUCT_ID
    )
    BEGIN
        SELECT 'error','Product Name Already Exists',''
    END

	ELSE BEGIN
    UPDATE [VMaster].[TBL_PRODUCT_MASTER]
    SET
        PRODUCT_NAME=@PRODUCT_NAME,
        TBS_PRODUCT_NAME=@TBS_PRODUCT_NAME,
        MAIN_CATEGORY_ID=@MAIN_CATEGORY_ID,
        SUB_CATEGORY_ID=@SUB_CATEGORY_ID,
        UOM_ID=@UOM_ID,
        NO_OF_PCS_PER_PACKING=@NO_OF_PCS_PER_PACKING,
        ALTERNATE_UOM_ID=@ALTERNATE_UOM_ID,
        COST_CENTRE_ID=@COST_CENTRE_ID,
        COMPANY_ID=@COMPANY_ID,
        TRUCK_ID=@TRUCK_ID,
        PRODUCTION_COST=@PRODUCTION_COST,
        VAT_PERCENTAGE=@VAT_PERCENTAGE,
        REMARKS=@REMARKS,
        STATUS_MASTER=@STATUS_MASTER,
        MODIFIED_BY=@USER,
        MODIFIED_DATE=GETDATE(),
        MODIFIED_MAC_ADDRESS=@MAC_ADDRESS
    WHERE PRODUCT_ID=@PRODUCT_ID;

    SELECT '', 'Record Updated Successfully', @PRODUCT_ID
END
END
GO

/****** Object:  StoredProcedure [VMASTER].[SHOW_PRODUCT_MASTER]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [VMASTER].[SHOW_PRODUCT_MASTER]
AS
BEGIN
    SET NOCOUNT ON

    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        MAIN_CATEGORY_ID,
        SUB_CATEGORY_ID,
        UOM_ID,
        NO_OF_PCS_PER_PACKING,
        ALTERNATE_UOM_ID,
        COST_CENTRE_ID,
        COMPANY_ID,
        TRUCK_ID,
        PRODUCTION_COST,
        VAT_PERCENTAGE,
        REMARKS,
        STATUS_MASTER
    FROM [VMaster].[TBL_PRODUCT_MASTER]
    ORDER BY PRODUCT_NAME;
END
GO

/****** Object:  StoredProcedure [VMASTER].[GET_PRODUCT_MASTER]    ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
ALTER PROCEDURE [VMASTER].[GET_PRODUCT_MASTER]
(
    @PRODUCT_ID INT
)
AS
BEGIN
    SET NOCOUNT ON

    SELECT
        PRODUCT_ID,
        PRODUCT_NAME,
        TBS_PRODUCT_NAME,
        MAIN_CATEGORY_ID,
        SUB_CATEGORY_ID,
        UOM_ID,
        NO_OF_PCS_PER_PACKING,
        ALTERNATE_UOM_ID,
        COST_CENTRE_ID,
        COMPANY_ID,
        TRUCK_ID,
        PRODUCTION_COST,
        VAT_PERCENTAGE,
        RESPONSE_1_emp_id,
        RESPONSE_1_DATE,
        RESPONSE_1_STATUS,
        RESPONSE_1_REMARKS,
        RESPONSE_2_emp_id,
        RESPONSE_2_DATE,
        RESPONSE_2_STATUS,
        RESPONSE_2_REMARKS,
        FINAL_RESPONSE_PERSON,
        FINAL_RESPONSE_DATE,
        FINAL_RESPONSE_STATUS,
        FINAL_RESPONSE_REMARKS,
        REMARKS,
        STATUS_MASTER,
        CREATED_BY
    FROM [VMaster].[TBL_PRODUCT_MASTER]
    WHERE PRODUCT_ID=@PRODUCT_ID
END
GO
