-- =====================================================================
-- Attendance Type Master
-- Table + CRUD Stored Procedures (mirrors TBL_PAYMENT_TERM_MASTER pattern)
-- =====================================================================

IF OBJECT_ID('VMaster.TBL_ATTENDANCE_TYPE_MASTER', 'U') IS NULL
BEGIN
    CREATE TABLE VMaster.TBL_ATTENDANCE_TYPE_MASTER
    (
        ATTENDANCE_TYPE_ID   INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ATTENDANCE_TYPE_NAME VARCHAR(150) NOT NULL,
        ELIGIBLE_DAYS        INT NULL,
        REMARKS              VARCHAR(500) NULL,
        STATUS_MASTER        VARCHAR(20) NOT NULL DEFAULT 'AC',
        CREATED_BY           VARCHAR(50) NULL,
        CREATED_DATE         DATETIME NULL,
        CREATED_MAC_ADDRESS  VARCHAR(50) NULL,
        MODIFIED_BY          VARCHAR(50) NULL,
        MODIFIED_DATE        DATETIME NULL,
        MODIFIED_MAC_ADDRESS VARCHAR(50) NULL
    );
END
GO

-- ===================== SAVE =====================
IF OBJECT_ID('VMaster.SAVE_ATTENDANCE_TYPE_MASTER', 'P') IS NOT NULL DROP PROCEDURE VMaster.SAVE_ATTENDANCE_TYPE_MASTER;
GO
CREATE PROCEDURE VMaster.SAVE_ATTENDANCE_TYPE_MASTER
(
    @ATTENDANCE_TYPE_ID INT OUTPUT,
    @ATTENDANCE_TYPE_NAME VARCHAR(150),
    @ELIGIBLE_DAYS INT,
    @REMARKS VARCHAR(500),
    @STATUS_MASTER VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    IF EXISTS
    (
        SELECT 'CHECK'
        FROM VMaster.TBL_ATTENDANCE_TYPE_MASTER
        WHERE ATTENDANCE_TYPE_NAME = @ATTENDANCE_TYPE_NAME
    )
    BEGIN
        SELECT 'ERROR','ATTENDANCE TYPE ALREADY EXISTS','0'
    END
    ELSE
    BEGIN
        INSERT INTO VMaster.TBL_ATTENDANCE_TYPE_MASTER
        (
            ATTENDANCE_TYPE_NAME,
            ELIGIBLE_DAYS,
            REMARKS,
            STATUS_MASTER,
            CREATED_BY,
            CREATED_DATE,
            CREATED_MAC_ADDRESS,
            MODIFIED_BY,
            MODIFIED_DATE,
            MODIFIED_MAC_ADDRESS
        )
        VALUES
        (
            @ATTENDANCE_TYPE_NAME,
            @ELIGIBLE_DAYS,
            @REMARKS,
            @STATUS_MASTER,
            @USER,
            GETDATE(),
            @MAC_ADDRESS,
            @USER,
            GETDATE(),
            @MAC_ADDRESS
        )

        SELECT @ATTENDANCE_TYPE_ID = SCOPE_IDENTITY()

        SELECT '', 'DATA SAVED SUCCESSFULLY', @ATTENDANCE_TYPE_ID
    END
END
GO

-- ===================== UPDATE =====================
IF OBJECT_ID('VMaster.UPDATE_ATTENDANCE_TYPE_MASTER', 'P') IS NOT NULL DROP PROCEDURE VMaster.UPDATE_ATTENDANCE_TYPE_MASTER;
GO
CREATE PROCEDURE VMaster.UPDATE_ATTENDANCE_TYPE_MASTER
(
    @ATTENDANCE_TYPE_ID INT,
    @ATTENDANCE_TYPE_NAME VARCHAR(50),
    @ELIGIBLE_DAYS INT,
    @REMARKS VARCHAR(500),
    @STATUS_MASTER VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    IF EXISTS
    (
        SELECT '1'
        FROM VMaster.TBL_ATTENDANCE_TYPE_MASTER
        WHERE ATTENDANCE_TYPE_NAME = @ATTENDANCE_TYPE_NAME
        AND ATTENDANCE_TYPE_ID <> @ATTENDANCE_TYPE_ID
    )
    BEGIN
        SELECT 'ERROR','ATTENDANCE TYPE ALREADY EXISTS','0'
    END
    ELSE
    BEGIN
        UPDATE VMaster.TBL_ATTENDANCE_TYPE_MASTER
        SET
            ATTENDANCE_TYPE_NAME = @ATTENDANCE_TYPE_NAME,
            ELIGIBLE_DAYS = @ELIGIBLE_DAYS,
            REMARKS = @REMARKS,
            STATUS_MASTER = @STATUS_MASTER,
            MODIFIED_BY = @USER,
            MODIFIED_DATE = GETDATE(),
            MODIFIED_MAC_ADDRESS = @MAC_ADDRESS
        WHERE ATTENDANCE_TYPE_ID = @ATTENDANCE_TYPE_ID

        SELECT '', 'RECORD UPDATED SUCCESSFULLY', @ATTENDANCE_TYPE_ID
    END
END
GO

-- ===================== GET =====================
IF OBJECT_ID('VMaster.GET_ATTENDANCE_TYPE_MASTER', 'P') IS NOT NULL DROP PROCEDURE VMaster.GET_ATTENDANCE_TYPE_MASTER;
GO
CREATE PROCEDURE VMaster.GET_ATTENDANCE_TYPE_MASTER
(
    @ATTENDANCE_TYPE_ID INT
)
AS
BEGIN
    SET NOCOUNT ON

    SELECT
        ATTENDANCE_TYPE_ID,
        ATTENDANCE_TYPE_NAME,
        ELIGIBLE_DAYS,
        REMARKS,
        STATUS_MASTER
    FROM VMaster.TBL_ATTENDANCE_TYPE_MASTER
    WHERE ATTENDANCE_TYPE_ID = @ATTENDANCE_TYPE_ID
END
GO

-- ===================== SHOW =====================
IF OBJECT_ID('VMaster.SHOW_ATTENDANCE_TYPE_MASTER', 'P') IS NOT NULL DROP PROCEDURE VMaster.SHOW_ATTENDANCE_TYPE_MASTER;
GO
CREATE PROCEDURE VMaster.SHOW_ATTENDANCE_TYPE_MASTER
(
    @STATUS VARCHAR(20)
)
AS
BEGIN
    SET NOCOUNT ON

    SELECT
        ATTENDANCE_TYPE_ID,
        ATTENDANCE_TYPE_NAME,
        ELIGIBLE_DAYS,
        REMARKS,
        STATUS_MASTER AS STATUS
    FROM VMaster.TBL_ATTENDANCE_TYPE_MASTER
    WHERE STATUS_MASTER = @STATUS
END
GO

-- ===================== DELETE =====================
IF OBJECT_ID('VMaster.DELETE_ATTENDANCE_TYPE_MASTER', 'P') IS NOT NULL DROP PROCEDURE VMaster.DELETE_ATTENDANCE_TYPE_MASTER;
GO
CREATE PROCEDURE VMaster.DELETE_ATTENDANCE_TYPE_MASTER
(
    @ATTENDANCE_TYPE_ID INT,
    @USER VARCHAR(50),
    @ROLE VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    IF @ROLE <> 'Admin'
    BEGIN
        SELECT 'ERROR','NO RIGHTS TO DELETE',''
    END
    ELSE IF NOT EXISTS
    (
        SELECT 'CHECK'
        FROM VMaster.TBL_ATTENDANCE_TYPE_MASTER
        WHERE ATTENDANCE_TYPE_ID = @ATTENDANCE_TYPE_ID
    )
    BEGIN
        SELECT 'ERROR','RECORD DOES NOT EXIST',''
    END
    ELSE
    BEGIN
        DELETE FROM VMaster.TBL_ATTENDANCE_TYPE_MASTER
        WHERE ATTENDANCE_TYPE_ID = @ATTENDANCE_TYPE_ID

        SELECT '', 'RECORD DELETED SUCCESSFULLY', @ATTENDANCE_TYPE_ID
    END
END
GO