-- Cash Advance entry stored procedures (VPayEntries)
-- Fixes the missing comma in SHOW_CASH_ADVANCE which caused [REASON] to be
-- aliased as [REMARKS] and dropped the real REMARKS column.

ALTER PROCEDURE [VPayEntries].[SHOW_CASH_ADVANCE]
(
  @CASH_ADV_REQUEST_REF_NO VARCHAR(20)
)
AS
BEGIN
    SET NOCOUNT ON

    SELECT 
     [CASH_ADV_REQUEST_REF_NO]
      ,[SALARY_DEDUCTION_TYPE]
      ,[ADVANCE_TYPE]
      ,[MONTH_ENTERED]
      ,[YEAR_ENTERED]
      ,[EMP_ID]
      ,[FIRST_NAME]
      ,[MIDDLE_NAME]
      ,[LAST_NAME]
      ,COMPANY_NAME 
      ,DEPARTMENT_NAME 
      ,DESIGNATION_NAME 
      ,DEPARTMENT_GROUP_NAME 
      ,DESIGNATION_GROUP_NAME 
      ,CAMP_NAME 
      ,Store_Name 
      ,EMPLOYMENT_TYPE_NAME 
	  ,CURRENCY_NAME 
      ,[ADVANCE_AMOUNT]
      ,[REASON]
      ,[REMARKS]
    FROM [VPayEntries].[TBL_CASH_ADVANCE] A
	  INNER JOIN VMaster.TBL_DESIGNATION_MASTER D ON D.DESIGNATION_ID =A.DESIGNATION_ID
    INNER JOIN VMaster.TBL_COMPANY_MASTER  C ON C.COMPANY_ID  =A.COMPANY_ID
    INNER JOIN VMaster.TBL_CURRENCY_MASTER   CS ON CS.CURRENCY_ID  =A.CURRENCY_ID
    INNER JOIN VMaster.TBL_DEPARTMENT_MASTER   DP ON DP.DEPARTMENT_ID   =A.DEPARTMENT_ID
  INNER JOIN VMaster.TBL_DEPARTMENT_GROUP_MASTER    DG ON DG.DEPARTMENT_GROUP_ID    =A.DEPARTMENT_GROUP_ID
  INNER JOIN VMaster.TBL_DESIGNATION_GROUP_MASTER     DS ON DS.DESIGNATION_GROUP_ID    =A.DESIGNATION_GROUP_ID
  INNER JOIN VMaster.TBL_CAMP_MASTER      CP ON CP.CAMP_ID     =A.CAMP_ID
 INNER JOIN VMaster.tbl_Store_Master       ST ON ST.Store_Id  =A.Store_Id
 INNER JOIN VMaster.TBL_EMPLOYMENT_TYPE_MASTER        EP ON EP.EMPLOYMENT_TYPE_ID   =A.EMPLOYMENT_TYPE_ID
    WHERE CASH_ADV_REQUEST_REF_NO=@CASH_ADV_REQUEST_REF_NO
END
GO