-- Cash Advance Request stored procedures (VRequest + VMaster SUBMIT)
-- Synced with the deployed procedures. Notable behaviors:
--   * CURRENCY_ID is part of every CRUD procedure.
--   * UPDATE_CASH_ADVANCE_REQUEST blocks editing once STATUS_MASTER = 'CL'
--     (submitted), unless the caller is an Administrator (matches the
--     "Contact To Admin" hint and the SUBMIT procedure's admin bypass).
--   * SAVE_CASH_ADVANCE_REQUEST generates the reference number server-side.
--   * SUBMIT_CASH_ADVANCE_REQUEST (VMaster) marks a request as submitted (CL).

USE [TBGS]
GO

/****** Object: StoredProcedure [VRequest].[GET_CASH_ADVANCE_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.GET_CASH_ADVANCE_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[GET_CASH_ADVANCE_REQUEST];
GO
CREATE PROCEDURE [VRequest].[GET_CASH_ADVANCE_REQUEST]
(
    @CASH_ADV_REQUEST_REF_NO VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    SELECT [SNO]
      ,[CASH_ADV_REQUEST_REF_NO]
      ,[SALARY_DEDUCTION_TYPE]
      ,[ADVANCE_TYPE]
      ,[MONTH_ENTERED]
      ,[YEAR_ENTERED]
      ,[EMP_ID]
      ,[FIRST_NAME]
      ,[MIDDLE_NAME]
      ,[LAST_NAME]
      ,[COMPANY_ID]
      ,[DEPARTMENT_ID]
      ,[DESIGNATION_ID]
      ,[DEPARTMENT_GROUP_ID]
      ,[DESIGNATION_GROUP_ID]
      ,[CAMP_ID]
      ,[STORE_ID]
      ,[EMPLOYMENT_TYPE_ID]
      ,CURRENCY_ID
      ,[GROSS_PAY]
      ,[NET_PAY]
      ,[ELIGIBLE_AMOUNT]
      ,[REQUEST_AMOUNT]
      ,[APPROVED_AMOUNT]
      ,[DEDUCTION_FROM_DATE]
      ,[DEDUCTION_TO_DATE]
      ,[NO_OF_MONTHS]
      ,[MONTHLY_DEDUCTION]
      ,[PAYMENT_MODE_ID]
      ,[BANK_ID]
      ,[ACCOUNT_NO]
      ,[REASON]
      ,[SECTION_HEAD_RESPONSE_PERSON_EMP_ID]
      ,[SECTION_HEAD_RESPONSE_DATE]
      ,[SECTION_HEAD_RESPONSE_STATUS]
      ,[SECTION_HEAD_RESPONSE_REMARKS]
      ,[RESPONSE_1_EMP_ID]
      ,[RESPONSE_1_DATE]
      ,[RESPONSE_1_STATUS]
      ,[RESPONSE_1_REMARKS]
      ,[RESPONSE_2_EMP_ID]
      ,[RESPONSE_2_DATE]
      ,[RESPONSE_2_STATUS]
      ,[RESPONSE_2_REMARKS]
      ,[FINAL_RESPONSE_PERSON]
      ,[FINAL_RESPONSE_DATE]
      ,[FINAL_RESPONSE_STATUS]
      ,[FINAL_RESPONSE_REMARKS]
      ,[REMARKS]
      ,[STATUS_MASTER]
  FROM [VRequest].[TBL_CASH_ADVANCE_REQUEST]
    WHERE CASH_ADV_REQUEST_REF_NO=@CASH_ADV_REQUEST_REF_NO
END
GO

/****** Object: StoredProcedure [VRequest].[SHOW_CASH_ADVANCE_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.SHOW_CASH_ADVANCE_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[SHOW_CASH_ADVANCE_REQUEST];
GO
CREATE PROCEDURE [VRequest].[SHOW_CASH_ADVANCE_REQUEST]
(
    @CASH_ADV_REQUEST_REF_NO VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    SELECT [SNO]
      ,[CASH_ADV_REQUEST_REF_NO]
      ,[SALARY_DEDUCTION_TYPE]
      ,[ADVANCE_TYPE]
      ,[MONTH_ENTERED]
      ,[YEAR_ENTERED]
      ,[EMP_ID]
      ,[FIRST_NAME]
      ,[MIDDLE_NAME]
      ,[LAST_NAME]
      ,COMPANY_NAME
      ,DEPARTMENT_NAME
      ,DESIGNATION_NAME
      ,DEPARTMENT_GROUP_NAME
      ,DESIGNATION_GROUP_NAME
      ,CAMP_NAME
      ,Store_Name
      ,EMPLOYMENT_TYPE_NAME
      ,CURRENCY_NAME
      ,[GROSS_PAY]
      ,[NET_PAY]
      ,[ELIGIBLE_AMOUNT]
      ,[REQUEST_AMOUNT]
      ,[APPROVED_AMOUNT]
      ,[DEDUCTION_FROM_DATE]
      ,[DEDUCTION_TO_DATE]
      ,[NO_OF_MONTHS]
      ,[MONTHLY_DEDUCTION]
      ,[PAYMENT_MODE_ID]
      ,[BANK_ID]
      ,[ACCOUNT_NO]
      ,[REASON]
      ,[SECTION_HEAD_RESPONSE_PERSON_EMP_ID]
      ,[SECTION_HEAD_RESPONSE_DATE]
      ,[SECTION_HEAD_RESPONSE_STATUS]
      ,[SECTION_HEAD_RESPONSE_REMARKS]
      ,[RESPONSE_1_EMP_ID]
      ,[RESPONSE_1_DATE]
      ,[RESPONSE_1_STATUS]
      ,[RESPONSE_1_REMARKS]
      ,[RESPONSE_2_EMP_ID]
      ,[RESPONSE_2_DATE]
      ,[RESPONSE_2_STATUS]
      ,[RESPONSE_2_REMARKS]
      ,[FINAL_RESPONSE_PERSON]
      ,[FINAL_RESPONSE_DATE]
      ,[FINAL_RESPONSE_STATUS]
      ,[FINAL_RESPONSE_REMARKS]
      ,A.[REMARKS]
      ,A.[STATUS_MASTER]
  FROM [VRequest].[TBL_CASH_ADVANCE_REQUEST] A
  INNER JOIN VMaster.TBL_DESIGNATION_MASTER D ON D.DESIGNATION_ID = A.DESIGNATION_ID
  INNER JOIN VMaster.TBL_COMPANY_MASTER C ON C.COMPANY_ID = A.COMPANY_ID
  INNER JOIN VMaster.TBL_CURRENCY_MASTER CS ON CS.CURRENCY_ID = A.CURRENCY_ID
  INNER JOIN VMaster.TBL_DEPARTMENT_MASTER DP ON DP.DEPARTMENT_ID = A.DEPARTMENT_ID
  INNER JOIN VMaster.TBL_DEPARTMENT_GROUP_MASTER DG ON DG.DEPARTMENT_GROUP_ID = A.DEPARTMENT_GROUP_ID
  INNER JOIN VMaster.TBL_DESIGNATION_GROUP_MASTER DS ON DS.DESIGNATION_GROUP_ID = A.DESIGNATION_GROUP_ID
  INNER JOIN VMaster.TBL_CAMP_MASTER CP ON CP.CAMP_ID = A.CAMP_ID
  INNER JOIN VMaster.tbl_Store_Master ST ON ST.Store_Id = A.Store_Id
  INNER JOIN VMaster.TBL_EMPLOYMENT_TYPE_MASTER EP ON EP.EMPLOYMENT_TYPE_ID = A.EMPLOYMENT_TYPE_ID
    WHERE CASH_ADV_REQUEST_REF_NO=@CASH_ADV_REQUEST_REF_NO
END
GO

/****** Object: StoredProcedure [VRequest].[SAVE_CASH_ADVANCE_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.SAVE_CASH_ADVANCE_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[SAVE_CASH_ADVANCE_REQUEST];
GO
CREATE PROCEDURE [VRequest].[SAVE_CASH_ADVANCE_REQUEST]
(
    @CASH_ADV_REQUEST_REF_NO VARCHAR(50),
    @SALARY_DEDUCTION_TYPE VARCHAR(50),
    @ADVANCE_TYPE VARCHAR(50),
    @MONTH_ENTERED VARCHAR(25),
    @YEAR_ENTERED INT,
    @EMP_ID INT,
    @FIRST_NAME VARCHAR(50),
    @MIDDLE_NAME VARCHAR(50),
    @LAST_NAME VARCHAR(50),
    @COMPANY_ID INT,
    @DEPARTMENT_ID INT,
    @DESIGNATION_ID INT,
    @DEPARTMENT_GROUP_ID INT,
    @DESIGNATION_GROUP_ID INT,
    @CAMP_ID INT,
    @STORE_ID INT,
    @EMPLOYMENT_TYPE_ID INT,
    @CURRENCY_ID INT,
    @GROSS_PAY DECIMAL(15,2),
    @NET_PAY DECIMAL(15,2),
    @ELIGIBLE_AMOUNT DECIMAL(15,2),
    @REQUEST_AMOUNT DECIMAL(15,2),
    @APPROVED_AMOUNT DECIMAL(15,2),
    @DEDUCTION_FROM_DATE DATETIME,
    @DEDUCTION_TO_DATE DATETIME,
    @NO_OF_MONTHS INT,
    @MONTHLY_DEDUCTION DECIMAL(15,2),
    @PAYMENT_MODE_ID INT,
    @BANK_ID INT,
    @ACCOUNT_NO VARCHAR(50),
    @REASON VARCHAR(3000),
    @REMARKS VARCHAR(1000),
    @STATUS_MASTER VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    EXEC VRequest.SP_Generate_Screen_Ref_No_With_Output_Parameter 'CASH ADV REQUEST REQUEST', @COMPANY_ID, @CASH_ADV_REQUEST_REF_NO OUT
    IF (@CASH_ADV_REQUEST_REF_NO IS NULL OR @CASH_ADV_REQUEST_REF_NO = '')
    BEGIN
        SELECT 'Error','Can''t Generate Cash Advance Reference Number. Contact Admin',''
    END
    ELSE
    BEGIN
        INSERT INTO [VRequest].[TBL_CASH_ADVANCE_REQUEST]
        (
            CASH_ADV_REQUEST_REF_NO,
            SALARY_DEDUCTION_TYPE,
            ADVANCE_TYPE,
            MONTH_ENTERED,
            YEAR_ENTERED,
            EMP_ID,
            FIRST_NAME,
            MIDDLE_NAME,
            LAST_NAME,
            COMPANY_ID,
            DEPARTMENT_ID,
            DESIGNATION_ID,
            DEPARTMENT_GROUP_ID,
            DESIGNATION_GROUP_ID,
            CAMP_ID,
            STORE_ID,
            EMPLOYMENT_TYPE_ID,
            CURRENCY_ID,
            GROSS_PAY,
            NET_PAY,
            ELIGIBLE_AMOUNT,
            REQUEST_AMOUNT,
            APPROVED_AMOUNT,
            DEDUCTION_FROM_DATE,
            DEDUCTION_TO_DATE,
            NO_OF_MONTHS,
            MONTHLY_DEDUCTION,
            PAYMENT_MODE_ID,
            BANK_ID,
            ACCOUNT_NO,
            REASON,
            REMARKS,
            STATUS_MASTER,
            CREATED_BY,
            CREATED_DATE,
            CREATED_MAC_ADDRESS,
            MODIFIED_BY,
            MODIFIED_DATE,
            MODIFIED_MAC_ADDRESS
        )
        VALUES
        (
            @CASH_ADV_REQUEST_REF_NO,
            @SALARY_DEDUCTION_TYPE,
            @ADVANCE_TYPE,
            @MONTH_ENTERED,
            @YEAR_ENTERED,
            @EMP_ID,
            @FIRST_NAME,
            @MIDDLE_NAME,
            @LAST_NAME,
            @COMPANY_ID,
            @DEPARTMENT_ID,
            @DESIGNATION_ID,
            @DEPARTMENT_GROUP_ID,
            @DESIGNATION_GROUP_ID,
            @CAMP_ID,
            @STORE_ID,
            @EMPLOYMENT_TYPE_ID,
            @CURRENCY_ID,
            @GROSS_PAY,
            @NET_PAY,
            @ELIGIBLE_AMOUNT,
            @REQUEST_AMOUNT,
            @APPROVED_AMOUNT,
            @DEDUCTION_FROM_DATE,
            @DEDUCTION_TO_DATE,
            @NO_OF_MONTHS,
            @MONTHLY_DEDUCTION,
            @PAYMENT_MODE_ID,
            @BANK_ID,
            @ACCOUNT_NO,
            @REASON,
            @REMARKS,
            @STATUS_MASTER,
            @USER,
            GETDATE(),
            @MAC_ADDRESS,
            @USER,
            GETDATE(),
            @MAC_ADDRESS
        );

        DECLARE @LAST_INSERTED_ID INT = SCOPE_IDENTITY();

        SELECT '' AS STATUS, 'Data Saved Successfully' AS MESSAGE, @LAST_INSERTED_ID AS DATA
    END
END
GO

/****** Object: StoredProcedure [VRequest].[UPDATE_CASH_ADVANCE_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.UPDATE_CASH_ADVANCE_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[UPDATE_CASH_ADVANCE_REQUEST];
GO
CREATE PROCEDURE [VRequest].[UPDATE_CASH_ADVANCE_REQUEST]
(
    @SNO INT,
    @CASH_ADV_REQUEST_REF_NO VARCHAR(50),
    @SALARY_DEDUCTION_TYPE VARCHAR(50),
    @ADVANCE_TYPE VARCHAR(50),
    @MONTH_ENTERED VARCHAR(25),
    @YEAR_ENTERED INT,
    @EMP_ID INT,
    @FIRST_NAME VARCHAR(50),
    @MIDDLE_NAME VARCHAR(50),
    @LAST_NAME VARCHAR(50),
    @COMPANY_ID INT,
    @DEPARTMENT_ID INT,
    @DESIGNATION_ID INT,
    @DEPARTMENT_GROUP_ID INT,
    @DESIGNATION_GROUP_ID INT,
    @CAMP_ID INT,
    @STORE_ID INT,
    @EMPLOYMENT_TYPE_ID INT,
    @CURRENCY_ID INT,
    @GROSS_PAY DECIMAL(15,2),
    @NET_PAY DECIMAL(15,2),
    @ELIGIBLE_AMOUNT DECIMAL(15,2),
    @REQUEST_AMOUNT DECIMAL(15,2),
    @APPROVED_AMOUNT DECIMAL(15,2),
    @DEDUCTION_FROM_DATE DATETIME,
    @DEDUCTION_TO_DATE DATETIME,
    @NO_OF_MONTHS INT,
    @MONTHLY_DEDUCTION DECIMAL(15,2),
    @PAYMENT_MODE_ID INT,
    @BANK_ID INT,
    @ACCOUNT_NO VARCHAR(50),
    @REASON VARCHAR(3000),
    @REMARKS VARCHAR(1000),
    @STATUS_MASTER VARCHAR(20),
    @USER VARCHAR(50),
    @ROLE VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    IF EXISTS
    (
        SELECT 'check submitted'
        FROM [VRequest].[TBL_CASH_ADVANCE_REQUEST]
        WHERE CASH_ADV_REQUEST_REF_NO = @CASH_ADV_REQUEST_REF_NO
          AND STATUS_MASTER = 'CL'
          AND @ROLE NOT IN ('Administrator', 'Admin')
    )
    BEGIN
        SELECT 'error','Records Already Submitted You Can''t Change Anything. Contact To Admin',''
    END
    ELSE
    BEGIN
        UPDATE [VRequest].[TBL_CASH_ADVANCE_REQUEST]
        SET
            CASH_ADV_REQUEST_REF_NO = @CASH_ADV_REQUEST_REF_NO,
            SALARY_DEDUCTION_TYPE = @SALARY_DEDUCTION_TYPE,
            ADVANCE_TYPE = @ADVANCE_TYPE,
            MONTH_ENTERED = @MONTH_ENTERED,
            YEAR_ENTERED = @YEAR_ENTERED,
            EMP_ID = @EMP_ID,
            FIRST_NAME = @FIRST_NAME,
            MIDDLE_NAME = @MIDDLE_NAME,
            LAST_NAME = @LAST_NAME,
            COMPANY_ID = @COMPANY_ID,
            DEPARTMENT_ID = @DEPARTMENT_ID,
            DESIGNATION_ID = @DESIGNATION_ID,
            DEPARTMENT_GROUP_ID = @DEPARTMENT_GROUP_ID,
            DESIGNATION_GROUP_ID = @DESIGNATION_GROUP_ID,
            CAMP_ID = @CAMP_ID,
            STORE_ID = @STORE_ID,
            EMPLOYMENT_TYPE_ID = @EMPLOYMENT_TYPE_ID,
            CURRENCY_ID = @CURRENCY_ID,
            GROSS_PAY = @GROSS_PAY,
            NET_PAY = @NET_PAY,
            ELIGIBLE_AMOUNT = @ELIGIBLE_AMOUNT,
            REQUEST_AMOUNT = @REQUEST_AMOUNT,
            APPROVED_AMOUNT = @APPROVED_AMOUNT,
            DEDUCTION_FROM_DATE = @DEDUCTION_FROM_DATE,
            DEDUCTION_TO_DATE = @DEDUCTION_TO_DATE,
            NO_OF_MONTHS = @NO_OF_MONTHS,
            MONTHLY_DEDUCTION = @MONTHLY_DEDUCTION,
            PAYMENT_MODE_ID = @PAYMENT_MODE_ID,
            BANK_ID = @BANK_ID,
            ACCOUNT_NO = @ACCOUNT_NO,
            REASON = @REASON,
            REMARKS = @REMARKS,
            MODIFIED_BY = @USER,
            MODIFIED_DATE = GETDATE(),
            MODIFIED_MAC_ADDRESS = @MAC_ADDRESS
        WHERE CASH_ADV_REQUEST_REF_NO = @CASH_ADV_REQUEST_REF_NO

        SELECT '','Data Updated Successfully',@CASH_ADV_REQUEST_REF_NO
    END
END
GO

/****** Object: StoredProcedure [VRequest].[DELETE_CASH_ADVANCE_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.DELETE_CASH_ADVANCE_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[DELETE_CASH_ADVANCE_REQUEST];
GO
CREATE PROCEDURE [VRequest].[DELETE_CASH_ADVANCE_REQUEST]
(
    @CASH_ADV_REQUEST_REF_NO VARCHAR(50),
    @USER VARCHAR(50),
    @ROLE VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    IF @ROLE <> 'Admin'
    BEGIN
        SELECT 'error','No Rights To Delete','';
    END
    ELSE
    BEGIN
        DELETE
        FROM [VRequest].[TBL_CASH_ADVANCE_REQUEST]
        WHERE CASH_ADV_REQUEST_REF_NO = @CASH_ADV_REQUEST_REF_NO;

        SELECT '','Data Deleted Successfully',@CASH_ADV_REQUEST_REF_NO
    END
END
GO

/****** Object: StoredProcedure [VMaster].[SUBMIT_CASH_ADVANCE_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VMaster.SUBMIT_CASH_ADVANCE_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VMaster].[SUBMIT_CASH_ADVANCE_REQUEST];
GO
CREATE PROCEDURE [VMaster].[SUBMIT_CASH_ADVANCE_REQUEST]
(
    @CASH_ADV_REQUEST_REF_NO VARCHAR(50),
    @ROLE VARCHAR(50) = 'Administrator'
)
AS
BEGIN
    SET NOCOUNT ON
    BEGIN TRY
        BEGIN TRANSACTION
        IF NOT EXISTS (SELECT 'X' FROM VRequest.TBL_CASH_ADVANCE_REQUEST WHERE CASH_ADV_REQUEST_REF_NO = @CASH_ADV_REQUEST_REF_NO)
        BEGIN
            SELECT 'Error','Record not found.. Contact Administrator','0'
        END
        ELSE IF EXISTS (SELECT 'X' FROM VRequest.TBL_CASH_ADVANCE_REQUEST WHERE CASH_ADV_REQUEST_REF_NO = @CASH_ADV_REQUEST_REF_NO AND STATUS_MASTER = 'CL')
            AND @ROLE <> 'Administrator'
        BEGIN
            SELECT 'Error','Already Submitted.. Contact Administrator','0'
        END
        ELSE IF EXISTS (SELECT 'X' FROM VRequest.TBL_CASH_ADVANCE_REQUEST WHERE CASH_ADV_REQUEST_REF_NO = @CASH_ADV_REQUEST_REF_NO AND STATUS_MASTER = 'CA')
        BEGIN
            SELECT 'Error','Already Cancelled.. Contact Administrator','0'
        END
        ELSE
        BEGIN
            UPDATE VRequest.TBL_CASH_ADVANCE_REQUEST
            SET STATUS_MASTER = 'CL'
            WHERE CASH_ADV_REQUEST_REF_NO = @CASH_ADV_REQUEST_REF_NO
            SELECT '','Submitted Successfully','CL'
        END
        COMMIT TRANSACTION
    END TRY
    BEGIN CATCH
        DECLARE @msg VARCHAR(MAX) = ''
        SET @msg = 'ERROR: ' + ERROR_MESSAGE() + ' at '
                    + COALESCE(ERROR_PROCEDURE(), '')
                    + COALESCE(' line:' + CONVERT(VARCHAR(30), ERROR_LINE()), '')
        ROLLBACK TRAN
        RAISERROR (@msg, 16, 1) WITH NOWAIT
    END CATCH
END
GO