ALTER PROCEDURE [VMASTER].[SHOW_ANIMAL_HUNTING_CHARGES_MASTER_HDR]
AS
BEGIN
SET NOCOUNT ON

SELECT
	ANIMAL_HUNT_CHARGE_ID,
	COMPANY_NAME,
	EFFECTIVE_YEAR,
	ISSUING_AUTHORITY,
	APPROVAL_REFERENCE_NO,
	REPLACE(CONVERT(VARCHAR(50),APPROVAL_DATE,106),' ','-') APPROVAL_DATE,
	REPLACE(CONVERT(VARCHAR(50),EFFECTIVE_FROM,106),' ','-') EFFECTIVE_FROM, 
	REPLACE(CONVERT(VARCHAR(50),EFFECTIVE_TO,106),' ','-') EFFECTIVE_TO, 
	CURRENCY_NAME,
	A.REMARKS,
	       Case when A.STATUS_MASTER ='AC' THEN 'ACTIVE' ELSE 'INACTIVE' END [STATUS_MASTER] 
FROM [VMaster].[TBL_ANIMAL_HUNTING_CHARGES_MASTER_HDR] AS A
LEFT JOIN  VMASTER.TBL_CURRENCY_MASTER AS  C ON C.CURRENCY_ID =A.CURRENCY_ID 
LEFT JOIN  VMASTER.TBL_COMPANY_MASTER AS   CA ON CA.COMPANY_ID =A.COMPANY_ID 

END



ALTER PROCEDURE [VMASTER].[SHOW_ANIMAL_HUNTING_CHARGES_MASTER_DTL]
AS
BEGIN
SET NOCOUNT ON

SELECT
	SNO,	 
	ANIMAL_NAME,
    REPLACE(CONVERT(VARCHAR(50),GOVT_RATE,106),' ','-') GOVT_RATE, 
	ACTUAL_AMOUNT,
	A.REMARKS,
	Case when A.STATUS_MASTER ='AC' THEN 'ACTIVE' ELSE 'INACTIVE' END [STATUS_MASTER] 
FROM [VMaster].[TBL_ANIMAL_HUNTING_CHARGES_MASTER_DTL] A
LEFT JOIN  VMaster.TBL_ANIMAL_MASTER AS  N ON  A.ANIMAL_ID =N.ANIMAL_ID 


END



ALTER PROCEDURE [VMASTER].[SHOW_COMPANY_QUOTA_ANIMAL_MAPPING_HDR]
AS
BEGIN
SET NOCOUNT ON

SELECT
	QUOTA_ID,
	COMPANY_NAME,
	CAMP_NAME,
	EFFECTIVE_YEAR,
	NEW_REVISION,
	OLD_QUOTA_ID,
	ISSUING_AUTHORITY,
	APPROVAL_REFERENCE_NO,
	REPLACE(CONVERT(VARCHAR(50),APPROVAL_DATE,106),' ','-') APPROVAL_DATE,
	REPLACE(CONVERT(VARCHAR(50),LAST_AMENDMENT_DATE,106),' ','-') LAST_AMENDMENT_DATE,
	REPLACE(CONVERT(VARCHAR(50),EFFECTIVE_FROM,106),' ','-') EFFECTIVE_FROM,
	REPLACE(CONVERT(VARCHAR(50),EFFECTIVE_TO,106),' ','-') EFFECTIVE_TO,	 
	QUOTA_AMOUNT,
	VAT_AMOUNT,
	FINAL_QUOTA_AMOUNT,
	CURRENCY_NAME,
	a.REMARKS,
	Case when A.STATUS_MASTER ='AC' THEN 'ACTIVE' ELSE 'INACTIVE' END [STATUS_MASTER] 
FROM VMaster.TBL_COMPANY_QUOTA_ANIMAL_MAPPING_HDR a 
left join  vmaster.TBL_COMPANY_MASTER as b on  a.COMPANY_ID =b.COMPANY_ID 
left join  VMaster.TBL_CURRENCY_MASTER as c on  c.CURRENCY_ID =a.CURRENCY_ID
left join  vmaster.TBL_CAMP_MASTER as  ca on ca.CAMP_ID =a.COMPANY_ID


END


ALTER PROCEDURE [VMASTER].[SHOW_COMPANY_QUOTA_ANIMAL_MAPPING_DTL]
AS
BEGIN
SET NOCOUNT ON

SELECT
	SNO,
	QUOTA_ID,
	ANIMAL_NAME,
	OLD_APPROVED_QTY,
	ADD_REMOVE_QTY,
	NEW_APPROVED_QTY,
	a.REMARKS,
	Case when A.STATUS_MASTER ='AC' THEN 'ACTIVE' ELSE 'INACTIVE' END [STATUS_MASTER] 
FROM [VMaster].[TBL_COMPANY_QUOTA_ANIMAL_MAPPING_DTL] as  a
left join  VMaster.TBL_ANIMAL_MASTER as  b on  a.ANIMAL_ID =b.ANIMAL_ID 


END



----show man power approved settings

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [VMaster].[SHOW_MAN_POWER_APPROVED_SETTINGS]
(
    @STATUS VARCHAR(20)
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        A.MAN_POWER_APPROVED_ID,
        A.COMPANY_ID,
        C.COMPANY_NAME,
        A.DEPARTMENT_ID,
        D.DEPARTMENT_NAME,
        A.DESIGNATION_ID,
        DS.DESIGNATION_NAME,
        A.EMPLOYMENT_TYPE_ID,
        EMP.EMPLOYMENT_TYPE_NAME,
        A.NEW_APPROVED_MAN_POWER,
        A.MAN_POWER_REQUEST_ID,
        A.APPROVED_BY,
        A.REMARKS,
        A.STATUS_MASTER,

        A.CREATED_BY,
        A.CREATED_DATE,
        A.MODIFIED_BY,
        A.MODIFIED_DATE

    FROM VMaster.TBL_MAN_POWER_APPROVED_SETTINGS A

    INNER JOIN VMaster.TBL_COMPANY_MASTER C
        ON A.COMPANY_ID = C.COMPANY_ID

    INNER JOIN VMaster.TBL_DEPARTMENT_MASTER D
        ON A.DEPARTMENT_ID = D.DEPARTMENT_ID

    INNER JOIN VMaster.TBL_DESIGNATION_MASTER DS
        ON A.DESIGNATION_ID = DS.DESIGNATION_ID

    INNER JOIN VMaster.TBL_EMPLOYMENT_TYPE_MASTER EMP
        ON A.EMPLOYMENT_TYPE_ID = EMP.EMPLOYMENT_TYPE_ID

    WHERE A.STATUS_MASTER = @STATUS

    ORDER BY
        C.COMPANY_NAME,
        D.DEPARTMENT_NAME,
        DS.DESIGNATION_NAME,
        EMP.EMPLOYMENT_TYPE_NAME;
END
GO

------------------------------------------------------------------------------
----GET_DRIVER_TRUCK_MASTER_MAPPING

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [VMaster].[GET_DRIVER_TRUCK_MASTER_MAPPING]
(
    @SNO INT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        M.SNO,
        M.DRIVER_EMP_ID,
        M.TRUCK_ID,
        T.TRUCK_NO,
        M.EFFECTIVE_FROM,

        M.SECTION_HEAD_RESPONSE_PERSON,
        M.SECTION_HEAD_RESPONSE_DATE,
        M.SECTION_HEAD_RESPONSE_STATUS,
        M.SECTION_HEAD_RESPONSE_REMARKS,

        M.RESPONSE_1_PERSON,
        M.RESPONSE_1_DATE,
        M.RESPONSE_1_STATUS,
        M.RESPONSE_1_REMARKS,

        M.RESPONSE_2_PERSON,
        M.RESPONSE_2_DATE,
        M.RESPONSE_2_STATUS,
        M.RESPONSE_2_REMARKS,

        M.FINAL_RESPONSE_PERSON,
        M.FINAL_RESPONSE_DATE,
        M.FINAL_RESPONSE_STATUS,
        M.FINAL_RESPONSE_REMARKS,

        M.REMARKS,
        M.STATUS_MASTER

    FROM VMaster.TBL_DRIVER_TRUCK_MASTER_MAPPING M

    INNER JOIN VMaster.TBL_DRIVER_MASTER_HDR D
        ON M.DRIVER_EMP_ID = D.DRIVER_EMP_ID

    INNER JOIN VMaster.TBL_TRUCK_MASTER_HDR T
        ON M.TRUCK_ID = T.TRUCK_ID

    WHERE M.SNO = @SNO;
END
GO
-----------------------------------------------------------------------
----SHOW_DRIVER_TRUCK_MASTER_MAPPING

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [VMaster].[SHOW_DRIVER_TRUCK_MASTER_MAPPING]
(
@STATUS varchar(50)
)
AS
BEGIN
    SET NOCOUNT ON

    SELECT
        M.SNO,
        M.DRIVER_EMP_ID,
        D.DRIVER_FULL_NAME,
        M.TRUCK_ID,
        T.TRUCK_NO,
        M.EFFECTIVE_FROM,
        M.SECTION_HEAD_RESPONSE_PERSON,
        M.SECTION_HEAD_RESPONSE_DATE,
        M.SECTION_HEAD_RESPONSE_STATUS,
        M.SECTION_HEAD_RESPONSE_REMARKS,
        M.RESPONSE_1_PERSON,
        M.RESPONSE_1_DATE,
        M.RESPONSE_1_STATUS,
        M.RESPONSE_1_REMARKS,
        M.RESPONSE_2_PERSON,
        M.RESPONSE_2_DATE,
        M.RESPONSE_2_STATUS,
        M.RESPONSE_2_REMARKS,
        M.FINAL_RESPONSE_PERSON,
        M.FINAL_RESPONSE_DATE,
        M.FINAL_RESPONSE_STATUS,
        M.FINAL_RESPONSE_REMARKS,
        M.REMARKS,
        M.STATUS_MASTER
    FROM VMaster.TBL_DRIVER_TRUCK_MASTER_MAPPING M
    INNER JOIN VMaster.TBL_DRIVER_MASTER_HDR D
        ON M.DRIVER_EMP_ID = D.DRIVER_EMP_ID
    INNER JOIN VMaster.TBL_TRUCK_MASTER_HDR T
        ON M.TRUCK_ID = T.TRUCK_ID
		WHERE M.STATUS_MASTER =@STATUS 
END
 
GO
--------------------------------------------------------------------------------
----GET_TRIP_TEMPLATE_MASTER

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

CREATE PROCEDURE [VMaster].[GET_TRIP_TEMPLATE_MASTER]
(
    @TRIP_TEMPLATE_ID INT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        A.TRIP_TEMPLATE_ID,
        A.TRIP_TEMPLATE_NAME,
        A.TRIP_TEMPLATE_DESCRIPTION,

        A.FROM_LOCATION_ID,
        FL.LOCATION_NAME AS FROM_LOCATION,

        A.TO_LOCATION_ID,
        TL.LOCATION_NAME AS TO_LOCATION,

        A.DISTANCE_KM,
        A.REMARKS,
        A.STATUS_MASTER

    FROM VMaster.TBL_TRIP_TEMPLATE_MASTER A

    LEFT JOIN VMaster.TBL_LOCATION_MASTER FL
        ON A.FROM_LOCATION_ID = FL.LOCATION_ID

    LEFT JOIN VMaster.TBL_LOCATION_MASTER TL
        ON A.TO_LOCATION_ID = TL.LOCATION_ID

    WHERE A.TRIP_TEMPLATE_ID = @TRIP_TEMPLATE_ID;
END
GO
------------------------------------------------------------------------