-- Overtime Request stored procedures (VRequest schema)
-- Synced from the deployed procedures, with the following fixes applied:
--   1. SAVE_OVERTIME_REQUEST: @Company_Id (undeclared) -> @COMPANY_ID parameter
--      (used by SP_Generate_Screen_Ref_No_With_Output_Parameter).
--   2. SAVE_OVERTIME_REQUEST: "Cash Advance Reference Number" message ->
--      "Overtime Request Reference Number".
--   3. SHOW_OVERTIME_REQUEST: WHERE @OT_REQUEST_REF_NO = @OT_REQUEST_REF_NO
--      (always true) -> WHERE OT_REQUEST_REF_NO = @OT_REQUEST_REF_NO.
-- Behavior notes:
--   * UPDATE blocks edits once STATUS_MASTER = 'CL' ("Already Submitted").
--   * DELETE requires @ROLE = 'Admin'.

USE [TBGS]
GO

/****** Object:  StoredProcedure [VREQUEST].[DELETE_OVERTIME_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.DELETE_OVERTIME_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[DELETE_OVERTIME_REQUEST];
GO
CREATE   PROCEDURE [VREQUEST].[DELETE_OVERTIME_REQUEST]
(
    @OT_REQUEST_REF_NO varchar(50),
    @USER VARCHAR(50),
    @ROLE VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON;

    IF @ROLE <> 'Admin'
    BEGIN
        SELECT
            'error' AS STATUS,
            'No Rights To Delete' AS MESSAGE,
            '' AS DATA
    END

   else IF NOT EXISTS
    (
        SELECT 1
        FROM [VREQUEST].[TBL_OVERTIME_REQUEST]
        WHERE OT_REQUEST_REF_NO = @OT_REQUEST_REF_NO
    )
    BEGIN
        SELECT
            'error' AS STATUS,
            'Overtime Request Not Found' AS MESSAGE,
            '' AS DATA;
    
    END
 
	else  begin
    DELETE FROM [VREQUEST].[TBL_OVERTIME_REQUEST]
    WHERE OT_REQUEST_REF_NO = @OT_REQUEST_REF_NO

    SELECT
        '' AS STATUS,  'Overtime Request Deleted Successfully' AS MESSAGE,@OT_REQUEST_REF_NO AS DATA
END
 end
GO

/****** Object:  StoredProcedure [VREQUEST].[GET_OVERTIME_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.GET_OVERTIME_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[GET_OVERTIME_REQUEST];
GO
CREATE   PROCEDURE [VREQUEST].[GET_OVERTIME_REQUEST]
(
    @OT_REQUEST_REF_NO varchar(50)
)
AS
BEGIN
    SET NOCOUNT ON

    SELECT
        SNO,
        OT_REQUEST_REF_NO,
        MONTH_ENTERED,
        YEAR_ENTERED,
        EMP_ID,
        FIRST_NAME,
        MIDDLE_NAME,
        LAST_NAME,
        COMPANY_ID,
        DEPARTMENT_ID,
        DESIGNATION_ID,
        DEPARTMENT_GROUP_ID,
        DESIGNATION_GROUP_ID,
        CAMP_ID,
        STORE_ID,
        EMPLOYMENT_TYPE_ID,
        CURRENCY_ID,
        OT_FROM_DATE,
        OT_TO_DATE,
        OT_HOURS,
        REQUEST_AMOUNT,
        APPROVED_AMOUNT,
        PAYMENT_REF_NO,
        PAYMENT_MODE_ID,
        BANK_ID,
        ACCOUNT_NO,
        PAID_STATUS,
        REASON,

        SECTION_HEAD_RESPONSE_PERSON_EMP_ID,
        SECTION_HEAD_RESPONSE_DATE,
        SECTION_HEAD_RESPONSE_STATUS,
        SECTION_HEAD_RESPONSE_REMARKS,

        RESPONSE_1_EMP_ID,
        RESPONSE_1_DATE,
        RESPONSE_1_STATUS,
        RESPONSE_1_REMARKS,

        RESPONSE_2_EMP_ID,
        RESPONSE_2_DATE,
        RESPONSE_2_STATUS,
        RESPONSE_2_REMARKS,

        FINAL_RESPONSE_EMP_ID,
        FINAL_RESPONSE_DATE,
        FINAL_RESPONSE_STATUS,
        FINAL_RESPONSE_REMARKS,

        REMARKS,
        STATUS_MASTER,
        CREATED_BY,
        CREATED_DATE,
        CREATED_MAC_ADDRESS,
        MODIFIED_BY,
        MODIFIED_DATE,
        MODIFIED_MAC_ADDRESS
    FROM [VREQUEST].[TBL_OVERTIME_REQUEST]
    WHERE OT_REQUEST_REF_NO = @OT_REQUEST_REF_NO
END
GO

/****** Object:  StoredProcedure [VREQUEST].[SAVE_OVERTIME_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.SAVE_OVERTIME_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[SAVE_OVERTIME_REQUEST];
GO
CREATE   PROCEDURE [VREQUEST].[SAVE_OVERTIME_REQUEST]
(
    @OT_REQUEST_REF_NO VARCHAR(50),
    @MONTH_ENTERED VARCHAR(25),
    @YEAR_ENTERED INT,
    @EMP_ID INT,
    @FIRST_NAME VARCHAR(50),
    @MIDDLE_NAME VARCHAR(50),
    @LAST_NAME VARCHAR(50),
    @COMPANY_ID INT,
    @DEPARTMENT_ID INT,
    @DESIGNATION_ID INT,
    @DEPARTMENT_GROUP_ID INT,
    @DESIGNATION_GROUP_ID INT,
    @CAMP_ID INT,
    @STORE_ID INT,
    @EMPLOYMENT_TYPE_ID INT,
    @CURRENCY_ID INT,
    @OT_FROM_DATE DATETIME,
    @OT_TO_DATE DATETIME,
    @OT_HOURS DECIMAL(10,2),
    @REQUEST_AMOUNT DECIMAL(15,2),
    @APPROVED_AMOUNT DECIMAL(15,2),
    @PAYMENT_REF_NO VARCHAR(50),
    @PAYMENT_MODE_ID INT,
    @BANK_ID INT,
    @ACCOUNT_NO VARCHAR(50),
    @PAID_STATUS VARCHAR(50),
    @REASON VARCHAR(3000),
    @SECTION_HEAD_RESPONSE_PERSON_EMP_ID INT,
    @SECTION_HEAD_RESPONSE_DATE DATETIME,
    @SECTION_HEAD_RESPONSE_STATUS VARCHAR(50),
    @SECTION_HEAD_RESPONSE_REMARKS VARCHAR(50),
    @RESPONSE_1_EMP_ID INT,
    @RESPONSE_1_DATE DATETIME,
    @RESPONSE_1_STATUS VARCHAR(50),
    @RESPONSE_1_REMARKS VARCHAR(50),
    @RESPONSE_2_EMP_ID INT,
    @RESPONSE_2_DATE DATETIME,
    @RESPONSE_2_STATUS VARCHAR(50),
    @RESPONSE_2_REMARKS VARCHAR(50),
    @FINAL_RESPONSE_EMP_ID INT,
    @FINAL_RESPONSE_DATE DATETIME,
    @FINAL_RESPONSE_STATUS VARCHAR(50),
    @FINAL_RESPONSE_REMARKS VARCHAR(50),
    @REMARKS VARCHAR(1000),
    @STATUS_MASTER VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

 EXEC VRequest.SP_Generate_Screen_Ref_No_With_Output_Parameter 'OT REQUEST REF NO',@COMPANY_ID,@OT_REQUEST_REF_NO OUT
 IF (@OT_REQUEST_REF_NO IS NULL OR @OT_REQUEST_REF_NO='')
BEGIN
	SELECT 'Error','Can''t Generate Overtime Request Reference Number. Contact Admin',''
END
ELSE
BEGIN
    INSERT INTO [VRequest].[TBL_OVERTIME_REQUEST]
    (
        OT_REQUEST_REF_NO,
        MONTH_ENTERED,
        YEAR_ENTERED,
        EMP_ID,
        FIRST_NAME,
        MIDDLE_NAME,
        LAST_NAME,
        COMPANY_ID,
        DEPARTMENT_ID,
        DESIGNATION_ID,
        DEPARTMENT_GROUP_ID,
        DESIGNATION_GROUP_ID,
        CAMP_ID,
        STORE_ID,
        EMPLOYMENT_TYPE_ID,
        CURRENCY_ID,
        OT_FROM_DATE,
        OT_TO_DATE,
        OT_HOURS,
        REQUEST_AMOUNT,
        APPROVED_AMOUNT,
        PAYMENT_REF_NO,
        PAYMENT_MODE_ID,
        BANK_ID,
        ACCOUNT_NO,
        PAID_STATUS,
        REASON,
        SECTION_HEAD_RESPONSE_PERSON_EMP_ID,
        SECTION_HEAD_RESPONSE_DATE,
        SECTION_HEAD_RESPONSE_STATUS,
        SECTION_HEAD_RESPONSE_REMARKS,
        RESPONSE_1_EMP_ID,
        RESPONSE_1_DATE,
        RESPONSE_1_STATUS,
        RESPONSE_1_REMARKS,
        RESPONSE_2_EMP_ID,
        RESPONSE_2_DATE,
        RESPONSE_2_STATUS,
        RESPONSE_2_REMARKS,
        FINAL_RESPONSE_EMP_ID,
        FINAL_RESPONSE_DATE,
        FINAL_RESPONSE_STATUS,
        FINAL_RESPONSE_REMARKS,
        REMARKS,
        STATUS_MASTER,
        CREATED_BY,
        CREATED_DATE,
        CREATED_MAC_ADDRESS,
        MODIFIED_BY,
        MODIFIED_DATE,
        MODIFIED_MAC_ADDRESS
    )
    VALUES
    (
        @OT_REQUEST_REF_NO,
        @MONTH_ENTERED,
        @YEAR_ENTERED,
        @EMP_ID,
        @FIRST_NAME,
        @MIDDLE_NAME,
        @LAST_NAME,
        @COMPANY_ID,
        @DEPARTMENT_ID,
        @DESIGNATION_ID,
        @DEPARTMENT_GROUP_ID,
        @DESIGNATION_GROUP_ID,
        @CAMP_ID,
        @STORE_ID,
        @EMPLOYMENT_TYPE_ID,
        @CURRENCY_ID,
        @OT_FROM_DATE,
        @OT_TO_DATE,
        @OT_HOURS,
        @REQUEST_AMOUNT,
        @APPROVED_AMOUNT,
        @PAYMENT_REF_NO,
        @PAYMENT_MODE_ID,
        @BANK_ID,
        @ACCOUNT_NO,
        @PAID_STATUS,
        @REASON,
        @SECTION_HEAD_RESPONSE_PERSON_EMP_ID,
        @SECTION_HEAD_RESPONSE_DATE,
        @SECTION_HEAD_RESPONSE_STATUS,
        @SECTION_HEAD_RESPONSE_REMARKS,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        @REMARKS,
        @STATUS_MASTER,
        @USER,
        GETDATE(),
        @MAC_ADDRESS,
        @USER,
        GETDATE(),
        @MAC_ADDRESS
    );

    DECLARE @LAST_INSERTED_ID INT = SCOPE_IDENTITY();

    SELECT
        '' AS STATUS,
        'Overtime Request Saved Successfully' AS MESSAGE,
        @LAST_INSERTED_ID AS DATA;
END
end
GO

/****** Object:  StoredProcedure [VREQUEST].[SHOW_OVERTIME_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.SHOW_OVERTIME_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[SHOW_OVERTIME_REQUEST];
GO
CREATE   PROCEDURE [VREQUEST].[SHOW_OVERTIME_REQUEST]
(
    @OT_REQUEST_REF_NO VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        SNO,
        OT_REQUEST_REF_NO,
        MONTH_ENTERED,
        YEAR_ENTERED,
        EMP_ID,
        FIRST_NAME,
        MIDDLE_NAME,
        LAST_NAME,
        COMPANY_ID,
        DEPARTMENT_ID,
        DESIGNATION_ID,
        DEPARTMENT_GROUP_ID,
        DESIGNATION_GROUP_ID,
        CAMP_ID,
        STORE_ID,
        EMPLOYMENT_TYPE_ID,
        CURRENCY_ID,
        OT_FROM_DATE,
        OT_TO_DATE,
        OT_HOURS,
        REQUEST_AMOUNT,
        APPROVED_AMOUNT,
        PAYMENT_REF_NO,
        PAYMENT_MODE_ID,
        BANK_ID,
        ACCOUNT_NO,
        PAID_STATUS,
        REASON,
        SECTION_HEAD_RESPONSE_STATUS,
        RESPONSE_1_STATUS,
        RESPONSE_2_STATUS,
        FINAL_RESPONSE_STATUS,
        REMARKS,
        STATUS_MASTER
    FROM [VREQUEST].[TBL_OVERTIME_REQUEST]
    WHERE OT_REQUEST_REF_NO = @OT_REQUEST_REF_NO
  
END
GO

/****** Object:  StoredProcedure [VREQUEST].[UPDATE_OVERTIME_REQUEST]    Script Date: 11-08-2026 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
IF OBJECT_ID('VRequest.UPDATE_OVERTIME_REQUEST', 'P') IS NOT NULL DROP PROCEDURE [VRequest].[UPDATE_OVERTIME_REQUEST];
GO
CREATE   PROCEDURE [VREQUEST].[UPDATE_OVERTIME_REQUEST]
(
    @SNO INT,
    @OT_REQUEST_REF_NO VARCHAR(50),
    @MONTH_ENTERED VARCHAR(25),
    @YEAR_ENTERED INT,
    @EMP_ID INT,
    @FIRST_NAME VARCHAR(50),
    @MIDDLE_NAME VARCHAR(50),
    @LAST_NAME VARCHAR(50),
    @COMPANY_ID INT,
    @DEPARTMENT_ID INT,
    @DESIGNATION_ID INT,
    @DEPARTMENT_GROUP_ID INT,
    @DESIGNATION_GROUP_ID INT,
    @CAMP_ID INT,
    @STORE_ID INT,
    @EMPLOYMENT_TYPE_ID INT,
    @CURRENCY_ID INT,
    @OT_FROM_DATE DATETIME,
    @OT_TO_DATE DATETIME,
    @OT_HOURS DECIMAL(10,2),
    @REQUEST_AMOUNT DECIMAL(15,2),
    @APPROVED_AMOUNT DECIMAL(15,2),
    @PAYMENT_REF_NO VARCHAR(50),
    @PAYMENT_MODE_ID INT,
    @BANK_ID INT,
    @ACCOUNT_NO VARCHAR(50),
    @PAID_STATUS VARCHAR(50),
    @REASON VARCHAR(3000),
    @REMARKS VARCHAR(1000),
    @STATUS_MASTER VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON;

    IF   EXISTS
    (
        SELECT 1
        FROM [VREQUEST].[TBL_OVERTIME_REQUEST]
        WHERE OT_REQUEST_REF_NO = @OT_REQUEST_REF_NO
		AND STATUS_MASTER ='CL'
     
    )
    BEGIN
        SELECT
            'error' AS STATUS,
            'Already Submitted Can''t do anychanges Contact To Admin' AS MESSAGE,
            '' AS DATA;

    END
	 else begin

    UPDATE [VREQUEST].[TBL_OVERTIME_REQUEST]
    SET
        OT_REQUEST_REF_NO = @OT_REQUEST_REF_NO,
        MONTH_ENTERED = @MONTH_ENTERED,
        YEAR_ENTERED = @YEAR_ENTERED,
        EMP_ID = @EMP_ID,
        FIRST_NAME = @FIRST_NAME,
        MIDDLE_NAME = @MIDDLE_NAME,
        LAST_NAME = @LAST_NAME,
        COMPANY_ID = @COMPANY_ID,
        DEPARTMENT_ID = @DEPARTMENT_ID,
        DESIGNATION_ID = @DESIGNATION_ID,
        DEPARTMENT_GROUP_ID = @DEPARTMENT_GROUP_ID,
        DESIGNATION_GROUP_ID = @DESIGNATION_GROUP_ID,
        CAMP_ID = @CAMP_ID,
        STORE_ID = @STORE_ID,
        EMPLOYMENT_TYPE_ID = @EMPLOYMENT_TYPE_ID,
        CURRENCY_ID = @CURRENCY_ID,
        OT_FROM_DATE = @OT_FROM_DATE,
        OT_TO_DATE = @OT_TO_DATE,
        OT_HOURS = @OT_HOURS,
        REQUEST_AMOUNT = @REQUEST_AMOUNT,
        APPROVED_AMOUNT = @APPROVED_AMOUNT,
        PAYMENT_REF_NO = @PAYMENT_REF_NO,
        PAYMENT_MODE_ID = @PAYMENT_MODE_ID,
        BANK_ID = @BANK_ID,
        ACCOUNT_NO = @ACCOUNT_NO,
        PAID_STATUS = @PAID_STATUS,
        REASON = @REASON,
        REMARKS = @REMARKS,
        STATUS_MASTER = @STATUS_MASTER,
        MODIFIED_BY = @USER,
        MODIFIED_DATE = GETDATE(),
        MODIFIED_MAC_ADDRESS = @MAC_ADDRESS
    WHERE OT_REQUEST_REF_NO = @OT_REQUEST_REF_NO
	
    SELECT
        '' AS STATUS,
        'Overtime Request Updated Successfully' AS MESSAGE,
        @OT_REQUEST_REF_NO AS DATA;
END
end
GO