-- Get purchase quotation dtl: additional-cost columns removed.
/* ---------- 1) GET_PURCHASE_QUOTATION_DTL : required date format ---------- */
ALTER   PROCEDURE [VPurchase].[GET_PURCHASE_QUOTATION_DTL]
(
    @PURCHASE_QUOTATION_DTL_ID INT
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
         D.PURCHASE_QUOTATION_DTL_ID
        ,D.PURCHASE_QUOTATION_NO
        ,D.PURCHASE_REQUEST_NO
        ,D.PURCHASE_REQUEST_DTL_ID
        ,D.CAMP_ID
        ,D.REQUEST_STORE_ID
        ,D.REFERENCE_TYPE_ID
        ,D.REFERENCE_NO
        ,D.LINE_NO
        ,D.MAIN_CATEGORY_ID
        ,D.SUB_CATEGORY_ID
        ,D.PRODUCT_ID
        ,P.PRODUCT_NAME
        ,D.NO_OF_PCS_PER_PACKING
        ,D.TOTAL_QUANTITY
        ,D.UOM_ID
        ,U.UOM_NAME
        ,D.TOTAL_PACKING
        ,D.ALT_UOM_ID
        ,AU.UOM_NAME AS ALT_UOM_NAME
        ,D.RATE
        ,D.SUB_TOTAL_AMOUNT_FC
        ,D.DISCOUNT_PERCENTAGE
        ,D.DISCOUNT_AMOUNT_FC
        ,D.TOTAL_PRODUCT_AMOUNT_FC
        ,D.TAX_ID
        ,D.TAX_PERCENTAGE
        ,D.TAX_AMOUNT_FC
        ,D.FINAL_AMOUNT_FC
        ,D.EXCHANGE_RATE
        ,D.SUB_TOTAL_AMOUNT_LC
        ,D.DISCOUNT_AMOUNT_LC

        ,D.TOTAL_PRODUCT_AMOUNT_LC
        ,D.TAX_AMOUNT_LC
        ,D.FINAL_AMOUNT_LC
        ,REPLACE(CONVERT(VARCHAR(50), D.REQUIRED_DATE, 106), ' ', '-') AS REQUIRED_DATE
        ,D.REASON
        ,D.REMARKS
        ,D.STATUS_ENTRY
        ,D.CREATED_BY
        ,D.CREATED_DATE
        ,D.CREATED_MAC_ADDRESS
        ,D.MODIFIED_BY
        ,D.MODIFIED_DATE
        ,D.MODIFIED_MAC_ADDRESS
    FROM VPurchase.TBL_PURCHASE_QUOTATION_DTL D
    LEFT JOIN VMaster.TBL_PRODUCT_MASTER P ON P.PRODUCT_ID = D.PRODUCT_ID
    LEFT JOIN VMaster.TBL_UOM_MASTER      U  ON U.UOM_ID      = D.UOM_ID
    LEFT JOIN VMaster.TBL_UOM_MASTER      AU ON AU.UOM_ID     = D.ALT_UOM_ID
    WHERE D.PURCHASE_QUOTATION_DTL_ID = @PURCHASE_QUOTATION_DTL_ID;
END
GO
-- Get purchase quotation hdr: additional-cost columns removed.
ALTER PROCEDURE [VPurchase].[GET_PURCHASE_QUOTATION_HDR]
(
    @PURCHASE_QUOTATION_NO VARCHAR(50) = NULL,
    @SNO INT = NULL,
    @Status VARCHAR(20) = 'ALL',
    @FromDate DATE = NULL,
    @ToDate DATE = NULL,
    @CompanyId INT = NULL,
    @SupplierBpId INT = NULL,
    @Search NVARCHAR(200) = NULL,
    @Page INT = NULL,
    @PageSize INT = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    IF @PURCHASE_QUOTATION_NO IS NOT NULL
    BEGIN
        SELECT * FROM [VPurchase].[TBL_PURCHASE_QUOTATION_HDR]
        WHERE PURCHASE_QUOTATION_NO = @PURCHASE_QUOTATION_NO;
        RETURN;
    END

    IF @SNO IS NOT NULL
    BEGIN
        SELECT * FROM [VPurchase].[TBL_PURCHASE_QUOTATION_HDR]
        WHERE SNO = @SNO;
        RETURN;
    END

    DROP TABLE IF EXISTS #REPORT_PQ_HDR;
    ;WITH CTE AS
    (
        SELECT
             A.SNO AS sno
            ,A.PURCHASE_QUOTATION_NO AS purchaseQuotationNo
            ,A.PURCHASE_QUOTATION_NO AS refNo
            ,COALESCE(
                NULLIF(LTRIM(RTRIM(A.PURCHASE_REQUEST_NO)), ''),
                (SELECT MIN(LTRIM(RTRIM(D.PURCHASE_REQUEST_NO)))
                   FROM [VPurchase].[TBL_PURCHASE_QUOTATION_DTL] D
                  WHERE D.PURCHASE_QUOTATION_NO = A.PURCHASE_QUOTATION_NO
                    AND NULLIF(LTRIM(RTRIM(D.PURCHASE_REQUEST_NO)), '') IS NOT NULL)
             ) AS purchaseRequestNo
            ,A.PURCHASE_QUOTATION_DATE AS purchaseQuotationDate
            ,A.COMPANY_ID AS companyId
            ,C.COMPANY_NAME AS companyName
            ,A.SUPPLIER_BP_ID AS supplierBpId
            ,BP.BP_NAME AS supplierName
            ,A.BRANCH_ID AS branchId
            ,BR.BRANCH_NAME AS branchName
            ,A.PO_STORE_ID AS poStoreId
            ,PS.STORE_NAME AS poStoreName
            ,A.SUPPLIER_QUOTATION_NO AS supplierQuotationNo
            ,A.SUPPLIER_QUOTATION_DATE AS supplierQuotationDate
            ,A.VALID_FROM_DATE AS validFromDate
            ,A.VALID_TO_DATE AS validToDate
            ,A.PAYMENT_TERM_ID AS paymentTermId
            ,A.PAYMENT_MODE_ID AS paymentModeId
            ,A.SHIPMENT_MODE_ID AS shipmentModeId
            ,SM.SHIPMENT_MODE_NAME AS shipmentModeName
            ,A.DELIVERY_DATE AS deliveryDate
            ,A.DELIVERY_TERM AS deliveryTerm
            ,A.SHIPMENT_REMARKS AS shipmentRemarks
            ,A.DELIVERY_LOCATION_ID AS deliveryLocationId
            ,A.TOTAL_SUB_TOTAL_HDR_AMOUNT_FC AS totalSubTotalHdrAmountFc
            ,A.TOTAL_DISCOUNT_HDR_AMOUNT_FC AS totalDiscountHdrAmountFc

            ,A.TOTAL_PRODUCT_HDR_AMOUNT_FC AS totalProductHdrAmountFc
            ,A.TOTAL_VAT_HDR_AMOUNT_FC AS totalVatHdrAmountFc
            ,A.FINAL_PRODUCT_HDR_AMOUNT_FC AS finalProductHdrAmountFc
            ,A.CURRENCY_ID AS currencyId
            ,A.EXCHANGE_RATE AS exchangeRate
            ,A.TOTAL_SUB_TOTAL_HDR_AMOUNT_LC AS totalSubTotalHdrAmountLc
            ,A.TOTAL_DISCOUNT_HDR_AMOUNT_LC AS totalDiscountHdrAmountLc

            ,A.TOTAL_PRODUCT_HDR_AMOUNT_LC AS totalProductHdrAmountLc
            ,A.TOTAL_TAX_HDR_AMOUNT_LC AS totalTaxHdrAmountLc
            ,A.FINAL_PRODUCT_HDR_AMOUNT_LC AS finalProductHdrAmountLc
            ,A.SECTION_HEAD_RESPONSE_PERSON_EMP_ID AS sectionHeadPersonEmpId
            ,A.SECTION_HEAD_RESPONSE_DATE AS sectionHeadDate
            ,CASE UPPER(LTRIM(RTRIM(ISNULL(A.SECTION_HEAD_RESPONSE_STATUS, ''))))
                WHEN 'APPROVAL' THEN 'APPROVED'
                WHEN 'APPROVED' THEN 'APPROVED'
                WHEN 'REJECT'   THEN 'REJECTED'
                WHEN 'REJECTED' THEN 'REJECTED'
                WHEN 'HOLD'     THEN 'HOLD'
                ELSE '' END AS sectionHeadStatus
            ,A.SECTION_HEAD_RESPONSE_REMARKS AS sectionHeadRemarks
            ,A.SECTION_HEAD_RESPONSE_IP_ADDRESS AS sectionHeadIpAddress
            ,A.RESPONSE_1_EMP_ID AS response1EmpId
            ,A.RESPONSE_1_DATE AS response1Date
            ,CASE UPPER(LTRIM(RTRIM(ISNULL(A.RESPONSE_1_STATUS, ''))))
                WHEN 'APPROVAL' THEN 'APPROVED'
                WHEN 'APPROVED' THEN 'APPROVED'
                WHEN 'REJECT'   THEN 'REJECTED'
                WHEN 'REJECTED' THEN 'REJECTED'
                WHEN 'HOLD'     THEN 'HOLD'
                ELSE '' END AS response1Status
            ,A.RESPONSE_1_REMARKS AS response1Remarks
            ,A.RESPONSE_1_IP_ADDRESS AS response1IpAddress
            ,A.RESPONSE_2_EMP_ID AS response2EmpId
            ,A.RESPONSE_2_DATE AS response2Date
            ,CASE UPPER(LTRIM(RTRIM(ISNULL(A.RESPONSE_2_STATUS, ''))))
                WHEN 'APPROVAL' THEN 'APPROVED'
                WHEN 'APPROVED' THEN 'APPROVED'
                WHEN 'REJECT'   THEN 'REJECTED'
                WHEN 'REJECTED' THEN 'REJECTED'
                WHEN 'HOLD'     THEN 'HOLD'
                ELSE '' END AS response2Status
            ,A.RESPONSE_2_REMARKS AS response2Remarks
            ,A.RESPONSE_2_IP_ADDRESS AS response2IpAddress
            ,A.FINAL_RESPONSE_EMP_ID AS finalResponseEmpId
            ,A.FINAL_RESPONSE_DATE AS finalResponseDate
            ,A.FINAL_RESPONSE_REMARKS AS finalResponseRemarks
            ,A.FINAL_RESPONSE_IP_ADDRESS AS finalResponseIpAddress
            -- Non-cascading terminal rollup, same rule as Purchase Request:
            -- APPROVED only when the FINAL level is approved, REJECTED if any
            -- level rejected, HOLD if any level held, otherwise PENDING.
            ,CASE
                WHEN UPPER(LTRIM(RTRIM(ISNULL(A.FINAL_RESPONSE_STATUS,'')))) IN ('APPROVAL','APPROVED')
                    THEN 'APPROVED'
                WHEN UPPER(LTRIM(RTRIM(ISNULL(A.FINAL_RESPONSE_STATUS,'')))) IN ('REJECT','REJECTED')
                    OR  UPPER(LTRIM(RTRIM(ISNULL(A.RESPONSE_2_STATUS,'')))) IN ('REJECT','REJECTED')
                    OR  UPPER(LTRIM(RTRIM(ISNULL(A.RESPONSE_1_STATUS,'')))) IN ('REJECT','REJECTED')
                    OR  UPPER(LTRIM(RTRIM(ISNULL(A.SECTION_HEAD_RESPONSE_STATUS,'')))) IN ('REJECT','REJECTED')
                    THEN 'REJECTED'
                WHEN UPPER(LTRIM(RTRIM(ISNULL(A.FINAL_RESPONSE_STATUS,'')))) = 'HOLD'
                    OR  UPPER(LTRIM(RTRIM(ISNULL(A.RESPONSE_2_STATUS,'')))) = 'HOLD'
                    OR  UPPER(LTRIM(RTRIM(ISNULL(A.RESPONSE_1_STATUS,'')))) = 'HOLD'
                    OR  UPPER(LTRIM(RTRIM(ISNULL(A.SECTION_HEAD_RESPONSE_STATUS,'')))) = 'HOLD'
                    THEN 'HOLD'
                ELSE 'PENDING' END AS finalResponseStatus
            ,A.QUOTATION_STATUS_ID AS quotationStatusId
            ,ST.STATUS_NAME AS quotationStatusName
            ,A.REMARKS AS remarks
            ,A.STATUS_ENTRY AS statusEntry
            ,A.CREATED_BY AS createdBy
            ,A.CREATED_DATE AS createdDate
        FROM [VPurchase].[TBL_PURCHASE_QUOTATION_HDR] A
        LEFT JOIN VMaster.TBL_COMPANY_MASTER C  ON C.COMPANY_ID = A.COMPANY_ID
        LEFT JOIN VMaster.TBL_BUSINESS_PARTNER_MASTER BP ON BP.BP_ID = A.SUPPLIER_BP_ID
        LEFT JOIN VMaster.TBL_BRANCH_MASTER BR ON BR.BRANCH_ID = A.BRANCH_ID
        LEFT JOIN VMaster.TBL_STORE_MASTER PS ON PS.STORE_ID = A.PO_STORE_ID
        LEFT JOIN VMaster.TBL_SHIPMENT_MODE_MASTER SM ON SM.SHIPMENT_MODE_ID = A.SHIPMENT_MODE_ID
        LEFT JOIN VMaster.TBL_STATUS_MASTER ST ON ST.STATUS_ID = A.QUOTATION_STATUS_ID
        WHERE (@FromDate IS NULL OR CONVERT(DATE, A.PURCHASE_QUOTATION_DATE) >= @FromDate)
          AND (@ToDate   IS NULL OR CONVERT(DATE, A.PURCHASE_QUOTATION_DATE) <= @ToDate)
          AND (@CompanyId IS NULL OR A.COMPANY_ID = @CompanyId)
          AND (@SupplierBpId IS NULL OR A.SUPPLIER_BP_ID = @SupplierBpId)
    )
    SELECT * INTO #REPORT_PQ_HDR
    FROM CTE
    WHERE (@Status = 'ALL' OR finalResponseStatus = UPPER(LTRIM(RTRIM(@Status))))
      AND (@Search IS NULL OR CONCAT(
          ISNULL(CAST(sno AS VARCHAR(20)), ''), ' ',
          ISNULL(refNo, ''), ' ',
          ISNULL(purchaseRequestNo, ''), ' ',
          ISNULL(supplierName, ''), ' ',
          ISNULL(supplierQuotationNo, ''), ' ',
          ISNULL(companyName, ''), ' ',
          ISNULL(branchName, ''), ' ',
          ISNULL(poStoreName, ''), ' ',
          ISNULL(shipmentModeName, '')
      ) LIKE '%' + @Search + '%');

    IF @Page IS NOT NULL AND @PageSize IS NOT NULL
    BEGIN
        SELECT COUNT(*) AS Total FROM #REPORT_PQ_HDR;
        SELECT * FROM #REPORT_PQ_HDR
        ORDER BY sno DESC
        OFFSET (@Page - 1) * @PageSize ROWS
        FETCH NEXT @PageSize ROWS ONLY;
    END
    ELSE
    BEGIN
        SELECT * FROM #REPORT_PQ_HDR ORDER BY sno DESC;
    END
    DROP TABLE IF EXISTS #REPORT_PQ_HDR;
END
GO
-- Save purchase quotation dtl: additional-cost columns removed.
/* ------------------------------------------------------------------ */
/* 1. SAVE_PURCHASE_QUOTATION_DTL                                      */
/* ------------------------------------------------------------------ */
ALTER PROCEDURE [VPurchase].[SAVE_PURCHASE_QUOTATION_DTL]
(
    @PURCHASE_QUOTATION_NO VARCHAR(50),
    @PURCHASE_REQUEST_NO VARCHAR(50),
    @PURCHASE_REQUEST_DTL_ID INT,
    @CAMP_ID INT,
    @REQUEST_STORE_ID INT,
    @REFERENCE_TYPE_ID INT,
    @REFERENCE_NO VARCHAR(50),
    @LINE_NO INT,
    @MAIN_CATEGORY_ID INT,
    @SUB_CATEGORY_ID INT,
    @PRODUCT_ID INT,
    @NO_OF_PCS_PER_PACKING DECIMAL(15,3),
    @TOTAL_QUANTITY DECIMAL(15,3),
    @UOM_ID INT,
    @TOTAL_PACKING DECIMAL(15,3),
    @ALT_UOM_ID INT,
    @RATE DECIMAL(15,3),
    @SUB_TOTAL_AMOUNT_FC DECIMAL(15,3),
    @DISCOUNT_PERCENTAGE DECIMAL(15,3),
    @DISCOUNT_AMOUNT_FC DECIMAL(15,3),
    @TOTAL_PRODUCT_AMOUNT_FC DECIMAL(15,3),
    @TAX_ID INT,
    @TAX_PERCENTAGE DECIMAL(15,3),
    @TAX_AMOUNT_FC DECIMAL(15,3),
    @FINAL_AMOUNT_FC DECIMAL(15,3),
    @EXCHANGE_RATE DECIMAL(15,6),
    @SUB_TOTAL_AMOUNT_LC DECIMAL(15,3),
    @DISCOUNT_AMOUNT_LC DECIMAL(15,3),

    @TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,3),
    @TAX_AMOUNT_LC DECIMAL(15,3),
    @FINAL_AMOUNT_LC DECIMAL(15,3),
    @REQUIRED_DATE DATETIME,
    @REASON VARCHAR(500),
    @REMARKS VARCHAR(500),
    @ITEM_TYPE VARCHAR(50) = NULL,
    @STATUS_ENTRY VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    -- Validate parent header exists
    IF NOT EXISTS (
        SELECT 1 FROM [VPurchase].[TBL_PURCHASE_QUOTATION_HDR]
        WHERE PURCHASE_QUOTATION_NO = @PURCHASE_QUOTATION_NO
    )
    BEGIN
        SELECT 'Error', 'Parent Purchase Quotation not found. Cannot save detail.', ''
        RETURN
    END

    -- Prevent duplicate LINE_NO per quotation
    IF EXISTS (
        SELECT 1 FROM [VPurchase].[TBL_PURCHASE_QUOTATION_DTL]
        WHERE PURCHASE_QUOTATION_NO = @PURCHASE_QUOTATION_NO
          AND LINE_NO = @LINE_NO
    )
    BEGIN
        SELECT 'Error', 'Line No ' + CAST(@LINE_NO AS VARCHAR(10)) + ' already exists for this Quotation.', ''
        RETURN
    END

    INSERT INTO [VPurchase].[TBL_PURCHASE_QUOTATION_DTL]
    (
        PURCHASE_QUOTATION_NO, PURCHASE_REQUEST_NO, PURCHASE_REQUEST_DTL_ID,
        CAMP_ID, REQUEST_STORE_ID, REFERENCE_TYPE_ID, REFERENCE_NO, LINE_NO,
        MAIN_CATEGORY_ID, SUB_CATEGORY_ID, PRODUCT_ID,
        NO_OF_PCS_PER_PACKING, TOTAL_QUANTITY, UOM_ID, TOTAL_PACKING, ALT_UOM_ID,
        RATE, SUB_TOTAL_AMOUNT_FC, DISCOUNT_PERCENTAGE, DISCOUNT_AMOUNT_FC,
        TOTAL_PRODUCT_AMOUNT_FC, TAX_ID, TAX_PERCENTAGE, TAX_AMOUNT_FC, FINAL_AMOUNT_FC,
        EXCHANGE_RATE, SUB_TOTAL_AMOUNT_LC, DISCOUNT_AMOUNT_LC,
        TOTAL_PRODUCT_AMOUNT_LC, TAX_AMOUNT_LC, FINAL_AMOUNT_LC,
        REQUIRED_DATE, REASON, REMARKS, ITEM_TYPE, STATUS_ENTRY,
        CREATED_BY, CREATED_DATE, CREATED_MAC_ADDRESS,
        MODIFIED_BY, MODIFIED_DATE, MODIFIED_MAC_ADDRESS
    )
    VALUES
    (
        @PURCHASE_QUOTATION_NO, @PURCHASE_REQUEST_NO, @PURCHASE_REQUEST_DTL_ID,
        @CAMP_ID, @REQUEST_STORE_ID, @REFERENCE_TYPE_ID, @REFERENCE_NO, @LINE_NO,
        @MAIN_CATEGORY_ID, @SUB_CATEGORY_ID, @PRODUCT_ID,
        @NO_OF_PCS_PER_PACKING, @TOTAL_QUANTITY, @UOM_ID, @TOTAL_PACKING, @ALT_UOM_ID,
        @RATE, @SUB_TOTAL_AMOUNT_FC, @DISCOUNT_PERCENTAGE, @DISCOUNT_AMOUNT_FC,
        @TOTAL_PRODUCT_AMOUNT_FC, @TAX_ID, @TAX_PERCENTAGE, @TAX_AMOUNT_FC, @FINAL_AMOUNT_FC,
        @EXCHANGE_RATE, @SUB_TOTAL_AMOUNT_LC, @DISCOUNT_AMOUNT_LC,
        @TOTAL_PRODUCT_AMOUNT_LC, @TAX_AMOUNT_LC, @FINAL_AMOUNT_LC,
        @REQUIRED_DATE, @REASON, @REMARKS, @ITEM_TYPE, ISNULL(@STATUS_ENTRY, 'AC'),
        @USER, GETDATE(), @MAC_ADDRESS,
        @USER, GETDATE(), @MAC_ADDRESS
    )

    DECLARE @LAST_INSERTED_ID INT = SCOPE_IDENTITY();

    SELECT '' AS STATUS, 'Data Saved Successfully' AS MESSAGE, @LAST_INSERTED_ID AS DATA;
END
GO
-- Save purchase quotation hdr: additional-cost columns removed.
ALTER PROCEDURE [VPurchase].[SAVE_PURCHASE_QUOTATION_HDR]
(
    @PURCHASE_REQUEST_NO VARCHAR(50) = NULL,
    @PURCHASE_QUOTATION_NO VARCHAR(50),
    @PURCHASE_QUOTATION_DATE DATETIME,
    @COMPANY_ID INT,
    @SUPPLIER_BP_ID INT,
    @BRANCH_ID INT,
    @PO_STORE_ID INT,
    @SUPPLIER_QUOTATION_NO VARCHAR(100),
    @SUPPLIER_QUOTATION_DATE DATETIME,
    @VALID_FROM_DATE DATETIME,
    @VALID_TO_DATE DATETIME,
    @PAYMENT_TERM_ID INT,
    @PAYMENT_MODE_ID INT,
    @SHIPMENT_MODE_ID INT,
    @DELIVERY_DATE DATETIME,
    @DELIVERY_TERM VARCHAR(100),
    @SHIPMENT_REMARKS VARCHAR(500),
    @DELIVERY_LOCATION_ID INT,
    @TOTAL_SUB_TOTAL_HDR_AMOUNT_FC DECIMAL(15,3),
    @TOTAL_DISCOUNT_HDR_AMOUNT_FC DECIMAL(15,3),

    @TOTAL_PRODUCT_HDR_AMOUNT_FC DECIMAL(15,3),
    @TOTAL_VAT_HDR_AMOUNT_FC DECIMAL(15,3),
    @FINAL_PRODUCT_HDR_AMOUNT_FC DECIMAL(15,3),
    @CURRENCY_ID INT,
    @EXCHANGE_RATE DECIMAL(15,6),
    @TOTAL_SUB_TOTAL_HDR_AMOUNT_LC DECIMAL(15,3),
    @TOTAL_DISCOUNT_HDR_AMOUNT_LC DECIMAL(15,3),

    @TOTAL_PRODUCT_HDR_AMOUNT_LC DECIMAL(15,3),
    @TOTAL_TAX_HDR_AMOUNT_LC DECIMAL(15,3),
    @FINAL_PRODUCT_HDR_AMOUNT_LC DECIMAL(15,3),
    @QUOTATION_STATUS_ID INT,
    @REMARKS VARCHAR(500),
    @STATUS_ENTRY VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    -- Generate ref no if not provided
    IF (@PURCHASE_QUOTATION_NO IS NULL OR @PURCHASE_QUOTATION_NO = '')
    BEGIN
        EXEC VRequest.SP_Generate_Screen_Ref_No_With_Output_Parameter
             'PURCHASE QUOTATION', @COMPANY_ID, @PURCHASE_QUOTATION_NO OUT
    END

    IF (@PURCHASE_QUOTATION_NO IS NULL OR @PURCHASE_QUOTATION_NO = '')
    BEGIN
        SELECT 'Error', 'Can''t Generate Purchase Quotation Reference Number. Contact Admin.', ''
        RETURN
    END

    INSERT INTO [VPurchase].[TBL_PURCHASE_QUOTATION_HDR]
    (
        PURCHASE_REQUEST_NO,
        PURCHASE_QUOTATION_NO, PURCHASE_QUOTATION_DATE,
        COMPANY_ID, SUPPLIER_BP_ID, BRANCH_ID, PO_STORE_ID,
        SUPPLIER_QUOTATION_NO, SUPPLIER_QUOTATION_DATE,
        VALID_FROM_DATE, VALID_TO_DATE,
        PAYMENT_TERM_ID, PAYMENT_MODE_ID, SHIPMENT_MODE_ID,
        DELIVERY_DATE, DELIVERY_TERM, SHIPMENT_REMARKS, DELIVERY_LOCATION_ID,
        TOTAL_SUB_TOTAL_HDR_AMOUNT_FC, TOTAL_DISCOUNT_HDR_AMOUNT_FC,
        TOTAL_PRODUCT_HDR_AMOUNT_FC,
        TOTAL_VAT_HDR_AMOUNT_FC, FINAL_PRODUCT_HDR_AMOUNT_FC,
        CURRENCY_ID, EXCHANGE_RATE,
        TOTAL_SUB_TOTAL_HDR_AMOUNT_LC, TOTAL_DISCOUNT_HDR_AMOUNT_LC,
        TOTAL_PRODUCT_HDR_AMOUNT_LC,
        TOTAL_TAX_HDR_AMOUNT_LC, FINAL_PRODUCT_HDR_AMOUNT_LC,
        QUOTATION_STATUS_ID, REMARKS, STATUS_ENTRY,
        CREATED_BY, CREATED_DATE, CREATED_MAC_ADDRESS,
        MODIFIED_BY, MODIFIED_DATE, MODIFIED_MAC_ADDRESS
    )
    VALUES
    (
        @PURCHASE_REQUEST_NO,
        @PURCHASE_QUOTATION_NO, @PURCHASE_QUOTATION_DATE,
        @COMPANY_ID, @SUPPLIER_BP_ID, @BRANCH_ID, @PO_STORE_ID,
        @SUPPLIER_QUOTATION_NO, @SUPPLIER_QUOTATION_DATE,
        @VALID_FROM_DATE, @VALID_TO_DATE,
        @PAYMENT_TERM_ID, @PAYMENT_MODE_ID, @SHIPMENT_MODE_ID,
        @DELIVERY_DATE, @DELIVERY_TERM, @SHIPMENT_REMARKS, @DELIVERY_LOCATION_ID,
        @TOTAL_SUB_TOTAL_HDR_AMOUNT_FC, @TOTAL_DISCOUNT_HDR_AMOUNT_FC,
        @TOTAL_PRODUCT_HDR_AMOUNT_FC,
        @TOTAL_VAT_HDR_AMOUNT_FC, @FINAL_PRODUCT_HDR_AMOUNT_FC,
        @CURRENCY_ID, @EXCHANGE_RATE,
        @TOTAL_SUB_TOTAL_HDR_AMOUNT_LC, @TOTAL_DISCOUNT_HDR_AMOUNT_LC,
        @TOTAL_PRODUCT_HDR_AMOUNT_LC,
        @TOTAL_TAX_HDR_AMOUNT_LC, @FINAL_PRODUCT_HDR_AMOUNT_LC,
        @QUOTATION_STATUS_ID, @REMARKS,
        -- Default to CF (Draft). Only SUBMIT_PURCHASE_QUOTATION may set CL.
        ISNULL(NULLIF(LTRIM(RTRIM(@STATUS_ENTRY)), ''), 'CF'),
        @USER, GETDATE(), @MAC_ADDRESS,
        @USER, GETDATE(), @MAC_ADDRESS
    )

    SELECT '', 'Data Saved Successfully', @PURCHASE_QUOTATION_NO
END
GO
-- Show purchase quotation dtl: additional-cost columns removed.
/* ------------------------------------------------------------------ */
/* 3. SHOW_PURCHASE_QUOTATION_DTL                                      */
/* ------------------------------------------------------------------ */
ALTER PROCEDURE [VPurchase].[SHOW_PURCHASE_QUOTATION_DTL]
(
    @STATUS                  VARCHAR(20),
    @PURCHASE_QUOTATION_NO   VARCHAR(50) = NULL
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
         D.PURCHASE_QUOTATION_DTL_ID
        ,D.PURCHASE_QUOTATION_NO
        ,D.PURCHASE_REQUEST_NO
        ,D.PURCHASE_REQUEST_DTL_ID
        ,D.CAMP_ID
        ,D.REQUEST_STORE_ID
        ,D.REFERENCE_TYPE_ID
        ,D.REFERENCE_NO
        ,D.LINE_NO
        ,D.MAIN_CATEGORY_ID
        ,MC.MAIN_CATEGORY_NAME
        ,D.SUB_CATEGORY_ID
        ,SC.SUB_CATEGORY_NAME
        ,D.PRODUCT_ID
        ,P.PRODUCT_NAME
        ,D.NO_OF_PCS_PER_PACKING
        ,D.TOTAL_QUANTITY
        ,D.UOM_ID
        ,U.UOM_NAME
        ,D.TOTAL_PACKING
        ,D.ALT_UOM_ID
        ,AU.UOM_NAME AS ALT_UOM_NAME
        ,D.RATE
        ,D.SUB_TOTAL_AMOUNT_FC
        ,D.DISCOUNT_PERCENTAGE
        ,D.DISCOUNT_AMOUNT_FC
        ,D.TOTAL_PRODUCT_AMOUNT_FC
        ,D.TAX_ID
        ,T.TAX_NAME
        ,D.TAX_PERCENTAGE
        ,D.TAX_AMOUNT_FC
        ,D.FINAL_AMOUNT_FC
        ,D.EXCHANGE_RATE
        ,D.SUB_TOTAL_AMOUNT_LC
        ,D.DISCOUNT_AMOUNT_LC

        ,D.TOTAL_PRODUCT_AMOUNT_LC
        ,D.TAX_AMOUNT_LC
        ,D.FINAL_AMOUNT_LC
        ,D.REQUIRED_DATE
        ,D.REASON
        ,D.REMARKS
        ,D.ITEM_TYPE
        ,D.STATUS_ENTRY
        ,D.CREATED_BY
        ,D.CREATED_DATE
        ,D.CREATED_MAC_ADDRESS
        ,D.MODIFIED_BY
        ,D.MODIFIED_DATE
        ,D.MODIFIED_MAC_ADDRESS
    FROM VPurchase.TBL_PURCHASE_QUOTATION_DTL D
    LEFT JOIN VMaster.TBL_PRODUCT_MASTER           P  ON P.PRODUCT_ID       = D.PRODUCT_ID
    LEFT JOIN VMaster.TBL_UOM_MASTER                U  ON U.UOM_ID           = D.UOM_ID
    LEFT JOIN VMaster.TBL_UOM_MASTER                AU ON AU.UOM_ID          = D.ALT_UOM_ID
    LEFT JOIN VMaster.TBL_PRODUCT_MAIN_CATEGORY_MASTER MC ON MC.MAIN_CATEGORY_ID = D.MAIN_CATEGORY_ID
    LEFT JOIN VMaster.TBL_PRODUCT_SUB_CATEGORY_MASTER  SC ON SC.SUB_CATEGORY_ID  = D.SUB_CATEGORY_ID
    LEFT JOIN VMaster.TBL_TAX_MASTER                T  ON T.TAX_ID            = D.TAX_ID
    WHERE (@STATUS = 'ALL' OR D.STATUS_ENTRY = @STATUS)
      AND (@PURCHASE_QUOTATION_NO IS NULL OR D.PURCHASE_QUOTATION_NO = @PURCHASE_QUOTATION_NO)
    ORDER BY D.LINE_NO, D.PURCHASE_QUOTATION_DTL_ID;
END
GO
-- Show purchase quotation hdr: additional-cost columns removed.
/* ========== 5. SHOW ========== */
ALTER PROCEDURE [VPurchase].[SHOW_PURCHASE_QUOTATION_HDR]
(
    @STATUS VARCHAR(20)
)
AS
BEGIN
    SET NOCOUNT ON

    SELECT
         A.[SNO]
        ,A.[PURCHASE_QUOTATION_NO]
        ,A.[PURCHASE_QUOTATION_DATE]
        ,A.[COMPANY_ID]
        ,C.[COMPANY_NAME]
        ,A.[SUPPLIER_BP_ID]
        ,BP.[BP_NAME] AS SUPPLIER_NAME
        ,A.[BRANCH_ID]
        ,BR.[BRANCH_NAME]
        ,A.[PO_STORE_ID]
        ,PS.[STORE_NAME] AS PO_STORE_NAME
        ,A.[SUPPLIER_QUOTATION_NO]
        ,A.[SUPPLIER_QUOTATION_DATE]
        ,A.[VALID_FROM_DATE]
        ,A.[VALID_TO_DATE]
        ,A.[PAYMENT_TERM_ID]
        ,A.[PAYMENT_MODE_ID]
        ,A.[SHIPMENT_MODE_ID]
        ,SM.[SHIPMENT_MODE_NAME]
        ,A.[DELIVERY_DATE]
        ,A.[DELIVERY_TERM]
        ,A.[SHIPMENT_REMARKS]
        ,A.[DELIVERY_LOCATION_ID]
        ,A.[TOTAL_SUB_TOTAL_HDR_AMOUNT_FC]
        ,A.[TOTAL_DISCOUNT_HDR_AMOUNT_FC]

        ,A.[TOTAL_PRODUCT_HDR_AMOUNT_FC]
        ,A.[TOTAL_VAT_HDR_AMOUNT_FC]
        ,A.[FINAL_PRODUCT_HDR_AMOUNT_FC]
        ,A.[CURRENCY_ID]
        ,A.[EXCHANGE_RATE]
        ,A.[TOTAL_SUB_TOTAL_HDR_AMOUNT_LC]
        ,A.[TOTAL_DISCOUNT_HDR_AMOUNT_LC]

        ,A.[TOTAL_PRODUCT_HDR_AMOUNT_LC]
        ,A.[TOTAL_TAX_HDR_AMOUNT_LC]
        ,A.[FINAL_PRODUCT_HDR_AMOUNT_LC]
        ,A.[QUOTATION_STATUS_ID]
        ,ST.[STATUS_NAME] AS QUOTATION_STATUS_NAME
        ,A.[REMARKS]
        ,A.[STATUS_ENTRY]
        ,A.[CREATED_BY]
        ,A.[CREATED_DATE]
        ,A.[MODIFIED_BY]
        ,A.[MODIFIED_DATE]
    FROM [VPurchase].[TBL_PURCHASE_QUOTATION_HDR] A
    LEFT JOIN VMaster.TBL_COMPANY_MASTER C  ON C.COMPANY_ID = A.COMPANY_ID
    LEFT JOIN VMaster.TBL_BUSINESS_PARTNER_MASTER BP ON BP.BP_ID = A.SUPPLIER_BP_ID
    LEFT JOIN VMaster.TBL_BRANCH_MASTER BR ON BR.BRANCH_ID = A.BRANCH_ID
    LEFT JOIN VMaster.TBL_STORE_MASTER PS ON PS.STORE_ID = A.PO_STORE_ID
    LEFT JOIN VMaster.TBL_SHIPMENT_MODE_MASTER SM ON SM.SHIPMENT_MODE_ID = A.SHIPMENT_MODE_ID
    LEFT JOIN VMaster.TBL_STATUS_MASTER ST ON ST.STATUS_ID = A.QUOTATION_STATUS_ID
    WHERE @STATUS = 'ALL' OR A.STATUS_ENTRY = @STATUS
END
GO
-- Update purchase quotation dtl: additional-cost columns removed.
/* ------------------------------------------------------------------ */
/* 2. UPDATE_PURCHASE_QUOTATION_DTL                                    */
/* ------------------------------------------------------------------ */
ALTER PROCEDURE [VPurchase].[UPDATE_PURCHASE_QUOTATION_DTL]
(
    @PURCHASE_QUOTATION_DTL_ID INT,
    @PURCHASE_QUOTATION_NO VARCHAR(50),
    @PURCHASE_REQUEST_NO VARCHAR(50),
    @PURCHASE_REQUEST_DTL_ID INT,
    @CAMP_ID INT,
    @REQUEST_STORE_ID INT,
    @REFERENCE_TYPE_ID INT,
    @REFERENCE_NO VARCHAR(50),
    @LINE_NO INT,
    @MAIN_CATEGORY_ID INT,
    @SUB_CATEGORY_ID INT,
    @PRODUCT_ID INT,
    @NO_OF_PCS_PER_PACKING DECIMAL(15,3),
    @TOTAL_QUANTITY DECIMAL(15,3),
    @UOM_ID INT,
    @TOTAL_PACKING DECIMAL(15,3),
    @ALT_UOM_ID INT,
    @RATE DECIMAL(15,3),
    @SUB_TOTAL_AMOUNT_FC DECIMAL(15,3),
    @DISCOUNT_PERCENTAGE DECIMAL(15,3),
    @DISCOUNT_AMOUNT_FC DECIMAL(15,3),
    @TOTAL_PRODUCT_AMOUNT_FC DECIMAL(15,3),
    @TAX_ID INT,
    @TAX_PERCENTAGE DECIMAL(15,3),
    @TAX_AMOUNT_FC DECIMAL(15,3),
    @FINAL_AMOUNT_FC DECIMAL(15,3),
    @EXCHANGE_RATE DECIMAL(15,6),
    @SUB_TOTAL_AMOUNT_LC DECIMAL(15,3),
    @DISCOUNT_AMOUNT_LC DECIMAL(15,3),

    @TOTAL_PRODUCT_AMOUNT_LC DECIMAL(15,3),
    @TAX_AMOUNT_LC DECIMAL(15,3),
    @FINAL_AMOUNT_LC DECIMAL(15,3),
    @REQUIRED_DATE DATETIME,
    @REASON VARCHAR(500),
    @REMARKS VARCHAR(500),
    @ITEM_TYPE VARCHAR(50) = NULL,
    @STATUS_ENTRY VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    IF NOT EXISTS (
        SELECT 1 FROM [VPurchase].[TBL_PURCHASE_QUOTATION_DTL]
        WHERE PURCHASE_QUOTATION_DTL_ID = @PURCHASE_QUOTATION_DTL_ID
    )
    BEGIN
        SELECT 'Error', 'Purchase Quotation Detail record not found.', ''
        RETURN
    END

    IF EXISTS (
        SELECT 1 FROM [VPurchase].[TBL_PURCHASE_QUOTATION_DTL]
        WHERE PURCHASE_QUOTATION_NO = @PURCHASE_QUOTATION_NO
          AND LINE_NO = @LINE_NO
          AND PURCHASE_QUOTATION_DTL_ID <> @PURCHASE_QUOTATION_DTL_ID
    )
    BEGIN
        SELECT 'Error', 'Line No ' + CAST(@LINE_NO AS VARCHAR(10)) + ' already exists for this Quotation.', ''
        RETURN
    END

    UPDATE [VPurchase].[TBL_PURCHASE_QUOTATION_DTL]
    SET
        PURCHASE_QUOTATION_NO = @PURCHASE_QUOTATION_NO,
        PURCHASE_REQUEST_NO = @PURCHASE_REQUEST_NO,
        PURCHASE_REQUEST_DTL_ID = @PURCHASE_REQUEST_DTL_ID,
        CAMP_ID = @CAMP_ID,
        REQUEST_STORE_ID = @REQUEST_STORE_ID,
        REFERENCE_TYPE_ID = @REFERENCE_TYPE_ID,
        REFERENCE_NO = @REFERENCE_NO,
        LINE_NO = @LINE_NO,
        MAIN_CATEGORY_ID = @MAIN_CATEGORY_ID,
        SUB_CATEGORY_ID = @SUB_CATEGORY_ID,
        PRODUCT_ID = @PRODUCT_ID,
        NO_OF_PCS_PER_PACKING = @NO_OF_PCS_PER_PACKING,
        TOTAL_QUANTITY = @TOTAL_QUANTITY,
        UOM_ID = @UOM_ID,
        TOTAL_PACKING = @TOTAL_PACKING,
        ALT_UOM_ID = @ALT_UOM_ID,
        RATE = @RATE,
        SUB_TOTAL_AMOUNT_FC = @SUB_TOTAL_AMOUNT_FC,
        DISCOUNT_PERCENTAGE = @DISCOUNT_PERCENTAGE,
        DISCOUNT_AMOUNT_FC = @DISCOUNT_AMOUNT_FC,
        TOTAL_PRODUCT_AMOUNT_FC = @TOTAL_PRODUCT_AMOUNT_FC,
        TAX_ID = @TAX_ID,
        TAX_PERCENTAGE = @TAX_PERCENTAGE,
        TAX_AMOUNT_FC = @TAX_AMOUNT_FC,
        FINAL_AMOUNT_FC = @FINAL_AMOUNT_FC,
        EXCHANGE_RATE = @EXCHANGE_RATE,
        SUB_TOTAL_AMOUNT_LC = @SUB_TOTAL_AMOUNT_LC,
        DISCOUNT_AMOUNT_LC = @DISCOUNT_AMOUNT_LC,

        TOTAL_PRODUCT_AMOUNT_LC = @TOTAL_PRODUCT_AMOUNT_LC,
        TAX_AMOUNT_LC = @TAX_AMOUNT_LC,
        FINAL_AMOUNT_LC = @FINAL_AMOUNT_LC,
        REQUIRED_DATE = @REQUIRED_DATE,
        REASON = @REASON,
        REMARKS = @REMARKS,
        ITEM_TYPE = @ITEM_TYPE,
        STATUS_ENTRY = @STATUS_ENTRY,
        MODIFIED_BY = @USER,
        MODIFIED_DATE = GETDATE(),
        MODIFIED_MAC_ADDRESS = @MAC_ADDRESS
    WHERE PURCHASE_QUOTATION_DTL_ID = @PURCHASE_QUOTATION_DTL_ID;

    SELECT '', 'Data Updated Successfully', @PURCHASE_QUOTATION_DTL_ID;
END
GO
-- Update purchase quotation hdr: additional-cost columns removed.
ALTER PROCEDURE [VPurchase].[UPDATE_PURCHASE_QUOTATION_HDR]
(
    @PURCHASE_REQUEST_NO VARCHAR(50) = NULL,
    @PURCHASE_QUOTATION_NO VARCHAR(50),
    @PURCHASE_QUOTATION_DATE DATETIME,
    @COMPANY_ID INT,
    @SUPPLIER_BP_ID INT,
    @BRANCH_ID INT,
    @PO_STORE_ID INT,
    @SUPPLIER_QUOTATION_NO VARCHAR(100),
    @SUPPLIER_QUOTATION_DATE DATETIME,
    @VALID_FROM_DATE DATETIME,
    @VALID_TO_DATE DATETIME,
    @PAYMENT_TERM_ID INT,
    @PAYMENT_MODE_ID INT,
    @SHIPMENT_MODE_ID INT,
    @DELIVERY_DATE DATETIME,
    @DELIVERY_TERM VARCHAR(100),
    @SHIPMENT_REMARKS VARCHAR(500),
    @DELIVERY_LOCATION_ID INT,
    @TOTAL_SUB_TOTAL_HDR_AMOUNT_FC DECIMAL(15,3),
    @TOTAL_DISCOUNT_HDR_AMOUNT_FC DECIMAL(15,3),

    @TOTAL_PRODUCT_HDR_AMOUNT_FC DECIMAL(15,3),
    @TOTAL_VAT_HDR_AMOUNT_FC DECIMAL(15,3),
    @FINAL_PRODUCT_HDR_AMOUNT_FC DECIMAL(15,3),
    @CURRENCY_ID INT,
    @EXCHANGE_RATE DECIMAL(15,6),
    @TOTAL_SUB_TOTAL_HDR_AMOUNT_LC DECIMAL(15,3),
    @TOTAL_DISCOUNT_HDR_AMOUNT_LC DECIMAL(15,3),

    @TOTAL_PRODUCT_HDR_AMOUNT_LC DECIMAL(15,3),
    @TOTAL_TAX_HDR_AMOUNT_LC DECIMAL(15,3),
    @FINAL_PRODUCT_HDR_AMOUNT_LC DECIMAL(15,3),
    @QUOTATION_STATUS_ID INT,
    @REMARKS VARCHAR(500),
    @STATUS_ENTRY VARCHAR(20),
    @USER VARCHAR(50),
    @MAC_ADDRESS VARCHAR(50)
)
AS
BEGIN
    SET NOCOUNT ON

    IF NOT EXISTS (
        SELECT 1 FROM [VPurchase].[TBL_PURCHASE_QUOTATION_HDR]
        WHERE PURCHASE_QUOTATION_NO = @PURCHASE_QUOTATION_NO
    )
    BEGIN
        SELECT 'Error', 'Purchase Quotation not found.', ''
        RETURN
    END

    -- Submitted quotations are frozen: no edit, no re-opening, for any role.
    IF EXISTS (
        SELECT 1 FROM [VPurchase].[TBL_PURCHASE_QUOTATION_HDR]
        WHERE PURCHASE_QUOTATION_NO = @PURCHASE_QUOTATION_NO
          AND UPPER(LTRIM(RTRIM(ISNULL(STATUS_ENTRY,'')))) = 'CL'
    )
    BEGIN
        SELECT 'Error', 'Records Already Submitted You Can''t Change Anything. Contact To Admin', ''
        RETURN
    END

    -- Approval columns (SECTION_HEAD_*, RESPONSE_1_*, RESPONSE_2_*,
    -- FINAL_RESPONSE_*) are intentionally absent from the SET list: re-saving a
    -- quotation from the entry screen must not be able to wipe or forge an
    -- approval trail. The approval dashboard owns those columns.

    UPDATE [VPurchase].[TBL_PURCHASE_QUOTATION_HDR]
    SET
        PURCHASE_REQUEST_NO = ISNULL(@PURCHASE_REQUEST_NO, PURCHASE_REQUEST_NO),
        PURCHASE_QUOTATION_DATE = @PURCHASE_QUOTATION_DATE,
        COMPANY_ID          = @COMPANY_ID,
        SUPPLIER_BP_ID      = @SUPPLIER_BP_ID,
        BRANCH_ID           = @BRANCH_ID,
        PO_STORE_ID         = @PO_STORE_ID,
        SUPPLIER_QUOTATION_NO   = @SUPPLIER_QUOTATION_NO,
        SUPPLIER_QUOTATION_DATE = @SUPPLIER_QUOTATION_DATE,
        VALID_FROM_DATE = @VALID_FROM_DATE,
        VALID_TO_DATE   = @VALID_TO_DATE,
        PAYMENT_TERM_ID = @PAYMENT_TERM_ID,
        PAYMENT_MODE_ID = @PAYMENT_MODE_ID,
        SHIPMENT_MODE_ID = @SHIPMENT_MODE_ID,
        DELIVERY_DATE       = @DELIVERY_DATE,
        DELIVERY_TERM       = @DELIVERY_TERM,
        SHIPMENT_REMARKS    = @SHIPMENT_REMARKS,
        DELIVERY_LOCATION_ID = @DELIVERY_LOCATION_ID,
        TOTAL_SUB_TOTAL_HDR_AMOUNT_FC   = @TOTAL_SUB_TOTAL_HDR_AMOUNT_FC,
        TOTAL_DISCOUNT_HDR_AMOUNT_FC    = @TOTAL_DISCOUNT_HDR_AMOUNT_FC,

        TOTAL_PRODUCT_HDR_AMOUNT_FC     = @TOTAL_PRODUCT_HDR_AMOUNT_FC,
        TOTAL_VAT_HDR_AMOUNT_FC         = @TOTAL_VAT_HDR_AMOUNT_FC,
        FINAL_PRODUCT_HDR_AMOUNT_FC     = @FINAL_PRODUCT_HDR_AMOUNT_FC,
        CURRENCY_ID    = @CURRENCY_ID,
        EXCHANGE_RATE  = @EXCHANGE_RATE,
        TOTAL_SUB_TOTAL_HDR_AMOUNT_LC   = @TOTAL_SUB_TOTAL_HDR_AMOUNT_LC,
        TOTAL_DISCOUNT_HDR_AMOUNT_LC    = @TOTAL_DISCOUNT_HDR_AMOUNT_LC,

        TOTAL_PRODUCT_HDR_AMOUNT_LC     = @TOTAL_PRODUCT_HDR_AMOUNT_LC,
        TOTAL_TAX_HDR_AMOUNT_LC         = @TOTAL_TAX_HDR_AMOUNT_LC,
        FINAL_PRODUCT_HDR_AMOUNT_LC     = @FINAL_PRODUCT_HDR_AMOUNT_LC,
        QUOTATION_STATUS_ID = @QUOTATION_STATUS_ID,
        REMARKS      = @REMARKS,
        STATUS_ENTRY = ISNULL(@STATUS_ENTRY, STATUS_ENTRY),

        MODIFIED_BY          = @USER,
        MODIFIED_DATE        = GETDATE(),
        MODIFIED_MAC_ADDRESS = @MAC_ADDRESS
    WHERE PURCHASE_QUOTATION_NO = @PURCHASE_QUOTATION_NO;

    SELECT '', 'Data Updated Successfully', @PURCHASE_QUOTATION_NO
END
GO
