--CREATE DATABASE TBGS
--GO
--CREATE SCHEMA VMASTER
--GO
--CREATE SCHEMA VENTRIES



CREATE TABLE VMASTER.[TBL_USER_INFO_HDR] (
LOGIN_ID INT IDENTITY(1,1) CONSTRAINT PK_LOGIN_ID PRIMARY KEY,
[EMP_ID] INT, -- FK 
LOGIN_NAME VARCHAR(50) CONSTRAINT UK_LOGIN_NAME UNIQUE,
[PASSWORD] VARCHAR(100),
[ROLE] VARCHAR(100),-- JUST TEXT
[MOBILE_NO] VARCHAR(30),
[MAIL_ID] VARCHAR(150),
[STOCK_SHOW_STATUS] VARCHAR(10),-- YES/NO
[OUTSIDE_ACCESS_Y_N] VARCHAR(20),-- YES/NO
[STATUS_MASTER] VARCHAR(20),-- AC/IA (ACTIVE/ IN ACTIVE)
[REMARKS] VARCHAR(1000),-- TEXT
[CREATED_USER] VARCHAR(50),-- BACK END
[CREATED_DATE] DATETIME,-- BACK END
[CREATED_MAC_ADDR] VARCHAR(50),-- BACK END
[MODIFIED_USER] VARCHAR(50),-- BACK END
[MODIFIED_DATE] DATETIME,-- BACK END
[MODIFIED_MAC_ADDR] VARCHAR(50),-- BACK END
)
GO

CREATE TABLE [VMASTER].[TBL_CURRENCY_MASTER](
	[CURRENCY_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_CURRE_CUID_CURRENCY PRIMARY KEY,
	[CURRENCY_NAME] [VARCHAR](50) CONSTRAINT UK_CURR_NZAME UNIQUE,-- TEXT
	[ADDRESS] [VARCHAR](50) NULL,-- TEXT
	[EXCHANGE_RATE] [DECIMAL](15, 5) NULL, -- CURRENCY EXCHANGE RATE PICK FROM MASTER LAST ENTRY -- AUTO UPDATE
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
  
CREATE TABLE [VMASTER].[TBL_COMPANY_MASTER]	(
	[COMPANY_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_COMP_ID_MAS_COMP PRIMARY KEY,
	[COMPANY_NAME] [VARCHAR](100) CONSTRAINT UK_COMP_NAME_MAS UNIQUE,-- TEXT
	[COMPANY_FULL_NAME] [VARCHAR](150) NULL,-- TEXT
	[TIN_NUMBER] [VARCHAR](50) CONSTRAINT UK_TIN_NAME_MAS UNIQUE,-- TEXT
	VRN_NUMBER VARCHAR(50),	-- TEXT
	[ADDRESS] [VARCHAR](2000) NULL,-- TEXT
	[CONTACT_PERSON] [VARCHAR](50) NULL,-- TEXT
	[CONTACT_NUMBER] [VARCHAR](50) NULL,-- TEXT
	[EMAIL] [VARCHAR](50) NULL,-- TEXT
	[SHORT_CODE] [VARCHAR](4) NULL,-- TEXT
	[FINANCE_START_MONTH] [VARCHAR](50) NULL,-- TEXT
	[FINANCE_END_MONTH] [VARCHAR](50) NULL,-- TEXT
	[YEAR_CODE] [VARCHAR](50) NULL,-- TEXT
	[DEFAULT_CURRENCY_ID] INT CONSTRAINT FK_CUR_ID_COMP_MAS FOREIGN KEY REFERENCES VMASTER.TBL_CURRENCY_MASTER(CURRENCY_ID),-- DROP DOWN
	[TIMEZONE] [VARCHAR](50) NULL,-- TEXT
	[NO_OF_USER] [INT] NULL,-- TEXT
	[WEBSITE] [VARCHAR](50) NULL,-- TEXT
	[COMP_BIG_LOGO] [VARBINARY](MAX) NULL, -- IMAGE
	[COMP_SMALL_LOGO] [VARBINARY](MAX) NULL,-- IMAGE
	[COMP_LETTER_HEAD] [VARBINARY](MAX) NULL,-- IMAGE
	[COMP_STAMP_LOGO] [VARBINARY](MAX) NULL,-- IMAGE
	[REMARKS] [VARCHAR](2000) NULL,-- TEXT
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
	)
	GO

	
CREATE TABLE [VMASTER].[TBL_DEPARTMENT_MASTER](
	[DEPARTMENT_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_DEPT_ID  PRIMARY KEY,
	[DEPARTMENT_NAME] [VARCHAR](50) CONSTRAINT UK_DEPT_NZAME UNIQUE,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,-- TEXT
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
  
  
CREATE TABLE [VMASTER].[TBL_DESIGNATION_MASTER](
	[DESIGNATION_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_CURRE_DESIGNATION PRIMARY KEY,
	[DESIGNATION_NAME] [VARCHAR](50) CONSTRAINT UK_DESIGNATION_NZAME UNIQUE,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,-- TEXT
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)

 GO
  
  
CREATE TABLE [VMASTER].[TBL_COUNTRY_MASTER]( -- WE HAVE TO UPLOAD DATA FROM WEBSITE
	[COUNTRY_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_COUNTR_ID_MAS PRIMARY KEY ,
	[COUNTRY_NAME] [VARCHAR](100) CONSTRAINT UK_COUNTRY_NAME_MAS UNIQUE,-- TEXT
	[NICENAME] [VARCHAR](80) NULL,-- TEXT
	[ISO3] [VARCHAR](50) NULL,-- TEXT
	[NUMCODE] [INT] NULL,-- TEXT
	[PHONECODE] [INT] NULL,-- TEXT
	[BATCH_NO] [VARCHAR](2) NULL,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](50) NULL,
	[CREATED_USER] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_USER] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
GO

CREATE TABLE [VMASTER].[TBL_REGION_MASTER](
[REGION_ID] INT IDENTITY(1,1) CONSTRAINT PK_REGION_ID_MAS PRIMARY KEY,
REGION_NAME VARCHAR(50) CONSTRAINT UK_UNIQUE_REG UNIQUE,-- TEXT
[COUNTRY_ID] INT CONSTRAINT FK_COUTRY_ID_REG FOREIGN KEY REFERENCES [VMASTER].[TBL_COUNTRY_MASTER]([COUNTRY_ID]),-- DROPDOWN
[CAPITAL] VARCHAR(50),-- TEXT
[NO_OF_DISTRICTS] INT,-- TEXT
[TOTAL_POPULATION] DECIMAL(18,2),-- TEXT
[ZONE_NAME] VARCHAR(50),-- TEXT
[DISTANCE_FROM_ARUSHA] DECIMAL(18,2),-- TEXT
[STATUS_MASTER] VARCHAR(20),
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_MAC_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_MAC_ADDRESS] VARCHAR(50)
)
GO

CREATE TABLE [VMASTER].[TBL_DISTRICT_MASTER](
	[DISTRICT_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_DIST_ID_DIS PRIMARY KEY,
	[COUNTRY_ID] [INT] CONSTRAINT FK_COUNTRY_ID_DIST_MAS FOREIGN KEY REFERENCES VMASTER.TBL_COUNTRY_MASTER(COUNTRY_ID),-- DROP DOWN
	[REGION_ID] [INT]  CONSTRAINT FK_REG_ID_REGION_MAS FOREIGN KEY REFERENCES VMASTER.TBL_REGION_MASTER(REGION_ID),-- DROP DOWN
	[DISTRICT_NAME] [VARCHAR](50) NULL,-- TEXT
	[TOTAL_POPULATION] [DECIMAL](18, 2) NULL,-- TEXT
	[ZONE_NAME] [VARCHAR](50) NULL,-- TEXT
	[DISTANCE_FROM_ARUSHA] [DECIMAL](18, 2) NULL,-- TEXT
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) 
	)
	GO

CREATE TABLE [VMASTER].[TBL_CAMP_MASTER] (
	[CAMP_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_CURRE_CAMP PRIMARY KEY,
	[CAMP_NAME] [VARCHAR](50) CONSTRAINT UK_CAMP_NZAME UNIQUE,-- -- TEXT
	[COUNTRY_ID] [INT] CONSTRAINT FK_COUNTRY_ID_CAMP_MAS FOREIGN KEY REFERENCES VMASTER.TBL_COUNTRY_MASTER(COUNTRY_ID),-- DROP DOWN
	[REGION_ID] [INT]  CONSTRAINT FK_REG_ID_CAMP_MAS FOREIGN KEY REFERENCES VMASTER.TBL_REGION_MASTER(REGION_ID),-- DROP DOWN
	DISTRICT_ID INT CONSTRAINT FK_DIST_ID_CAMP_MAS FOREIGN KEY REFERENCES VMASTER.TBL_DISTRICT_MASTER(DISTRICT_ID),-- DROP DOWN
	[REMARKS] [VARCHAR](1000) NULL,-- TEXT
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)

 GO
  
  --SELECT * FROM STORE.VMASTER.TBL_STORE_MASTER
CREATE TABLE [VMASTER].[TBL_STORE_MASTER] (
	[STORE_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_STORE_ID_MAS PRIMARY KEY,
	[STORE_NAME] [VARCHAR](100) CONSTRAINT UK_STORE_NAME UNIQUE,-- TEXT
	STORE_SHORT_NAME VARCHAR(50),-- TEXT
	[CAMP_ID] [INT] CONSTRAINT FK_LOC_STORE_CAMP_MAS FOREIGN KEY REFERENCES VMASTER.TBL_CAMP_MASTER(CAMP_ID),-- DROP DOWN
	[MANAGER_NAME] [VARCHAR](50) NULL,-- TEXT
	[STORE_SHORT_CODE] [VARCHAR](5) NULL,-- TEXT
	[EMAIL_ADDRESS] [VARCHAR](1000) NULL,-- TEXT
	[CC_EMAIL_ADDRESS] [VARCHAR](MAX) NULL,-- TEXT
	[BCC_EMAIL_ADDRESS] [VARCHAR](50) NULL,-- TEXT
	[RESPONSE_DIRECTORS_NAME] [VARCHAR](1000) NULL,-- TEXT
	[REMARKS] [VARCHAR](2000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
GO


CREATE TABLE [VMASTER].[TBL_CAMP_MASTER](
	[CAMP_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_CURRE_CAMP PRIMARY KEY,
	[CAMP_NAME] [VARCHAR](50) CONSTRAINT UK_CAMP_NZAME UNIQUE,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,-- TEXT
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)

GO

CREATE TABLE [VMASTER].[TBL_ROLE_MASTER](
	[ROLE_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_ROLE_MAST PRIMARY KEY,
	[ROLE_NAME] [VARCHAR](50) CONSTRAINT UK_ROLE_NZAME UNIQUE,
	[ROLE_DESCRIPTION] [VARCHAR](50) NULL,
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO

 
CREATE TABLE [VMASTER].[TBL_USER_TO_STORE_MAPPING](
[USER_TO_STORE_ID] INT IDENTITY(1,1) CONSTRAINT PK_USER_TO_STORE_ID PRIMARY KEY,
[LOGIN_ID] INT CONSTRAINT FK_USER_ID_STORE_MAP FOREIGN KEY REFERENCES VMASTER.[TBL_USER_INFO_HDR]([LOGIN_ID]),
COMPANY_ID INT CONSTRAINT FK_COMP_ID_USERSTORE FOREIGN KEY REFERENCES VMASTER.TBL_COMPANY_MASTER(COMPANY_ID),
CAMP_ID INT CONSTRAINT FK_CAMP_ID_USERSTORE FOREIGN KEY REFERENCES VMASTER.TBL_CAMP_MASTER(CAMP_ID),
[STORE_ID] INT CONSTRAINT FK_STORE_ID_USERSTOREMAP1 FOREIGN KEY REFERENCES VMASTER.TBL_STORE_MASTER(STORE_ID),
[ROLE_ID] INT CONSTRAINT FK_ROLE_ID_USERSTOREMAP2 FOREIGN KEY REFERENCES VMASTER.TBL_ROLE_MASTER(ROLE_ID),
[REMARKS] [VARCHAR](1000) NULL,
[STATUS_MASTER] VARCHAR(20),
[CREATED_USER] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_MAC_ADDR] VARCHAR(50),
[MODIFIED_USER] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_MAC_ADDR] VARCHAR(50)
);

GO


CREATE TABLE [VMASTER].[TBL_COST_CENTRE_MASTER](
[COST_CENTRE_ID] INT IDENTITY(1,1) CONSTRAINT PK_SNO_COST_CENTER_ID PRIMARY KEY,
[COST_CENTRE_NAME] VARCHAR(50) CONSTRAINT UK_COST_CENTER_NAME_MAS UNIQUE,
COMPANY_ID INT CONSTRAINT FK_COMP_ID_COST_CENT FOREIGN KEY REFERENCES VMASTER.TBL_COMPANY_MASTER(COMPANY_ID),
[REMARKS] VARCHAR(2000),
[STATUS_MASTER] VARCHAR(20),
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_MAC_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_MAC_ADDRESS] VARCHAR(50),
);
GO


CREATE TABLE [VMASTER].[TBL_PRODUCT_MAIN_CATEGORY_MASTER](
[MAIN_CATEGORY_ID] INT IDENTITY(1,1) CONSTRAINT PK_MAIN_CAT_ID PRIMARY KEY,
MAIN_CATEGORY_NAME VARCHAR(100) CONSTRAINT UK_MAIN_CATE_NAME UNIQUE,
[REMARKS] VARCHAR(2000),
[STATUS_MASTER] VARCHAR(20),
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_MAC_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_MAC_ADDRESS] VARCHAR(50),
);
GO

 
CREATE TABLE [VMASTER].[TBL_PRODUCT_SUB_CATEGORY_MASTER](
[SUB_CATEGORY_ID] INT IDENTITY(1,1) CONSTRAINT PK_SNO_SUB_ID PRIMARY KEY,
SUB_CATEGORY_NAME VARCHAR(50) CONSTRAINT UK_SUUB_CATE_NAME_MAS UNIQUE,
[MAIN_CATEGORY_ID] INT CONSTRAINT FK_SUB_CAT_MAIN FOREIGN KEY REFERENCES [VMASTER].[TBL_PRODUCT_MAIN_CATEGORY_MASTER]([MAIN_CATEGORY_ID]),
[REMARKS] VARCHAR(2000),
[STATUS_MASTER] VARCHAR(20),
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_MAC_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_MAC_ADDRESS] VARCHAR(50),
);
GO

CREATE TABLE [VMASTER].[TBL_UOM_MASTER](
[UOM_ID] INT IDENTITY(1,1) CONSTRAINT PK_SNO_UOM_ID PRIMARY KEY,
UOM_NAME VARCHAR(50) CONSTRAINT UK_UOM_NAME_MAS UNIQUE,
KG_PER_UOM DECIMAL(15,2),
[REMARKS] VARCHAR(2000),
[STATUS_MASTER] VARCHAR(20),
[CREATED_BY] VARCHAR(50),
[CREATED_DATE] DATETIME,
[CREATED_MAC_ADDRESS] VARCHAR(50),
[MODIFIED_BY] VARCHAR(50),
[MODIFIED_DATE] DATETIME,
[MODIFIED_MAC_ADDRESS] VARCHAR(50),
);
GO

CREATE TABLE [VMASTER].[TBL_PRODUCT_MASTER]
 (
	[PRODUCT_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_PRODUCT_ID_MAS PRIMARY KEY,
	[PRODUCT_NAME] [VARCHAR](1500) CONSTRAINT UK_PRODUCT_NAME_MAS UNIQUE,
	[TBS_PRODUCT_NAME] [VARCHAR](MAX) NULL,
	[MAIN_CATEGORY_ID] [INT] CONSTRAINT FK_MAIN_CATE_ID_PROD FOREIGN KEY REFERENCES [VMASTER].[TBL_PRODUCT_MAIN_CATEGORY_MASTER](MAIN_CATEGORY_ID),
	[SUB_CATEGORY_ID] [INT] CONSTRAINT FK_SUB_CATE_ID_PROD FOREIGN KEY REFERENCES [VMASTER].[TBL_PRODUCT_SUB_CATEGORY_MASTER](SUB_CATEGORY_ID),
	UOM_ID INT CONSTRAINT FK_UOM_ID_PROD_MAS FOREIGN KEY REFERENCES [VMASTER].[TBL_UOM_MASTER](UOM_ID),
	[NO_OF_PCS_PER_PACKING] [DECIMAL](15, 2) NULL,
	ALTERNATE_UOM_ID INT CONSTRAINT FK_ALT_UOM_ID_PROD_MAS FOREIGN KEY REFERENCES [VMASTER].[TBL_UOM_MASTER](UOM_ID),
	COST_CENTRE_ID INT CONSTRAINT FK_COST_CENT_ID_PROD FOREIGN KEY REFERENCES [VMASTER].[TBL_COST_CENTRE_MASTER](COST_CENTRE_ID),
	COMPANY_ID INT CONSTRAINT FK_COMP_ID_COST_CENT_PROD_MAS FOREIGN KEY REFERENCES VMASTER.TBL_COMPANY_MASTER(COMPANY_ID),
	[PRODUCTION_COST] [DECIMAL](15, 2) NULL,
	[VAT_PERCENTAGE] [DECIMAL](15, 2) NULL,
	
	RESPONSE_1_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_1_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	RESPONSE_2_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_2_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	FINAL_RESPONSE_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_DATE DATETIME,-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	[REMARKS] [VARCHAR](2000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
 )
GO


 
  

CREATE TABLE [VMASTER].[TBL_PRICE_TYPE_MASTER]( --  ( HUNT WITH GUN, HUNT WITHOUT GUN, HUNT+GUN+ARMER,OBSERVER)
	[PRICE_TYPE_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_PRICE_TYPE_MAS PRIMARY KEY,
	[PRICE_TYPE_NAME] [VARCHAR](50) CONSTRAINT UK_PRICE_TYPE UNIQUE,-- TEXT
	[PRICE_TYPE_DESCRIPTION] [VARCHAR](50) ,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
  
CREATE TABLE [VMASTER].[TBL_SALES_PACKAGE_TYPE_MASTER] ( --  
	[SALES_PACKAGE_TYPE_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_SALES_PACKAGE_TYPE_MAS PRIMARY KEY,
	[SALES_PACKAGE_TYPE_NAME] [VARCHAR](50) CONSTRAINT UK_PACKAGE_TYPE_NZAME UNIQUE,-- TEXT -- PREMIUM/MAJOR/REGULAR
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
 
CREATE TABLE [VMASTER].[TBL_PRICE_PACKAGE_MASTER] ( --  
	[PRICE_PACKAGE_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_PRICE_PACKAGE_MAS PRIMARY KEY,
	PRICE_PACKAGE_TYPE  VARCHAR(50),-- GENERAL/ADDITIONAL
	[SALES_PACKAGE_TYPE_ID] INT CONSTRAINT FK_SALES_PACKAGE_TYPE_PRICE FOREIGN KEY REFERENCES [VMASTER].[TBL_SALES_PACKAGE_TYPE_MASTER]([SALES_PACKAGE_TYPE_ID]), -- PREMIUM/MAJOR/REGULAR
	[PRICE_PACKAGE_NAME] [VARCHAR](50) CONSTRAINT UK_PACKAGE_NZAME UNIQUE,-- TEXT -- 7 DAYS/ 10 DAYS / 15 DAYS / 21 DAYS/ EXTENSION_PER_DAY /CHARTED FLIGHT / ADDITIONAL FOOD/ ADDITIONAL DRINKS/ ADDITIONAL DAYS 
	[PRICE_PACKAGE_DAYS] INT,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
 
CREATE TABLE [VMASTER].[TBL_PRICE_LIST_MASTER] ( --  ( HUNT WITH GUN, HUNT WITHOUT GUN, HUNT+GUN+ARMER,OBSERVER)
	[PRICE_LIST_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_PRICE_LIST_MAS PRIMARY KEY,
	COMPANY_ID INT CONSTRAINT FK_COMP_ID_PRICE_LIST FOREIGN KEY REFERENCES VMASTER.TBL_COMPANY_MASTER(COMPANY_ID),
	[PRICE_TYPE_ID] INT CONSTRAINT FK_PRICE_TYPE_PRICE_LIST FOREIGN KEY REFERENCES [VMASTER].[TBL_PRICE_TYPE_MASTER]([PRICE_TYPE_ID]),----( HUNT WITH GUN, HUNT WITHOUT GUN, HUNT+GUN+ARMER,OBSERVER)
	[PRICE_PACKAGE_ID] INT CONSTRAINT FK_PRICE_LIST_ID_PRICE FOREIGN KEY REFERENCES [VMASTER].[TBL_PRICE_PACKAGE_MASTER]([PRICE_PACKAGE_ID]) ,--  7 DAYS/ 10 DAYS / 15 DAYS / 21 DAYS/ CHARTED FLIGHT / ADDITIONAL FOOD/ ADDITIONAL DRINKS/ ADDITIONAL DAYS 
	PER_DAY_OR_TRIP_OR_QTY_PRICE DECIMAL(15,2),---- TEXT
	FOOD_LIMIT_AMOUNT DECIMAL(15,2),---- TEXT
	DRINKS_LIMIT_AMOUNT DECIMAL(15,2),---- TEXT
	ACCOMDATION_LIMIT_AMOUNT DECIMAL(15,2),---- TEXT
	CURRENCY_ID INT CONSTRAINT FK_CURR_ID_PRICE_LI FOREIGN KEY REFERENCES VMASTER.TBL_CURRENCY_MASTER(CURRENCY_ID),
	EFFECTIVE_FROM DATETIME,
	EFFECTIVE_TO DATETIME,
	REQUESTED_BY VARCHAR(50),-- AUTO REQUESTED LOGIN NAME
	REQUESTED_DATE DATETIME,-- REQUESTED GETDATE

	SECTION_HEAD_RESPONSE_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_DATE DATETIME,-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	RESPONSE_1_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_1_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	RESPONSE_2_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_2_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	FINAL_RESPONSE_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_DATE DATETIME,-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
  
  --SELECT * FROM STORE.VMASTER.TBL_BILLING_LOCATION_WISE_PRODUCT_PRICE_SETTINGS

CREATE TABLE [VMASTER].[TBL_EXCHANGE_RATE_MASTER] ( --- DAILY EXCHANGE RATE INSERT -- CHOOSE COMPANY & FROM CURRENCY & TO CURRENCY AND SHOW ALL THE DATAS TO FILL EXCHANGE DATE
	SNO [INT] IDENTITY(1,1) CONSTRAINT PK_EXP_ID_EX PRIMARY KEY,
	COMPANY_ID INT CONSTRAINT FK_COMP_ID_EXCE FOREIGN KEY REFERENCES VMASTER.TBL_COMPANY_MASTER(COMPANY_ID),
	MONTH_ENTERED VARCHAR(50),-- DROP DOWN TO SHOW ALL THE MONTHS
	YEAR_ENTERED VARCHAR(20),-- DROP DOWN TO SHOW ALL THE YEARS ( BEFORE CURRENT YEARS)
	DATE_OF_EXCHANGE DATETIME,
	[FROM_CURRENCY_ID] INT CONSTRAINT FK_FROM_CURRE_ID_EXC FOREIGN KEY REFERENCES VMASTER.TBL_CURRENCY_MASTER(CURRENCY_ID) ,-- USD
	[TO_CURRENCY_ID] INT CONSTRAINT FK_TO_CURRE_ID_EXC FOREIGN KEY REFERENCES VMASTER.TBL_CURRENCY_MASTER(CURRENCY_ID) ,--- TZS
	[EXCHANGE_RATE] [DECIMAL](15, 5) NULL, -- TEXT
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO

 
CREATE TABLE [VMASTER].[TBL_LICENSE_PERMIT_TYPE_MASTER] ( --  
	[LICENSE_PERMIT_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_LICENSE_PERMIT_MAS PRIMARY KEY,
	[LICENSE_PERMIT_NAME] [VARCHAR](50) CONSTRAINT UK_PERMIT_TYPE UNIQUE,-- TEXT -- 
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO

 

 
CREATE TABLE [VMASTER].[TBL_LICENSE_PERMIT_COST_MASTER] ( --  
	[SNO] [INT] IDENTITY(1,1) CONSTRAINT PK_LICENSE_PERMIT_COST_MAS PRIMARY KEY,
	[LICENSE_PERMIT_ID] INT CONSTRAINT FK_LICENSE_PERMIT_ID_LCCOST FOREIGN KEY REFERENCES [VMASTER].[TBL_LICENSE_PERMIT_TYPE_MASTER]([LICENSE_PERMIT_ID]) ,-- DROP DOWN -- LICENSE TYPES LIKE GAME HUNTING PERMIT/ 
	[SALES_PACKAGE_TYPE_ID] INT CONSTRAINT FK_LICENSE_PACKAGE_TYPE_LCCOST FOREIGN KEY REFERENCES [VMASTER].[TBL_SALES_PACKAGE_TYPE_MASTER]([SALES_PACKAGE_TYPE_ID]) ,-- DROP DOWN -- PREMIUM/GENERAL
	[PRICE_TYPE_ID] INT CONSTRAINT FK_PRICE_TYPE_ID_LC_COST FOREIGN KEY REFERENCES [VMASTER].[TBL_PRICE_TYPE_MASTER] ([PRICE_TYPE_ID]), -- DROP DOWN (HUNT WITH GUN, HUNT WITHOUT GUN, HUNT+GUN+ARMER,OBSERVER)
	[PRICE_PACKAGE_ID] INT CONSTRAINT FK_PRICE_PACKAGE_ID_LC_COST FOREIGN KEY REFERENCES  [VMASTER].[TBL_PRICE_PACKAGE_MASTER] ([PRICE_PACKAGE_ID]), -- DROP DOWN 7 DAYS/ 10 DAYS / 15 DAYS / 21 DAYS
	GOVT_RATE DECIMAL(15,2),-- TEXT GOVT RATE
	ACTUAL_AMOUNT DECIMAL(15,2), -- OUR COMPANY RATE
	CURRENCY_ID INT CONSTRAINT FK_CURRR_ID_LICENS_COST FOREIGN KEY REFERENCES VMASTER.TBL_CURRENCY_MASTER(CURRENCY_ID),
	EFFECTIVE_FROM DATETIME,
	EFFECTIVE_TO DATETIME,
	SECTION_HEAD_RESPONSE_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_DATE DATETIME,-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	RESPONSE_1_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_1_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	RESPONSE_2_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_2_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	FINAL_RESPONSE_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_DATE DATETIME,-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO

 
CREATE TABLE [VMASTER].[TBL_ANIMAL_MASTER](
	[ANIMAL_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_ANIMAL_CUID_CURRENCY PRIMARY KEY,
	[ANIMAL_NAME] [VARCHAR](50) CONSTRAINT UK_ANIMAL_NZAME UNIQUE,-- TEXT
	--[ADDRESS] [VARCHAR](50) NULL,-- TEXT
	--[EXCHANGE_RATE] [DECIMAL](15, 5) NULL, -- CURRENCY EXCHANGE RATE PICK FROM MASTER LAST ENTRY -- AUTO UPDATE
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
 

 CREATE TABLE [VMASTER].[TBL_COMPANY_QUOTA_ANIMAL_MAPPING_HDR] ( --  
	QUOTA_ID INT IDENTITY(1,1) CONSTRAINT PK_QUOTA_MAP_ID_MAS PRIMARY KEY,
	COMPANY_ID INT CONSTRAINT FK_COMP_ID_COMP_QUOTA FOREIGN KEY REFERENCES [VMASTER].TBL_COMPANY_MASTER(COMPANY_ID),
	CAMP_ID INT CONSTRAINT FK_CAMP_ID_COMP_QUOTA FOREIGN KEY REFERENCES [VMASTER].TBL_CAMP_MASTER(CAMP_ID),
	EFFECTIVE_YEAR VARCHAR(10),-- YEAR DROP DOWN
	NEW_REVISION VARCHAR(50),--DROP DOWN NEW/REVISION
	OLD_QUOTA_ID INT,-- SAME TABLE IF TYPE IS REVISION NEED TO LOAD
	ISSUING_AUTHORITY VARCHAR(50),-- TEXT 
	APPROVAL_REFERENCE_NO VARCHAR(50),
	APPROVAL_DATE DATETIME,
	LAST_AMENDMENT_DATE DATETIME,-- TEXT
	EFFECTIVE_FROM DATETIME,
	EFFECTIVE_TO DATETIME,
	QUOTA_AMOUNT DECIMAL(15,2),--TEXT
	VAT_AMOUNT DECIMAL(15,2),-- TEXT
	FINAL_QUOTA_AMOUNT DECIMAL(15,2),-- TEXT
	CURRENCY_ID INT CONSTRAINT FK_CURR_ID_QUOTA_DETL FOREIGN KEY REFERENCES VMASTER.TBL_CURRENCY_MASTER(CURRENCY_ID),
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
 
 
CREATE TABLE [VMASTER].[TBL_COMPANY_QUOTA_ANIMAL_MAPPING_DTL] ( --  
	SNO INT IDENTITY(1,1) CONSTRAINT PK_QUOTA_DTL_TYPE_MAS PRIMARY KEY,
	QUOTA_ID INT CONSTRAINT FK_QUOTA_ID_COMP_QUOTA FOREIGN KEY REFERENCES [VMASTER].[TBL_COMPANY_QUOTA_ANIMAL_MAPPING_HDR](QUOTA_ID),
	ANIMAL_ID INT CONSTRAINT FK_ANIMAL_ID_COMP_QUOT FOREIGN KEY REFERENCES VMASTER.TBL_ANIMAL_MASTER(ANIMAL_ID),
	OLD_APPROVED_QTY INT,-- IF REVISION. TAKE DATA FROM OLD QUOTA ID
	ADD_REMOVE_QTY INT,-- TEXT + OR - QTY DATA TABLE/GRID EDIT 
	NEW_APPROVED_QTY INT,-- ---- ADD OLD_APPROVED_QTY + NEW_APPROVED_QTY
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
 
 
 CREATE TABLE [VMASTER].[TBL_ANIMAL_HUNTING_CHARGES_MASTER_HDR] -- GRID EDIT HDR AND DTL
 ( --  
	ANIMAL_HUNT_CHARGE_ID INT IDENTITY(1,1) CONSTRAINT PK_ANIM_HUNTI_PRICE_ID_MAS PRIMARY KEY,
	COMPANY_ID INT CONSTRAINT FK_COMP_ID_ANIMAL_HUNT_CHAR FOREIGN KEY REFERENCES [VMASTER].TBL_COMPANY_MASTER(COMPANY_ID),
	EFFECTIVE_YEAR VARCHAR(10),-- YEAR DROP DOWN
	ISSUING_AUTHORITY VARCHAR(50),-- TEXT 
	APPROVAL_REFERENCE_NO VARCHAR(50),
	APPROVAL_DATE DATETIME,
	EFFECTIVE_FROM DATETIME,
	EFFECTIVE_TO DATETIME,
	CURRENCY_ID INT CONSTRAINT FK_CURR_ID_ANIMAL_HUNT_CHAR FOREIGN KEY REFERENCES VMASTER.TBL_CURRENCY_MASTER(CURRENCY_ID),

	SECTION_HEAD_RESPONSE_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_DATE DATETIME,-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	RESPONSE_1_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_1_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	RESPONSE_2_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_2_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	FINAL_RESPONSE_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_DATE DATETIME,-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
 
CREATE TABLE [VMASTER].[TBL_ANIMAL_HUNTING_CHARGES_MASTER_DTL] ( --  
	SNO INT IDENTITY(1,1) CONSTRAINT PK_ANIM_HUNT_DTL_MAS PRIMARY KEY,
	ANIMAL_HUNT_CHARGE_ID INT CONSTRAINT FK_QUOTA_ID_COMP_QUOTA_MAS_DTL FOREIGN KEY REFERENCES [VMASTER].[TBL_ANIMAL_HUNTING_CHARGES_MASTER_HDR](ANIMAL_HUNT_CHARGE_ID),
	ANIMAL_ID INT CONSTRAINT FK_ANIMAL_ID_COMP_QUOT_MAS_DTL FOREIGN KEY REFERENCES VMASTER.TBL_ANIMAL_MASTER(ANIMAL_ID),
	GOVT_RATE DECIMAL(15,2),-- TEXT GOVT RATE
	ACTUAL_AMOUNT DECIMAL(15,2), -- OUR COMPANY RATE
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
  
CREATE TABLE [VMASTER].[TBL_MAIN_MENU](
	[MAIN_MENU_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_MAIN_MENU_ID PRIMARY KEY,
	[MAIN_MENU_NAME] [VARCHAR](100) NULL,
	[MAIN_MENU_LOCATION] [VARCHAR](100) NULL,
	[MAIN_MENU_SEQ_ID] [INT] NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[STYLE_CSS] [VARCHAR](1000) NULL,
	[PAGE_ACTION] [VARCHAR](100) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
)
GO

CREATE TABLE [VMASTER].[TBL_SUB_MENU](
	[SUB_MENU_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_SUB_MENU_ID PRIMARY KEY,
	[MAIN_MENU_ID] [INT] CONSTRAINT FK_MAIN_MENU_ID_SUB FOREIGN KEY REFERENCES [VMASTER].[TBL_MAIN_MENU]([MAIN_MENU_ID]),
	[SUB_MENU_NAME] [VARCHAR](100) NULL,
	[SUB_MENU_LOCATION] [VARCHAR](100) NULL,
	[SUB_MENU_SEQ_ID] [INT] NULL,
	[STYLE_CSS] [VARCHAR](1000) NULL,
	[PAGE_ACTION] [VARCHAR](100) NULL,
	[IS_PARENT] [VARCHAR](25) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
)
GO

CREATE TABLE [VMASTER].[TBL_SUB_MENU_MAPPING](
	[MAP_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_MAP_ID_SUB_MEU_MAP PRIMARY KEY,
	[SUB_MENU_PARENT_ID] [INT] CONSTRAINT FK_SUB_MENU_MAP FOREIGN KEY REFERENCES [VMASTER].[TBL_SUB_MENU](SUB_MENU_ID),
	[CHILD_ID] [INT] CONSTRAINT FK_SUB_MENU_MAP_CHILD FOREIGN KEY REFERENCES [VMASTER].[TBL_SUB_MENU](SUB_MENU_ID),
	[MAP_LOCATION] [VARCHAR](100) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
)
GO
 
CREATE TABLE [VMASTER].[TBL_LINKS_AND_PAGES](
	[LINK_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_LINK_PAGE PRIMARY KEY,
	[SUB_MENU_ID] [INT] CONSTRAINT FK_SUB_MENU_LINK FOREIGN KEY REFERENCES [VMASTER].[TBL_SUB_MENU](SUB_MENU_ID),
	[LINK_NAME] [VARCHAR](100) NULL,
	[PAGE_ACTION] [VARCHAR](100) NULL,
	[REDIRECTION_TYPE] [VARCHAR](100) NULL,
	[LINK_LOCATION] [VARCHAR](100) NULL,
	[LINK_SEQ_ID] [INT] NULL,
	[STYLE_CSS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
 
 )

 GO

CREATE TABLE [VMASTER].[TBL_ROLE_TO_LINK_AND_PAGE]
	(
		[ROLE_TO_LINK_ID_ROLE_TO_LINK] [INT] IDENTITY(1,1) CONSTRAINT PK_ROLE_TO_LINK_MAS PRIMARY KEY,
		[ROLE_ID_ROLE_TO_LINK] [INT] CONSTRAINT FK_ROLE_ROLE_LINK FOREIGN KEY REFERENCES [VMASTER].[TBL_ROLE_MASTER](ROLE_ID),
		[LINK_ID_ROLE_TO_LINK] [INT] CONSTRAINT FK_LINK_ROLE_LINK FOREIGN KEY REFERENCES [VMASTER].[TBL_LINKS_AND_PAGES]([LINK_ID]),
		[STATUS_ROLE_TO_LINK] [VARCHAR](20) NULL,
		[CREATED_USER_ROLE_TO_LINK] [VARCHAR](50) NULL,
		[CREATED_DATE_ROLE_TO_LINK] [DATETIME] NULL,
		[CREATED_MAC_ADDR_ROLE_TO_LINK] [VARCHAR](50) NULL,
		[MODIFIED_USER_ROLE_TO_LINK] [VARCHAR](50) NULL,
		[MODIFIED_DATE_ROLE_TO_LINK] [DATETIME] NULL,
		[MODIFIED_MAC_ADDR_ROLE_TO_LINK] [VARCHAR](50) NULL,
	)
	 


	 GO

CREATE TABLE [VMASTER].[TBL_BUSINESS_PARTNER_MASTER]
(
	[BP_ID] [INT] IDENTITY(1,1) CONSTRAINT [PK_CUST_ID_MS] PRIMARY KEY CLUSTERED,
	BP_TYPE VARCHAR(50),-- CUSTOMER/SUPPLIER
	[BP_NAME] [VARCHAR](250) CONSTRAINT [UK_CUST_NAME_MS] UNIQUE NONCLUSTERED,
	[BP_SHORT_CODE] [VARCHAR](50) NULL,
	[TIN_NUMBER] [VARCHAR](100) NULL,
	[VAT_NUMBER] [VARCHAR](50) NULL,
	[CONTACT_PERSON] [VARCHAR](50) NULL,
	[CONTACT_NUMBER] [VARCHAR](50) NULL,
	[ADDRESS] [VARCHAR](1500) NULL,
	[EMAIL_ADDRESS] [VARCHAR](100) NULL,
	[PHONE_NUMBER_2] [VARCHAR](50) NULL,
	[COUNTRY_ID] [INT] CONSTRAINT [FK_COUNTR_ID_CUS_MAS] FOREIGN KEY REFERENCES [VMASTER].[TBL_COUNTRY_MASTER]([COUNTRY_ID]),
	[REGION_ID] [INT] NULL,
	[DISTRICT_ID] [INT] NULL,
	[LOCATION] [VARCHAR](100) NULL,-- TEXT
	[NATURE_OF_BUSINESS] [VARCHAR](50) NULL,-- B2B/B2C
	[CREDIT_ALLOWED] [VARCHAR](50) NULL,-- YES/NO
	[COMPANY_HEAD_CONTACT_PERSON] [VARCHAR](250) NULL,
	[COMPANY_HEAD_PHONE_NO] [VARCHAR](250) NULL,
	[COMPANY_HEAD_EMAIL] [VARCHAR](250) NULL,
	[ACCOUNTS_CONTACT_PERSON] [VARCHAR](250) NULL,
	[ACCOUNTS_PHONE_NO] [VARCHAR](250) NULL,
	[ACCOUNTS_EMAIL] [VARCHAR](250) NULL,
	[CURRENCY_ID] [INT] CONSTRAINT [FK_CURRENCY_ID] FOREIGN KEY REFERENCES [VMASTER].[TBL_CURRENCY_MASTER]([CURRENCY_ID]),
	[PAYMENT_TERMS] [VARCHAR](2500) NULL,
	SECTION_HEAD_RESPONSE_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_DATE DATETIME,-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	SECTION_HEAD_RESPONSE_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	RESPONSE_1_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_1_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_1_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	RESPONSE_2_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_DATE DATETIME,-- APPROVAL SCREEN AUTO
	RESPONSE_2_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	RESPONSE_2_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO

	FINAL_RESPONSE_PERSON VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_DATE DATETIME,-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_STATUS VARCHAR(50),-- APPROVAL SCREEN AUTO
	FINAL_RESPONSE_REMARKS VARCHAR(50),-- APPROVAL SCREEN AUTO
	[REMARKS] [VARCHAR](2000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,

);
-- ONCE ITS SAVED. EXISTING QUOTA ENTRY STATUS SHOULD CHANGE IT AS INACTIVE FOR THE SAME COMPANY/CAMPE/YEAR
GO


CREATE TABLE [VMASTER].[TBL_SALES_TYPE_MASTER]( --   
	[SALES_TYPE_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_SALES_TYPE_MAS PRIMARY KEY,
	[SALES_TYPE_NAME] [VARCHAR](50) CONSTRAINT UK_SALES_TYPE UNIQUE,-- TEXT -- HUNTING / PHOTOGRAPHY
	[SALES_TYPE_DESCRIPTION] [VARCHAR](50) ,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
  
  
CREATE TABLE [VMASTER].[TBL_PROFESSIONAL_HUNTER_MASTER]( --   
	[PH_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_PH_MAS PRIMARY KEY,
	[PH_NAME] [VARCHAR](50) CONSTRAINT UK_PH_NAME_MAS UNIQUE,-- TEXT  
	[PH_DESCRIPTION] [VARCHAR](50) ,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
  
  
create tablE TABLE [VMASTER].[TBL_ANIMAL_PARTS_MASTER] ( --   
	[ANIMAL_PARTS_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_ANIMAL_PARTS_MAS PRIMARY KEY,
	[ANIMAL_PARTS_NAME] [VARCHAR](50) CONSTRAINT UK_ANIMAL_PARTS_NAME_MAS UNIQUE,-- TEXT 
	[ANIMAL_PARTS_DESCRIPTION] [VARCHAR](50) ,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
  
CREATE TABLE [VMASTER].[TBL_ANTI_POACHING_FINDINGS_MASTER] ( --   
	[ANTI_POACHING_FINDINGS_ID] [INT] IDENTITY(1,1) CONSTRAINT PK_ANTI_POACHING_FIND_MAS PRIMARY KEY,
	[ANTI_POACHING_FINDINGS_NAME] [VARCHAR](50) CONSTRAINT UK_ANTI_POACHING_FIND_NAME_MAS UNIQUE,-- TEXT -- HUNTING / PHOTOGRAPHY
	[ANTI_POACHING_FINDINGS_DESCRIPTION] [VARCHAR](50) ,-- TEXT
	[REMARKS] [VARCHAR](1000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 GO
  


  
  
CREATE TABLE [VMASTER].[TBL_FIELD_HDR]( ---- COMMON DROP DOWN MASTER HDR
	[FIELD_ID_FLD_HDR] [BIGINT] IDENTITY(1,1) CONSTRAINT PK_FIELD_SNO PRIMARY KEY,
	[PROJECT_NAME_FLD_HDR] [VARCHAR](50) ,
	[FIELD_CATEGORY_FLD_HDR] [VARCHAR](50) CONSTRAINT UK_FIELD_CATE UNIQUE,
	[FIELD_DESC_FLD_HDR] [VARCHAR](150) NULL,
	[STATUS_FLD_HDR] [VARCHAR](20) NULL,
	[REMARKS_FLD_HDR] [VARCHAR](1000) NULL,
	[CREATED_USER_FLD_HDR] [VARCHAR](50) NULL,
	[CREATED_DATE_FLD_HDR] [DATETIME] NULL,
	[CREATED_MAC_ADDR_FLD_HDR] [VARCHAR](50) NULL,
	[MODIFIED_USER_FLD_HDR] [VARCHAR](50) NULL,
	[MODIFIED_DATE_FLD_HDR] [DATETIME] NULL,
	[MODIFIED_MAC_ADDR_FLD_HDR] [VARCHAR](50) NULL,
  )
   
GO

CREATE TABLE [VMASTER].[TBL_FIELD_DTL](---- COMMON DROP DOWN MASTER DTL
	[ACTIVITY_ID_FLD_DTL] [BIGINT] IDENTITY(1,1) CONSTRAINT PK_ACT_ID_MAS_DTL PRIMARY KEY,
	[FIELD_ID_FLD_DTL] [BIGINT] CONSTRAINT FK_FIELD_ID_DTL FOREIGN KEY REFERENCES  [VMASTER].[TBL_FIELD_HDR]([FIELD_ID_FLD_HDR]),
	[ACTIVITY_NAME_FLD_DTL] [VARCHAR](MAX) NULL,
	[ACTIVITY_DESC_FLD_DTL] [VARCHAR](MAX) NULL,
	[STATUS_FLD_DTL] [VARCHAR](10) NULL,
	[REMARKS_FLD_DTL] [VARCHAR](1000) NULL,
	[CREATED_USER_FLD_DTL] [VARCHAR](50) NULL,
	[CREATED_DATE_FLD_DTL] [DATETIME] NULL,
	[CREATED_MAC_ADDR_FLD_DTL] [VARCHAR](50) NULL,
	[MODIFIED_USER_FLD_DTL] [VARCHAR](50) NULL,
	[MODIFIED_DATE_FLD_DTL] [DATETIME] NULL,
	[MODIFIED_MAC_ADDR_FLD_DTL] [VARCHAR](50) NULL 
)
 
GO
 
CREATE TABLE [VMASTER].[TBL_PRODUCT_COMPANY_MAIN_CATEGORY_MAPPING](
	[SNO] [INT] IDENTITY(1,1) CONSTRAINT PK_SNO_PROD_MAIN_CATE_MAP PRIMARY KEY ,
	[COMPANY_ID] [INT] CONSTRAINT FK_COMP_ID_PROD_COMP_MAIN FOREIGN KEY REFERENCES VMASTER.TBL_COMPANY_MASTER(COMPANY_ID),
	[MAIN_CATEGORY_ID] [INT] CONSTRAINT FK_MAIN_CAT_ID_COMP_MAIN FOREIGN KEY REFERENCES VMASTER.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
	[REMARKS] [VARCHAR](2000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)
 
GO

CREATE TABLE [VMASTER].[TBL_STORE_PRODUCT_MINIMUM_STOCK](
	[SNO] [INT] IDENTITY(1,1) CONSTRAINT PK_SNO_PROD_MOQ  PRIMARY KEY,
	[COMPANY_ID] [INT] CONSTRAINT FK_COMP_ID_MOQ FOREIGN KEY REFERENCES  VMASTER.TBL_COMPANY_MASTER(COMPANY_ID),
	[CAMP_ID] [INT] CONSTRAINT FK_CAMP_ID_MOQ FOREIGN KEY REFERENCES VMASTER.TBL_CAMP_MASTER(CAMP_ID),
	[STORE_ID] [INT] CONSTRAINT FK_STORE_ID_MOQ FOREIGN KEY REFERENCES VMASTER.TBL_STORE_MASTER(STORE_ID),
	[MAIN_CATEGORY_ID] [INT]  CONSTRAINT FK_MAIN_CAT_ID_MOQ FOREIGN KEY REFERENCES VMASTER.TBL_PRODUCT_MAIN_CATEGORY_MASTER(MAIN_CATEGORY_ID),
	[SUB_CATEGORY_ID] [INT]  CONSTRAINT FK_SUB_CAT_ID_MOQ FOREIGN KEY REFERENCES VMASTER.TBL_PRODUCT_SUB_CATEGORY_MASTER(SUB_CATEGORY_ID),
	[PRODUCT_ID] [INT] CONSTRAINT FK_PROD_ID_MOQ FOREIGN KEY REFERENCES  VMASTER.TBL_PRODUCT_MASTER(PRODUCT_ID),
	[MINIMUM_STOCK_PCS] [INT] NULL,
	[PURCHASE_ALERT_QTY] [DECIMAL](15, 2) NULL,
	[REQUESTED_BY] [VARCHAR](50) NULL,
	[EFFECTIVE_FROM] [DATETIME] NULL,
	[EFFECTIVE_TO] [DATETIME] NULL,
	[REMARKS] [VARCHAR](2000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)

GO

CREATE TABLE [VMASTER].[TBL_RACK_SECTION_MASTER]
(
	[RACK_SECTION_ID] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_RACK_SECK_ID] PRIMARY KEY CLUSTERED,
	[RACK_SECTION_NAME] [VARCHAR](10) CONSTRAINT [UK_RACK_SECIOTN_NAME] UNIQUE NONCLUSTERED, -- A,B,C
	[RACK_SECTION_DESCRIPTION] [VARCHAR](100) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL
);
GO

CREATE TABLE [VMASTER].[TBL_RACK_MASTER]
(
	[RACK_ID] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_RACK_ID] PRIMARY KEY CLUSTERED,
	[RACK_NAME] [VARCHAR](40) CONSTRAINT [UK_RACK_NAME] UNIQUE NONCLUSTERED, -- COMP SHORT CODE/ CAMP SHORT CODE/ STORE SHORT CODE/RACK SECTION NAME/1,2,3,4,5,6
	[RACK_DESCRIPTION] [VARCHAR](100) ,
	[COMPANY_ID] [INT] CONSTRAINT [FK_COMP_ID_RACK_MAST] FOREIGN KEY REFERENCES [VMASTER].[TBL_COMPANY_MASTER]([COMPANY_ID]),
	[CAMP_ID] [INT] CONSTRAINT [FK_CAMP_ID_RACK_MAST] FOREIGN KEY REFERENCES [VMASTER].[TBL_CAMP_MASTER]([CAMP_ID]),
	[STORE_ID] [INT] CONSTRAINT [FK_STORE_ID_RACK_MAST] FOREIGN KEY REFERENCES [VMASTER].[TBL_STORE_MASTER]([STORE_ID]),
	[RACK_SECTION_ID] [INT] CONSTRAINT [FK_RACK_SECTION_ID_RACK_MAST] FOREIGN KEY REFERENCES [VMASTER].[TBL_RACK_SECTION_MASTER]([RACK_SECTION_ID]),
	[MAX_CAPACITY] [INT] NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[REMARKS] [VARCHAR](100) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
)

GO

CREATE TABLE [VMASTER].[TBL_PRODUCT_OPENING_STOCK]
(
	[SNO] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_OPEN_STK] PRIMARY KEY CLUSTERED,
	[OPENING_STOCK_DATE] [DATETIME] NULL,
	[COMPANY_ID] [INT] CONSTRAINT [FK_COMP_ID_POP] FOREIGN KEY REFERENCES [VMASTER].[TBL_COMPANY_MASTER]([COMPANY_ID]),
	[CAMP_ID] [INT] CONSTRAINT [FK_CAMP_ID_OP_STOCK] FOREIGN KEY REFERENCES [VMASTER].[TBL_CAMP_MASTER]([CAMP_ID]),
	[STORE_ID] [INT] CONSTRAINT [FK_STORE_ID_OPEN_STK] FOREIGN KEY REFERENCES [VMASTER].[TBL_STORE_MASTER]([STORE_ID]),
	[MAIN_CATEGORY_ID] [INT] CONSTRAINT [FK_MAIN_OPEN_STK] FOREIGN KEY REFERENCES [VMASTER].[TBL_PRODUCT_MAIN_CATEGORY_MASTER]([MAIN_CATEGORY_ID]),
	[SUB_CATEGORY_ID] [INT] CONSTRAINT [FK_SUB_OPEN_STK] FOREIGN KEY REFERENCES [VMASTER].[TBL_PRODUCT_SUB_CATEGORY_MASTER]([SUB_CATEGORY_ID]),
	[PRODUCT_ID] [INT] CONSTRAINT [FK_PRODUCT_OPEN_STK] FOREIGN KEY REFERENCES [VMASTER].[TBL_PRODUCT_MASTER]([PRODUCT_ID]),
	[QTY] [DECIMAL](15,2) NULL,
	APPROVED_BY VARCHAR(50),-- TEXT
	[REMARKS] [VARCHAR](2000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL
	
)

GO

CREATE TABLE [VMASTER].[TBL_VAT_PERCENTAGE_SETTING](
	[SNO] [INT] IDENTITY(1,1) CONSTRAINT PK_VAT_PERC_SETT PRIMARY KEY,
	[VAT_PERCENTAGE] [DECIMAL](15, 2) NULL,
	[EFFECTIVE_FROM] [DATETIME] NULL,
	[EFFECTIVE_TO] [DATETIME] NULL,
	[REMARKS] [VARCHAR](2000) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL,
	)

	GO
	--SELECT * FROM [VMASTER].TBL_BUSINESS_PARTNER_MASTER
	CREATE TABLE [VMASTER].[TBL_BP_PRODUCT_VAT_PERCENTAGE_SETTINGS_HDR]
(
	[BP_PROD_VAT_ID] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_SNO_CUST_VAT_MAP] PRIMARY KEY CLUSTERED,
	[COMPANY_ID] [INT] CONSTRAINT [FK_COMP_CUST_VAT_MAP1] FOREIGN KEY REFERENCES [VMASTER].[TBL_COMPANY_MASTER]([COMPANY_ID]),
	[BP_ID] [INT] CONSTRAINT [FK_CUST_CUST_VAT_MAP1] FOREIGN KEY REFERENCES [VMASTER].TBL_BUSINESS_PARTNER_MASTER([BP_ID]),
	[MAIN_CATEGORY_ID] [INT] CONSTRAINT [FK_MC_CUST_VAT_MAP1] FOREIGN KEY REFERENCES [VMASTER].[TBL_PRODUCT_MAIN_CATEGORY_MASTER]([MAIN_CATEGORY_ID]),
	[SUB_CATEGORY_ID] [INT] CONSTRAINT [FK_SC_CUST_VAT_MAP1] FOREIGN KEY REFERENCES [VMASTER].[TBL_PRODUCT_SUB_CATEGORY_MASTER]([SUB_CATEGORY_ID]),
	[PRODUCT_ID] [INT] CONSTRAINT [FK_CUST_PROD_VAT_MAP1] FOREIGN KEY REFERENCES [VMASTER].[TBL_PRODUCT_MASTER]([PRODUCT_ID]),
	[VAT_PERCENTAGE] [DECIMAL](10,2) NULL,
	[EFFECTIVE_FROM] [DATETIME] NULL,
	[EFFECTIVE_TO] [DATETIME] NULL,
	[REQUEST_STATUS] [VARCHAR](50) NULL,
	[REMARKS] [VARCHAR](100) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL
);

GO

CREATE TABLE [VMASTER].[TBL_BP_PRODUCT_VAT_PERCENTAGE_SETTINGS_FILES_UPLOAD](
	[SNO] [INT] IDENTITY(1,1) CONSTRAINT PK_SNO_BP_VAT_FILE_UPL PRIMARY KEY,
	[BP_PROD_VAT_ID] [INT] CONSTRAINT FK_CUST_ID_CUST FOREIGN KEY REFERENCES [VMASTER].[TBL_BP_PRODUCT_VAT_PERCENTAGE_SETTINGS_HDR]([BP_PROD_VAT_ID]),
	[DOCUMENT_TYPE] [VARCHAR](50) NULL,-- DROP DOWN
	[DESCRIPTIONS] [VARCHAR](100) NULL,-- TEXT
	[FILE_NAME] [VARCHAR](150) NULL,-- AUTO PICK FROM FILE UPLOAD
	[CONTENT_TYPE] [VARCHAR](50) NULL,-- AUTO PICK FROM FILE UPLOAD
	[CONTENT_DATA] [VARBINARY](MAX) NULL,-- AUTO PICK FROM FILE UPLOAD
	[REMARKS] [VARCHAR](100) NULL,
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
 
 
CREATE TABLE [VMASTER].[TBL_HOTEL_RESORT_MASTER]
(
	[HOTEL_ID] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_HOTEL_RESORT_ID] PRIMARY KEY CLUSTERED,
	HOTEL_TYPE VARCHAR(50), -- HOTEL/RESORT
	[HOTEL_NAME] [VARCHAR](10) CONSTRAINT [UK_HOTEL_NAME] UNIQUE NONCLUSTERED, -- A,B,C
	HOTEL_STAR VARCHAR(20),-- 1 STAR/ 2 STAR/3 STAR/4 STAR/5 STAR/6 STAR/7 STAR
	[COUNTRY_ID] [INT] CONSTRAINT FK_COUNTRY_ID_AIRPORT FOREIGN KEY REFERENCES VMASTER.TBL_COUNTRY_MASTER(COUNTRY_ID),-- DROP DOWN
	[REGION_ID] [INT]  CONSTRAINT FK_REG_ID_HOTEL FOREIGN KEY REFERENCES VMASTER.TBL_REGION_MASTER(REGION_ID),-- DROP DOWN
	[DISTRICT_ID] [INT] CONSTRAINT FK_DIST_ID_HOTEL FOREIGN KEY REFERENCES VMASTER.TBL_DISTRICT_MASTER(DISTRICT_ID),-- DROP DOWN
	LOCATION_NAME VARCHAR(50),-- TEXT
	HOTEL_ADDRESS VARCHAR(150),--- TEXT
	REMARKS VARCHAR(100),
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL
);
GO


CREATE TABLE [VMASTER].[TBL_AIRLINES_MASTER]
(
	[AIRLINE_ID] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_AIRLINE_ID] PRIMARY KEY CLUSTERED,
	[AIRLINE_NAME] [VARCHAR](10) CONSTRAINT [UK_AIRLINE_NAME_NAME] UNIQUE NONCLUSTERED, -- A,B,C
	REMARKS VARCHAR(100),
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL
);
GO


CREATE TABLE [VMASTER].[TBL_AIRPORT_MASTER]
(
	[AIRPORT_ID] [INT] IDENTITY(1,1) NOT NULL CONSTRAINT [PK_AIRPORT_ID] PRIMARY KEY CLUSTERED,
	[AIRPORT_NAME] [VARCHAR](10) CONSTRAINT [UK_AIRPORT_NAME] UNIQUE NONCLUSTERED, -- A,B,C
	[COUNTRY_ID] [INT] CONSTRAINT FK_COUNTRY_ID_HOTEL FOREIGN KEY REFERENCES VMASTER.TBL_COUNTRY_MASTER(COUNTRY_ID),-- DROP DOWN
	[REGION_ID] [INT]  ,--CONSTRAINT FK_REG_ID_HOTEL FOREIGN KEY REFERENCES VMASTER.TBL_REGION_MASTER(REGION_ID),-- DROP DOWN
	[DISTRICT_ID] [INT] ,--CONSTRAINT FK_DIST_ID_HOTEL FOREIGN KEY REFERENCES VMASTER.TBL_REGION_MASTER(REGION_ID),-- DROP DOWN
	LOCATION_NAME VARCHAR(50),-- TEXT
	AIRPORT_ADDRESS VARCHAR(150),--- TEXT
	REMARKS VARCHAR(100),
	[STATUS_MASTER] [VARCHAR](20) NULL,
	[CREATED_BY] [VARCHAR](50) NULL,
	[CREATED_DATE] [DATETIME] NULL,
	[CREATED_MAC_ADDRESS] [VARCHAR](50) NULL,
	[MODIFIED_BY] [VARCHAR](50) NULL,
	[MODIFIED_DATE] [DATETIME] NULL,
	[MODIFIED_MAC_ADDRESS] [VARCHAR](50) NULL
);
GO


CREATE TABLE [VMASTER].[TBL_GUN_BRAND_MASTER]
(
    GUN_BRAND_ID            INT IDENTITY(1,1) CONSTRAINT PK_TBL_GUN_BRAND_MASTER PRIMARY KEY,
    BRAND_NAME              VARCHAR(100)    NOT NULL,---- BRAND
    BP_ID       INT CONSTRAINT FK_BP_ID_GUN_BRAND FOREIGN KEY REFERENCES [VMASTER].[TBL_BUSINESS_PARTNER_MASTER](BP_ID),
    COUNTRY_OF_ORIGIN       INT    CONSTRAINT FK_COUNTRY_ID_GUN_BRAND FOREIGN KEY REFERENCES VMASTER.TBL_COUNTRY_MASTER(COUNTRY_ID),-- DROP DOWN
    WEBSITE                 VARCHAR(200)    NULL,
    CONTACT_PERSON          VARCHAR(100)    NULL,
    CONTACT_NUMBER          VARCHAR(30)     NULL,
    EMAIL                   VARCHAR(100)    NULL,
    WARRANTY_AVAILABLE      VARCHAR(20)     NULL, -- YES/NO
    REMARKS                 VARCHAR(100)    NULL,
    STATUS_MASTER           VARCHAR(20)     NULL,
    CREATED_BY              VARCHAR(50)     NULL,
    CREATED_DATE            DATETIME        NULL,
    CREATED_MAC_ADDRESS     VARCHAR(50)     NULL,
    MODIFIED_BY             VARCHAR(50)     NULL,
    MODIFIED_DATE           DATETIME        NULL,
    MODIFIED_MAC_ADDRESS    VARCHAR(50)     NULL
);
GO
--('CZ','CZ','ČESKÁ ZBROJOVKA','CZECH REPUBLIC','ACTIVE','ADMIN',GETDATE()),
--('WIN','WINCHESTER','WINCHESTER REPEATING ARMS','USA','ACTIVE','ADMIN',GETDATE()),
--('REM','REMINGTON','REMINGTON ARMS','USA','ACTIVE','ADMIN',GETDATE()),
--('SAKO','SAKO','SAKO LTD','FINLAND','ACTIVE','ADMIN',GETDATE()),
--('BLASER','BLASER','BLASER GMBH','GERMANY','ACTIVE','ADMIN',GETDATE()),
--('MAUSER','MAUSER','MAUSER','GERMANY','ACTIVE','ADMIN',GETDATE());
CREATE TABLE [VMASTER].[TBL_GUN_CATEGORY_MASTER]
(
    GUN_CATEGORY_ID         INT IDENTITY(1,1) CONSTRAINT PK_TBL_GUN_CATEGORY_MASTER PRIMARY KEY,
    GUN_CATEGORY_NAME           VARCHAR(100)    NOT NULL,-- RIFLE/SHOTGUN/HAND GUN
    DESCRIPTION             VARCHAR(200)    NULL,
    REMARKS                 VARCHAR(100)    NULL,
    STATUS_MASTER           VARCHAR(20)     NULL,
    CREATED_BY              VARCHAR(50)     NULL,
    CREATED_DATE            DATETIME        NULL,
    CREATED_MAC_ADDRESS     VARCHAR(50)     NULL,
    MODIFIED_BY             VARCHAR(50)     NULL,
    MODIFIED_DATE           DATETIME        NULL,
    MODIFIED_MAC_ADDRESS    VARCHAR(50)     NULL
);
GO

CREATE TABLE [VMASTER].[TBL_GUN_TYPE_MASTER]
(
    GUN_TYPE_ID             INT IDENTITY(1,1) CONSTRAINT PK_TBL_GUN_TYPE_MASTER PRIMARY KEY,
    TYPE_NAME               VARCHAR(100) NOT NULL,-- BOLT ACTION/DOUBLE RIFLE/LEVER ACTION/PUMP ACTION/SEMI AUTOMATIC
    DESCRIPTION             VARCHAR(200) NULL,
    REMARKS                 VARCHAR(100) NULL,
    STATUS_MASTER           VARCHAR(20) NULL,
    CREATED_BY              VARCHAR(50) NULL,
    CREATED_DATE            DATETIME NULL,
    CREATED_MAC_ADDRESS     VARCHAR(50) NULL,
    MODIFIED_BY             VARCHAR(50) NULL,
    MODIFIED_DATE           DATETIME NULL,
    MODIFIED_MAC_ADDRESS    VARCHAR(50) NULL
);
GO

CREATE TABLE [VMASTER].[TBL_CALIBER_MASTER]
(
    CALIBER_ID              INT IDENTITY(1,1) CONSTRAINT PK_TBL_CALIBER_MASTER PRIMARY KEY,
    CALIBER_CODE            VARCHAR(20) NOT NULL,
    CALIBER_NAME            VARCHAR(100) NOT NULL,
    METRIC_SIZE             VARCHAR(50) NULL,
    DESCRIPTION             VARCHAR(200) NULL,
    REMARKS                 VARCHAR(100) NULL,
    STATUS_MASTER           VARCHAR(20) NULL,
    CREATED_BY              VARCHAR(50) NULL,
    CREATED_DATE            DATETIME NULL,
    CREATED_MAC_ADDRESS     VARCHAR(50) NULL,
    MODIFIED_BY             VARCHAR(50) NULL,
    MODIFIED_DATE           DATETIME NULL,
    MODIFIED_MAC_ADDRESS    VARCHAR(50) NULL
);
GO
--- CALIBER SAMPLE DATA
--('223','223 REMINGTON','5.56 MM','SMALL GAME','', 'ACTIVE','ADMIN',GETDATE()),
--('243','243 WINCHESTER','6 MM','MEDIUM GAME','', 'ACTIVE','ADMIN',GETDATE()),
--('270','270 WINCHESTER','6.8 MM','PLAINS GAME','', 'ACTIVE','ADMIN',GETDATE()),
--('300WM','300 WIN MAG','7.62 MM','LARGE GAME','', 'ACTIVE','ADMIN',GETDATE()),
--('375HH','375 H&H MAGNUM','9.5 MM','DANGEROUS GAME','', 'ACTIVE','ADMIN',GETDATE()),
--('416R','416 RIGBY','10.6 MM','DANGEROUS GAME','', 'ACTIVE','ADMIN',GETDATE()),
--('458WM','458 WIN MAG','11.6 MM','BIG FIVE','', 'ACTIVE','ADMIN',GETDATE()),
--('470NE','470 NITRO EXPRESS','12 MM','ELEPHANT','', 'ACTIVE','ADMIN',GETDATE());

CREATE TABLE [VMASTER].[TBL_BULLET_TYPE_MASTER]
(
    BULLET_TYPE_ID          INT IDENTITY(1,1) CONSTRAINT PK_TBL_BULLET_TYPE_MASTER PRIMARY KEY,
    BULLET_TYPE_NAME        VARCHAR(100) NOT NULL,
    DESCRIPTION             VARCHAR(200) NULL,
    REMARKS                 VARCHAR(100) NULL,
    STATUS_MASTER           VARCHAR(20) NULL,
    CREATED_BY              VARCHAR(50) NULL,
    CREATED_DATE            DATETIME NULL,
    CREATED_MAC_ADDRESS     VARCHAR(50) NULL,
    MODIFIED_BY             VARCHAR(50) NULL,
    MODIFIED_DATE           DATETIME NULL,
    MODIFIED_MAC_ADDRESS    VARCHAR(50) NULL
);
GO
--('SP','SOFT POINT','SOFT POINT BULLET','', 'ACTIVE','ADMIN',GETDATE()),
--('SOLID','SOLID','SOLID BULLET','', 'ACTIVE','ADMIN',GETDATE()),
--('FMJ','FULL METAL JACKET','FMJ BULLET','', 'ACTIVE','ADMIN',GETDATE()),
--('HP','HOLLOW POINT','HOLLOW POINT BULLET','', 'ACTIVE','ADMIN',GETDATE()),
--('MONO','MONOLITHIC','COPPER BULLET','', 'ACTIVE','ADMIN',GETDATE());

CREATE TABLE [VMASTER].[TBL_AMMUNITION_BRAND_MASTER]
(
    AMMUNITION_BRAND_ID     INT IDENTITY(1,1) CONSTRAINT PK_TBL_AMMUNITION_BRAND_MASTER PRIMARY KEY,
    BRAND_NAME              VARCHAR(100) NOT NULL,
    COUNTRY_OF_ORIGIN       INT    CONSTRAINT FK_COUNTRY_ID_AMMUNI_BRAND FOREIGN KEY REFERENCES VMASTER.TBL_COUNTRY_MASTER(COUNTRY_ID),-- DROP DOWN
    CONTACT_PERSON          VARCHAR(100) NULL,
    CONTACT_NUMBER          VARCHAR(30) NULL,
    EMAIL                   VARCHAR(100) NULL,
    WEBSITE                 VARCHAR(200) NULL,
    REMARKS                 VARCHAR(100) NULL,
    STATUS_MASTER           VARCHAR(20) NULL,
    CREATED_BY              VARCHAR(50) NULL,
    CREATED_DATE            DATETIME NULL,
    CREATED_MAC_ADDRESS     VARCHAR(50) NULL,
    MODIFIED_BY             VARCHAR(50) NULL,
    MODIFIED_DATE           DATETIME NULL,
    MODIFIED_MAC_ADDRESS    VARCHAR(50) NULL
);
GO
--('HORNADY','HORNADY','USA','ACTIVE','ADMIN',GETDATE()),
--('NOSLER','NOSLER','USA','ACTIVE','ADMIN',GETDATE()),
--('FEDERAL','FEDERAL PREMIUM','USA','ACTIVE','ADMIN',GETDATE()),
--('NORMA','NORMA','SWEDEN','ACTIVE','ADMIN',GETDATE()),
--('BARNES','BARNES','USA','ACTIVE','ADMIN',GETDATE());
CREATE TABLE [VMASTER].[TBL_GUN_MASTER]
(
    GUN_ID                  INT IDENTITY(1,1) CONSTRAINT PK_TBL_GUN_MASTER PRIMARY KEY,
    GUN_CODE                VARCHAR(30) NOT NULL,
    GUN_NAME                VARCHAR(100) NOT NULL,
    GUN_CATEGORY_ID         INT CONSTRAINT FK_TBL_GUN_MASTER_GUN_CATEGORY REFERENCES [VMASTER].[TBL_GUN_CATEGORY_MASTER](GUN_CATEGORY_ID),
    GUN_TYPE_ID             INT CONSTRAINT FK_TBL_GUN_MASTER_GUN_TYPE REFERENCES [VMASTER].[TBL_GUN_TYPE_MASTER](GUN_TYPE_ID),
    GUN_BRAND_ID            INT CONSTRAINT FK_TBL_GUN_MASTER_GUN_BRAND REFERENCES [VMASTER].[TBL_GUN_BRAND_MASTER](GUN_BRAND_ID),
    CALIBER_ID              INT CONSTRAINT FK_TBL_GUN_MASTER_CALIBER REFERENCES [VMASTER].[TBL_CALIBER_MASTER](CALIBER_ID),
    CAMP_ID					INT CONSTRAINT FK_TBL_CAMP_MASTER REFERENCES [VMASTER].[TBL_CAMP_MASTER](CAMP_ID),
    STORE_ID				INT CONSTRAINT FK_TBL_STORE_MASTER REFERENCES [VMASTER].[TBL_STORE_MASTER](STORE_ID),
    MODEL                   VARCHAR(100) NULL,
    SERIAL_NUMBER           VARCHAR(100) NOT NULL,
    BARREL_LENGTH           DECIMAL(10,2) NULL,
    MAGAZINE_CAPACITY       INT NULL,
    LICENSE_NUMBER          VARCHAR(100) NULL,
    REMARKS                 VARCHAR(100) NULL,
    STATUS_MASTER           VARCHAR(20) NULL,
    CREATED_BY              VARCHAR(50) NULL,
    CREATED_DATE            DATETIME NULL,
    CREATED_MAC_ADDRESS     VARCHAR(50) NULL,
    MODIFIED_BY             VARCHAR(50) NULL,
    MODIFIED_DATE           DATETIME NULL,
    MODIFIED_MAC_ADDRESS    VARCHAR(50) NULL
);
GO
--('GUN0001','CZ 550 SAFARI',1,1,1,5,1,'550 SAFARI','CZ550001',25.0,5,'LIC001','ACTIVE','ADMIN',GETDATE()),
--('GUN0002','BLASER R8',1,1,5,6,1,'R8 PROFESSIONAL','BLR80001',24.0,4,'LIC002','ACTIVE','ADMIN',GETDATE());
CREATE TABLE [VMASTER].[TBL_BULLET_MASTER]
(
    BULLET_ID               INT IDENTITY(1,1) CONSTRAINT PK_TBL_BULLET_MASTER PRIMARY KEY,
    BULLET_CODE             VARCHAR(20) NOT NULL,
    BULLET_NAME             VARCHAR(100) NOT NULL,
    BULLET_TYPE_ID          INT CONSTRAINT FK_TBL_BULLET_MASTER_TYPE REFERENCES [VMASTER].[TBL_BULLET_TYPE_MASTER](BULLET_TYPE_ID),
    AMMUNITION_BRAND_ID     INT CONSTRAINT FK_TBL_BULLET_MASTER_BRAND REFERENCES [VMASTER].[TBL_AMMUNITION_BRAND_MASTER](AMMUNITION_BRAND_ID),
    CALIBER_ID              INT CONSTRAINT FK_TBL_BULLET_MASTER_CALIBER REFERENCES [VMASTER].[TBL_CALIBER_MASTER](CALIBER_ID),
    GRAIN_WEIGHT            DECIMAL(10,2) NULL,
    PACK_SIZE               INT NULL,
    ROUNDS_PER_BOX          INT NULL,
    REORDER_LEVEL           INT NULL,
    REMARKS                 VARCHAR(100) NULL,
    STATUS_MASTER           VARCHAR(20) NULL,
    CREATED_BY              VARCHAR(50) NULL,
    CREATED_DATE            DATETIME NULL,
    CREATED_MAC_ADDRESS     VARCHAR(50) NULL,
    MODIFIED_BY             VARCHAR(50) NULL,
    MODIFIED_DATE           DATETIME NULL,
    MODIFIED_MAC_ADDRESS    VARCHAR(50) NULL
);
GO
--('BLT001','HORNADY DGX 300GR',1,1,5,300,20,20,100,'ACTIVE','ADMIN',GETDATE()),
--('BLT002','FEDERAL SOLID 400GR',2,3,6,400,20,20,50,'ACTIVE','ADMIN',GETDATE());
