const BASE = "http://localhost:5000/api/v1";

let passed = 0;
let failed = 0;

function check(name: string, cond: boolean, extra?: any) {
  if (cond) {
    passed++;
    console.log(`PASS  ${name}`);
  } else {
    failed++;
    console.log(`FAIL  ${name}`, extra !== undefined ? JSON.stringify(extra) : "");
  }
}

async function api(path: string, init: RequestInit = {}, token?: string) {
  const headers: Record<string, string> = { ...(init.headers as Record<string, string> || {}) };
  if (token) headers["Authorization"] = `Bearer ${token}`;
  if (init.body && !headers["Content-Type"]) headers["Content-Type"] = "application/json";
  const res = await fetch(`${BASE}${path}`, { ...init, headers });
  let json: any = {};
  try { json = await res.json(); } catch (_) {}
  return { status: res.status, json };
}

const baseBody = {
  SALARY_DEDUCTION_TYPE: "SALARY",
  ADVANCE_TYPE: "Cash Advance",
  MONTH_ENTERED: "August",
  YEAR_ENTERED: 2026,
  EMP_ID: 1001,
  FIRST_NAME: "Test",
  MIDDLE_NAME: "",
  LAST_NAME: "Employee",
  COMPANY_ID: 4,
  DEPARTMENT_ID: 1,
  DESIGNATION_ID: 1,
  DEPARTMENT_GROUP_ID: 1,
  DESIGNATION_GROUP_ID: 1,
  CAMP_ID: 1,
  STORE_ID: 1,
  EMPLOYMENT_TYPE_ID: 1,
  GROSS_PAY: 50000,
  NET_PAY: 45000,
  ELIGIBLE_AMOUNT: 20000,
  DEDUCTION_FROM_DATE: "2026-09-01",
  DEDUCTION_TO_DATE: "2026-12-01",
  NO_OF_MONTHS: 4,
  PAYMENT_MODE_ID: 1,
  ACCOUNT_NO: "1234567890",
  STATUS_MASTER: "AC",
  USER: "sri",
  MAC_ADDRESS: "00-11-22-33-44-55",
};

async function run() {
  const login = await api("/auth/login", {
    method: "POST",
    body: JSON.stringify({ LOGIN_NAME: "sri", PASSWORD: "ana" }),
  });
  check("Login succeeds", login.status === 200 && !!login.json.accessToken, login.json);
  const token = login.json.accessToken;
  if (!token) {
    console.log("Aborting: no token");
    process.exit(1);
  }

  const sync = await api("/sync-menus", {}, token);
  check("Sync menus succeeds", sync.status === 200 && sync.json.success, sync.json);
  const syncedLink = (sync.json.synced || []).find((s: any) => s.route === "/cash-advance-request");
  check("Cash Advance Request link synced", !!syncedLink, sync.json.synced);

  const list1 = await api("/cash-advance-request", {}, token);
  check("GET list succeeds", list1.status === 200 && Array.isArray(list1.json.data), list1.json);
  const initialCount = (list1.json.data || []).length;
  console.log(`      initial record count: ${initialCount}`);

  const clientRef = `AD/${Date.now()}`;
  const create = await api("/cash-advance-request", {
    method: "POST",
    body: JSON.stringify({
      CASH_ADV_REQUEST_REF_NO: clientRef,
      REQUEST_AMOUNT: 10000,
      APPROVED_AMOUNT: 0,
      MONTHLY_DEDUCTION: 2500,
      BANK_ID: 2,
      REASON: "Test cash advance",
      REMARKS: "Standard cash advance request",
      ...baseBody,
    }),
  }, token);
  check("POST create succeeds", create.status === 200 && create.json.success && !!create.json.SNO, create.json);
  const sno = create.json.SNO;
  if (!sno) {
    console.log("Aborting: no SNO returned");
    process.exit(1);
  }
  console.log(`      created SNO: ${sno}`);

  // Ref is auto-generated by the SAVE SP; read it back from the list
  const listAfterCreate = await api("/cash-advance-request?status=AC", {}, token);
  const createdRow = (listAfterCreate.json.data || []).find((r: any) => Number(r.SNO) === Number(sno));
  const refNo = createdRow?.CASH_ADV_REQUEST_REF_NO || "";
  check("Created record visible in list with ref", !!createdRow && !!refNo, createdRow);
  console.log(`      stored ref no: ${refNo}`);

  const getOne = await api(`/cash-advance-request/${encodeURIComponent(refNo)}`, {}, token);
  check("GET by ref returns created record", getOne.status === 200 && getOne.json.data?.CASH_ADV_REQUEST_REF_NO === refNo, getOne.json);
  check("GET by ref salary deduction type", getOne.json.data?.SALARY_DEDUCTION_TYPE === "SALARY", getOne.json.data);
  check("GET by ref request amount", Number(getOne.json.data?.REQUEST_AMOUNT) === 10000, getOne.json.data);
  check("GET by ref monthly deduction", Number(getOne.json.data?.MONTHLY_DEDUCTION) === 2500, getOne.json.data);

  const update = await api(`/cash-advance-request/${sno}`, {
    method: "PUT",
    body: JSON.stringify({
      SNO: sno,
      CASH_ADV_REQUEST_REF_NO: refNo,
      REQUEST_AMOUNT: 12000,
      APPROVED_AMOUNT: 12000,
      MONTHLY_DEDUCTION: 3000,
      BANK_ID: 2,
      REASON: "Test cash advance (updated)",
      REMARKS: "Updated cash advance request",
      ...baseBody,
    }),
  }, token);
  check("PUT update succeeds", update.status === 200 && update.json.success, update.json);

  const list2 = await api("/cash-advance-request?status=AC", {}, token);
  const updated = (list2.json.data || []).find((r: any) => Number(r.SNO) === Number(sno));
  check("Updated record visible in list", !!updated && Number(updated.REQUEST_AMOUNT) === 12000, updated);
  check("Update persisted approved amount", updated?.APPROVED_AMOUNT != null && Number(updated.APPROVED_AMOUNT) === 12000, updated);

  const list3 = await api("/cash-advance-request?status=IN", {}, token);
  check("GET inactive list succeeds", list3.status === 200 && Array.isArray(list3.json.data), list3.json);

  const del = await api(`/cash-advance-request/${encodeURIComponent(refNo)}?USER=sri&ROLE=Admin&MAC_ADDRESS=00-11-22-33-44-55`, { method: "DELETE" }, token);
  check("DELETE succeeds", del.status === 200 && del.json.success, del.json);

  const list4 = await api("/cash-advance-request", {}, token);
  const stillThere = (list4.json.data || []).find((r: any) => Number(r.SNO) === Number(sno));
  check("Deleted record no longer in list", !stillThere, list4.json);
  console.log(`      final record count: ${(list4.json.data || []).length}`);

  console.log(`\n${passed} passed, ${failed} failed`);
  process.exit(failed > 0 ? 1 : 0);
}

run().catch((e) => {
  console.error("Test error:", e);
  process.exit(1);
});