ALTER PROCEDURE [VMaster].[LOGIN_USER]
(
    @LOGIN_NAME VARCHAR(50),
    @PASSWORD VARCHAR(255)
)
AS
BEGIN
    SET NOCOUNT ON;

    SELECT
        U.LOGIN_ID,
        U.LOGIN_NAME,
        U.ROLE,
        U.MAIL_ID,
        U.STOCK_SHOW_STATUS,
        U.OUTSIDE_ACCESS_Y_N,
        U.STATUS_MASTER AS USER_STATUS,
        R.ROLE_ID,
        R.STATUS_MASTER AS ROLE_STATUS
    FROM VMaster.TBL_USER_INFO_HDR U
    LEFT JOIN VMaster.TBL_ROLE_MASTER R 
        ON LOWER(LTRIM(RTRIM(R.ROLE_NAME))) = LOWER(LTRIM(RTRIM(U.ROLE)))
    WHERE U.LOGIN_NAME = @LOGIN_NAME
      AND U.PASSWORD = @PASSWORD;
END
