import express from "express"
import { authenticate } from "../middlewares/authenticate.middleware";
import { checkPermission } from "../middlewares/checkPermission.middleware";
import AuthRouter from "./auth.routers";
import UserRouter from "./user.routers";
import RoleRouter from "./role.routers";
import MainMenuRouter from "./mainMenu.routers";
import SubMenuRouter from "./subMenu.routers";
import LinksAndPagesRouter from "./linksAndPages.routers";
import RoleToLinkRouter from "./roleToLink.routers";
import CurrencyMasterRouter from "./currencyMaster.routers";
import UomMasterRouter from "./uomMaster.routers";
import CountryMasterRouter from "./countryMaster.routers";
import RegionMasterRouter from "./regionMaster.routers";
import DistrictMasterRouter from "./districtMaster.routers";

import NavigationRouter from "./navigation.routers";
import { fixMenus, resetAndReseedMenus, syncMenus, cleanupDuplicateMenus } from "../controllers/fix.controller";

import CompanyMasterRouter from "./companyMaster.routers";
import CampMasterRouter from "./campMaster.routers";
import StoreMasterRouter from "./storeMaster.routers";
import ProductMainCategoryRouter from "./productMainCategoryMaster.routers";
import ProductSubCategoryRouter from "./productSubCategoryMaster.routers";
import CostCentreMasterRouter from "./costCentreMaster.routers";
import ProductMasterRouter from "./productMaster.routers";
import UserStoreMappingRouter from "./userStoreMapping.routers";
import ExchangeRateMasterRouter from "./exchangeRateMaster.routers";
import AnimalMasterRouter from "./animalMaster.routers";
import PriceTypeMasterRouter from "./priceTypeMaster.routers";
import SalesPackageTypeMasterRouter from "./salesPackageTypeMaster.routers";
import PricePackageMasterRouter from "./pricePackageMaster.routers";
import PriceListMasterRouter from "./priceListMaster.routers";
import ProductOpeningStockRouter from "./productOpeningStock.routers";
import ProductCompanyMainCategoryMappingRouter from "./productCompanyMainCategoryMapping.routers";
import SalesTypeMasterRouter from "./salesTypeMaster.routers";
import ProfessionalHunterMasterRouter from "./professionalHunterMaster.routers";
import AntiPoachingFindingsMasterRouter from "./antiPoachingFindingsMaster.routers";
import RackSectionMasterRouter from "./rackSectionMaster.routers";
import RackMasterRouter from "./rackMaster.routers";
import VatPercentageSettingRouter from "./vatPercentageSetting.routers";
import HotelResortMasterRouter from "./hotelResortMaster.routers";
import AirlinesMasterRouter from "./airlinesMaster.routers";
import CaliberMasterRouter from "./caliberMaster.routers";
import BulletTypeMasterRouter from "./bulletTypeMaster.routers";
import AmmunitionBrandMasterRouter from "./ammunitionBrandMaster.routers";
import LicensePermitTypeRouter from "./licensePermitType.routers";
import LicensePermitCostRouter from "./licensePermitCost.routers";
import SalesPackageTypeRouter from "./salesPackageType.routers";
import PriceTypeRouter from "./priceType.routers";
import PricePackageRouter from "./pricePackage.routers";
import PaymentModeMasterRouter from "./paymentModeMaster.routers";
import PaymentTriggerEventMasterRouter from "./paymentTriggerEventMaster.routers";
import PayrollDeductionTypeMasterRouter from "./payrollDeductionTypeMaster.routers";
import MonthlyAutoDeductionRouter from "./monthlyAutoDeduction.routers";
import DepartmentMasterRouter from "./departmentMaster.routers";
import DesignationMasterRouter from "./designationMaster.routers";
import DepartmentGroupMasterRouter from "./departmentGroupMaster.routers";
import GunTypeMasterRouter from "./gunTypeMaster.routers";
import GunCategoryMasterRouter from "./gunCategoryMaster.routers";
import TrailerTypeMasterRouter from "./trailerTypeMaster.routers";
import BusBoardingLocationMasterRouter from "./busBoardingLocationMaster.routers";
import VisaTypeMasterRouter from "./visaTypeMaster.routers";
import EmployeeContractTypeMasterRouter from "./employeeContractTypeMaster.routers";
import EmployeeWorkingStatusMasterRouter from "./employeeWorkingStatusMaster.routers";
import CreditLimitPaymentModeMasterRouter from "./creditLimitPaymentModeMaster.routers";
import TrailerMasterRouter from "./trailerMaster.routers";
import TrailerMasterFilesRouter from "./trailerMasterFiles.routers";
import LocationMasterRouter from "./locationMaster.routers";
import BloodGroupMasterRouter from "./bloodGroupMaster.routers";
import TripTemplateMasterRouter from "./tripTemplateMaster.routers";
import TripTemplatePriceMappingRouter from "./tripTemplatePriceMapping.routers";
import CustomerWiseTripTemplatePriceMappingRouter from "./customerWiseTripTemplatePriceMapping.routers";

import CompanyQuotaAnimalMappingCombinedRouter from "./companyQuotaAnimalMappingCombined.routers";
import FieldCombinedRouter from "./fieldCombined.routers";
import AnimalHuntingChargesMasterCombinedRouter from "./animalHuntingChargesMasterCombined.routers";
import EmployeeBenefitMasterCombinedRouter from "./employeeBenefitMasterCombined.routers";

import GunBrandMasterRouter from "./gunBrandMaster.routers";
import BusinessPartnerMasterRouter from "./businessPartnerMaster.routers";
import GunMasterRouter from "./gunMaster.routers";
import BulletMasterRouter from "./bulletMaster.routers";
import BankMasterRouter from "./bankMaster.routers";
import CompanyBankAccountMasterRouter from "./companyBankAccountMaster.routers";
import VideographerMasterRouter from "./videographerMaster.routers";
import MassagerMasterRouter from "./massagerMaster.routers";

import CompanyDepartmentDesignationMappingRouter from "./companyDepartmentDesignationMapping.routers";
import CompanyCampStoreMappingRouter from "./companyCampStoreMapping.routers";
import DesignationGroupMasterRouter from "./designationGroupMaster.routers";
import NewSalaryScaleRouter from "./newSalaryScale.routers";
import AnimalPartsMasterRouter from "./animalPartsMaster.routers";
import StoreProductMinimumStockRouter from "./storeProductMinimumStock.routers";
import AirportMasterRouter from "./airportMaster.routers";
import ManPowerChangeRequestRouter from "./manPowerChangeRequest.routers";
import ManPowerApprovedSettingsRouter from "./manPowerApprovedSettings.routers";
import EmploymentTypeMasterRouter from "./employmentTypeMaster.routers";
import TruckTypeMasterRouter from "./truckTypeMaster.routers";
import FuelStationMasterRouter from "./fuelStationMaster.routers";
import PaymentTermMasterRouter from "./paymentTermMaster.routers";
import EducationQualificationMasterRouter from "./educationQualificationMaster.routers";
import CustomerCreditLimitDetailsRouter from "./customerCreditLimitDetails.routers";
import DriverTruckMasterMappingRouter from "./driverTruckMasterMapping.routers";
import TruckMasterHdrRouter from "./truckMasterHdr.routers";
import FuelTypeMasterRouter from "./fuelTypeMaster.routers";
import DriverMasterRouter from "./driverMaster.routers";
import TruckMasterFilesRouter from "./truckMasterFiles.routers";
import BpProductVatPercentageSettingsRouter from "./bpProductVatPercentageSettings.routers";
import BpProductVatPercentageSettingsFilesRouter from "./bpProductVatPercentageSettingsFiles.routers";
import HolidayEntriesRouter from "./holidayEntries.routers";
import EmployeeDatabaseRouter from "./employeeDatabase.routers";
import DMSRouter from "./dms.routers";
import DriverMasterFilesRouter from "./driverMasterFiles.routers";
import ClientAdditionalServicesMasterRouter from "./clientAdditionalServicesMaster.routers";
import AttendanceTypeMasterRouter from "./attendanceTypeMaster.routers";
import AttendanceDetailsRouter from "./attendanceDetails.routers";
import AttendanceRequestRouter from "./attendanceRequest.routers";
import CashAdvanceRouter from "./cashAdvance.routers";
import CashAdvanceRequestRouter from "./cashAdvanceRequest.routers";
import ArrearsRequestRouter from "./arrearsRequest.routers";
import ArrearEntriesRouter from "./arrearEntries.routers";
import OvertimeRequestRouter from "./overtimeRequest.routers";
import OvertimeEntriesRouter from "./overtimeEntries.routers";
import BonusRequestRouter from "./bonusRequest.routers";
import BonusEntriesRouter from "./bonusEntries.routers";
import LeaveEncashmentRouter from "./leaveEncashment.routers";
import LeaveEncashmentEntriesRouter from "./leaveEncashmentEntries.routers";
import DeductionEntriesRouter from "./deductionEntries.routers";
import EmployeeBenefitTypeMasterRouter from "./employeeBenefitTypeMaster.routers";
import OverTimeReferenceEntriesRouter from "./overtimeReferenceEntries.routers";
import LaborChargeEntriesRouter from "./laborChargeEntries.routers";
import PromotionDemotionTransferRequestRouter from "./promotionDemotionTransferRequest.routers";
import PromotionDemotionTransferEntriesRouter from "./promotionDemotionTransferEntries.routers";
import WarningFormsRouter from "./warningForms.routers";
import ShiftNameMasterRouter from "./shiftNameMaster.routers";
import EmployeeDailyShiftDetailsRouter from "./employeeDailyShiftDetails.routers";
import WeekDayMasterRouter from "./weekDayMaster.routers";
import DashboardRouter from "./dashboard.routers";
import ApprovalRouter from "./approval.routers";

const Router = express.Router()

Router.use("/auth", AuthRouter);
Router.use("/users", authenticate, checkPermission("/users"), UserRouter);
Router.use("/roles", authenticate, checkPermission("/roles"), RoleRouter);
Router.use("/main-menu", authenticate, checkPermission("/main-menu"), MainMenuRouter);
Router.use("/sub-menu", authenticate, checkPermission("/sub-menu"), SubMenuRouter);
Router.use("/links-and-pages", authenticate, checkPermission("/links-and-pages"), LinksAndPagesRouter);
Router.use("/role-to-link", authenticate, checkPermission("/role-to-link"), RoleToLinkRouter);
Router.use("/currency-master", authenticate, checkPermission("/currency-master"), CurrencyMasterRouter);
Router.use("/uom-master", authenticate, checkPermission("/uom-master"), UomMasterRouter);
Router.use("/country-master", authenticate, checkPermission("/country-master"), CountryMasterRouter);
Router.use("/region-master", authenticate, checkPermission("/region-master"), RegionMasterRouter);
Router.use("/district-master", authenticate, checkPermission("/district-master"), DistrictMasterRouter);

Router.use("/navigation", authenticate, NavigationRouter);
Router.get("/fix", authenticate, fixMenus);
Router.get("/fix-reset", authenticate, resetAndReseedMenus);
Router.get("/sync-menus", authenticate, syncMenus);
Router.get("/cleanup-duplicates", authenticate, cleanupDuplicateMenus);

Router.use("/company-master", authenticate, checkPermission("/company-master"), CompanyMasterRouter);
Router.use("/camp-master", authenticate, checkPermission("/camp-master"), CampMasterRouter);
Router.use("/store-master", authenticate, checkPermission("/store-master"), StoreMasterRouter);
Router.use("/product-main-category", authenticate, checkPermission("/product-main-category"), ProductMainCategoryRouter);
Router.use("/product-sub-category", authenticate, checkPermission("/product-sub-category"), ProductSubCategoryRouter);
Router.use("/cost-centre-master", authenticate, checkPermission("/cost-centre-master"), CostCentreMasterRouter);
Router.use("/product-master", authenticate, checkPermission("/product-master"), ProductMasterRouter);
Router.use("/user-store-mapping", authenticate, checkPermission("/user-store-mapping"), UserStoreMappingRouter);
Router.use("/exchange-rate-master", authenticate, checkPermission("/exchange-rate-master"), ExchangeRateMasterRouter);
Router.use("/animal-master", authenticate, checkPermission("/animal-master"), AnimalMasterRouter);
Router.use("/price-type-master", authenticate, checkPermission("/price-type-master"), PriceTypeMasterRouter);
Router.use("/sales-package-type-master", authenticate, checkPermission("/sales-package-type-master"), SalesPackageTypeMasterRouter);
Router.use("/price-package-master", authenticate, checkPermission("/price-package-master"), PricePackageMasterRouter);
Router.use("/price-list-master", authenticate, checkPermission("/price-list-master"), PriceListMasterRouter);
Router.use("/product-opening-stock", authenticate, checkPermission("/product-opening-stock"), ProductOpeningStockRouter);
Router.use("/product-company-main-category-mapping", authenticate, checkPermission("/product-company-main-category-mapping"), ProductCompanyMainCategoryMappingRouter);
Router.use("/sales-type-master", authenticate, checkPermission("/sales-type-master"), SalesTypeMasterRouter);
Router.use("/professional-hunter-master", authenticate, checkPermission("/professional-hunter-master"), ProfessionalHunterMasterRouter);
Router.use("/anti-poaching-findings-master", authenticate, checkPermission("/anti-poaching-findings-master"), AntiPoachingFindingsMasterRouter);
Router.use("/rack-section-master", authenticate, checkPermission("/rack-section-master"), RackSectionMasterRouter);
Router.use("/rack-master", authenticate, checkPermission("/rack-master"), RackMasterRouter);
Router.use("/vat-percentage-setting", authenticate, checkPermission("/vat-percentage-setting"), VatPercentageSettingRouter);
Router.use("/hotel-resort-master", authenticate, checkPermission("/hotel-resort-master"), HotelResortMasterRouter);
Router.use("/airlines-master", authenticate, checkPermission("/airlines-master"), AirlinesMasterRouter);
Router.use("/caliber-master", authenticate, checkPermission("/caliber-master"), CaliberMasterRouter);
Router.use("/bullet-type-master", authenticate, checkPermission("/bullet-type-master"), BulletTypeMasterRouter);
Router.use("/ammunition-brand-master", authenticate, checkPermission("/ammunition-brand-master"), AmmunitionBrandMasterRouter);
Router.use("/license-permit-type", authenticate, checkPermission("/license-permit-type"), LicensePermitTypeRouter);
Router.use("/license-permit-cost", authenticate, checkPermission("/license-permit-cost"), LicensePermitCostRouter);
Router.use("/sales-package-type", authenticate, checkPermission("/sales-package-type"), SalesPackageTypeRouter);
Router.use("/price-type", authenticate, checkPermission("/price-type"), PriceTypeRouter);
Router.use("/price-package", authenticate, checkPermission("/price-package"), PricePackageRouter);
Router.use("/payment-mode-master", authenticate, checkPermission("/payment-mode-master"), PaymentModeMasterRouter);
Router.use("/payment-trigger-event-master", authenticate, checkPermission("/payment-trigger-event-master"), PaymentTriggerEventMasterRouter);
Router.use("/payroll-deduction-type-master", authenticate, checkPermission("/payroll-deduction-type-master"), PayrollDeductionTypeMasterRouter);
Router.use("/monthly-auto-deduction", authenticate, checkPermission("/monthly-auto-deduction"), MonthlyAutoDeductionRouter);
Router.use("/department-master", authenticate, checkPermission("/department-master"), DepartmentMasterRouter);
Router.use("/designation-master", authenticate, checkPermission("/designation-master"), DesignationMasterRouter);
Router.use("/department-group-master", authenticate, checkPermission("/department-group-master"), DepartmentGroupMasterRouter);
Router.use("/gun-type-master", authenticate, checkPermission("/gun-type-master"), GunTypeMasterRouter);
Router.use("/gun-category-master", authenticate, checkPermission("/gun-category-master"), GunCategoryMasterRouter);
Router.use("/trailer-type-master", authenticate, checkPermission("/trailer-type-master"), TrailerTypeMasterRouter);
Router.use("/bus-boarding-location-master", authenticate, checkPermission("/bus-boarding-location-master"), BusBoardingLocationMasterRouter);
Router.use("/visa-type-master", authenticate, checkPermission("/visa-type-master"), VisaTypeMasterRouter);
Router.use("/employee-contract-type-master", authenticate, checkPermission("/employee-contract-type-master"), EmployeeContractTypeMasterRouter);
Router.use("/employee-working-status-master", authenticate, checkPermission("/employee-working-status-master"), EmployeeWorkingStatusMasterRouter);


Router.use("/field", authenticate, checkPermission("/field"), FieldCombinedRouter);
Router.use("/company-quota-animal-mapping", authenticate, checkPermission("/company-quota-animal-mapping"), CompanyQuotaAnimalMappingCombinedRouter);
Router.use("/animal-hunting-charges-master", authenticate, checkPermission("/animal-hunting-charges-master"), AnimalHuntingChargesMasterCombinedRouter);
Router.use("/employee-benefit-master", authenticate, checkPermission("/employee-benefit-master"), EmployeeBenefitMasterCombinedRouter);

Router.use("/gun-brand-master", authenticate, checkPermission("/gun-brand-master"), GunBrandMasterRouter);
Router.use("/business-partner-master", authenticate, checkPermission("/business-partner-master"), BusinessPartnerMasterRouter);
Router.use("/gun-master", authenticate, checkPermission("/gun-master"), GunMasterRouter);
Router.use("/bullet-master", authenticate, checkPermission("/bullet-master"), BulletMasterRouter);
Router.use("/bank-master", authenticate, checkPermission("/bank-master"), BankMasterRouter);
Router.use("/company-bank-account-master", authenticate, checkPermission("/company-bank-account-master"), CompanyBankAccountMasterRouter);
Router.use("/videographer-master", authenticate, checkPermission("/videographer-master"), VideographerMasterRouter);
Router.use("/massager-master", authenticate, checkPermission("/massager-master"), MassagerMasterRouter);
Router.use("/credit-limit-payment-mode-master", authenticate, checkPermission("/credit-limit-payment-mode-master"), CreditLimitPaymentModeMasterRouter);
Router.use("/trailer-master", authenticate, checkPermission("/trailer-master"), TrailerMasterRouter);
Router.use("/trailer-master-files", authenticate, checkPermission("/trailer-master"), TrailerMasterFilesRouter);
Router.use("/location-master", authenticate, checkPermission("/location-master"), LocationMasterRouter);
Router.use("/blood-group-master", authenticate, checkPermission("/blood-group-master"), BloodGroupMasterRouter);
Router.use("/trip-template-master", authenticate, checkPermission("/trip-template-master"), TripTemplateMasterRouter);
Router.use("/trip-template-price-mapping", authenticate, checkPermission("/trip-template-price-mapping"), TripTemplatePriceMappingRouter);
Router.use("/customer-wise-trip-template-price-mapping", authenticate, checkPermission("/customer-wise-trip-template-price-mapping"), CustomerWiseTripTemplatePriceMappingRouter);
Router.use("/company-department-designation-mapping", authenticate, checkPermission("/company-department-designation-mapping"), CompanyDepartmentDesignationMappingRouter);
Router.use("/company-camp-store-mapping", authenticate, checkPermission("/company-camp-store-mapping"), CompanyCampStoreMappingRouter);
Router.use("/designation-group-master", authenticate, checkPermission("/designation-group-master"), DesignationGroupMasterRouter);
Router.use("/new-salary-scale", authenticate, checkPermission("/new-salary-scale"), NewSalaryScaleRouter);
Router.use("/animal-parts-master", authenticate, checkPermission("/animal-parts-master"), AnimalPartsMasterRouter);
Router.use("/store-product-minimum-stock", authenticate, checkPermission("/store-product-minimum-stock"), StoreProductMinimumStockRouter);
Router.use("/airport-master", authenticate, checkPermission("/airport-master"), AirportMasterRouter);
Router.use("/man-power-change-request", authenticate, checkPermission("/man-power-change-request"), ManPowerChangeRequestRouter);
Router.use("/man-power-approved-settings", authenticate, checkPermission("/man-power-approved-settings"), ManPowerApprovedSettingsRouter);
Router.use("/employment-type-master", authenticate, checkPermission("/employment-type-master"), EmploymentTypeMasterRouter);
Router.use("/education-qualification-master", authenticate, checkPermission("/education-qualification-master"), EducationQualificationMasterRouter);
Router.use("/customer-credit-limit-details", authenticate, checkPermission("/customer-credit-limit-details"), CustomerCreditLimitDetailsRouter);
Router.use("/truck-type-master", authenticate, checkPermission("/truck-type-master"), TruckTypeMasterRouter);
Router.use("/fuel-station-master", authenticate, checkPermission("/fuel-station-master"), FuelStationMasterRouter);
Router.use("/payment-term-master", authenticate, checkPermission("/payment-term-master"), PaymentTermMasterRouter);
Router.use("/driver-truck-master-mapping", authenticate, checkPermission("/driver-truck-master-mapping"), DriverTruckMasterMappingRouter);
Router.use("/truck-master", authenticate, checkPermission("/truck-master"), TruckMasterHdrRouter);
Router.use("/fuel-type-master", authenticate, checkPermission("/fuel-type-master"), FuelTypeMasterRouter);
Router.use("/driver-master", authenticate, checkPermission("/driver-master"), DriverMasterRouter);
Router.use("/driver-master-files", authenticate, checkPermission("/driver-master"), DriverMasterFilesRouter);
Router.use("/truck-master-files", authenticate, checkPermission("/truck-master"), TruckMasterFilesRouter);
Router.use("/bp-product-vat-percentage-settings", authenticate, checkPermission("/bp-product-vat-percentage-settings"), BpProductVatPercentageSettingsRouter);
Router.use("/bp-product-vat-percentage-settings-files", authenticate, checkPermission("/bp-product-vat-percentage-settings"), BpProductVatPercentageSettingsFilesRouter);
Router.use("/client-additional-services-master", authenticate, checkPermission("/client-additional-services-master"), ClientAdditionalServicesMasterRouter);
Router.use("/attendance-type-master", authenticate, checkPermission("/attendance-type-master"), AttendanceTypeMasterRouter);
Router.use("/attendance-details", authenticate, checkPermission("/attendance-details"), AttendanceDetailsRouter);
Router.use("/attendance-request", authenticate, checkPermission("/attendance-request"), AttendanceRequestRouter);
Router.use("/cash-advance", authenticate, checkPermission("/cash-advance"), CashAdvanceRouter);
Router.use("/cash-advance-request", authenticate, checkPermission("/cash-advance-request"), CashAdvanceRequestRouter);
Router.use("/arrears-request", authenticate, checkPermission("/arrears-request"), ArrearsRequestRouter);
Router.use("/arrear-entries", authenticate, checkPermission("/arrear-entries"), ArrearEntriesRouter);
Router.use("/overtime-request", authenticate, checkPermission("/overtime-request"), OvertimeRequestRouter);
Router.use("/overtime-entries", authenticate, checkPermission("/overtime-entries"), OvertimeEntriesRouter);
Router.use("/bonus-request", authenticate, checkPermission("/bonus-request"), BonusRequestRouter);
Router.use("/bonus-entries", authenticate, checkPermission("/bonus-entries"), BonusEntriesRouter);
Router.use("/leave-encashment-request", authenticate, checkPermission("/leave-encashment-request"), LeaveEncashmentRouter);
Router.use("/leave-encashment-entries", authenticate, checkPermission("/leave-encashment-entries"), LeaveEncashmentEntriesRouter);
Router.use("/deduction-entries", authenticate, checkPermission("/deduction-entries"), DeductionEntriesRouter);
Router.use("/employee-benefit-type-master", authenticate, checkPermission("/employee-benefit-type-master"), EmployeeBenefitTypeMasterRouter);
Router.use("/overtime-reference-entries", authenticate, checkPermission("/overtime-reference-entries"), OverTimeReferenceEntriesRouter);
Router.use("/labor-charge-entries", authenticate, checkPermission("/labor-charge-entries"), LaborChargeEntriesRouter);
Router.use("/promotion-demotion-transfer-request", authenticate, checkPermission("/promotion-demotion-transfer-request"), PromotionDemotionTransferRequestRouter);
Router.use("/promotion-demotion-transfer-entries", authenticate, checkPermission("/promotion-demotion-transfer-entries"), PromotionDemotionTransferEntriesRouter);
Router.use("/warning-forms", authenticate, checkPermission("/warning-forms"), WarningFormsRouter);
Router.use("/shift-name-master", authenticate, checkPermission("/shift-name-master"), ShiftNameMasterRouter);
Router.use("/employee-daily-shift-details", authenticate, checkPermission("/employee-daily-shift-details"), EmployeeDailyShiftDetailsRouter);
Router.use("/week-day-master", authenticate, checkPermission("/week-day-master"), WeekDayMasterRouter);
Router.use("/holiday-entries", authenticate, checkPermission("/holiday-entries"), HolidayEntriesRouter);
Router.use("/employee-database", authenticate, checkPermission("/employee-database"), EmployeeDatabaseRouter);
Router.use("/dms", authenticate, checkPermission(["/dms", "/truck-master", "/driver-master", "/trailer-master"]), DMSRouter);

// Approval app (nextjs_Approval_tbgs) - no LINK records exist for these paths,
// so only authenticate is applied; the approval controller needs req.user.
Router.use("/dashboard", authenticate, DashboardRouter);
Router.use("/approvals", authenticate, ApprovalRouter);


export default Router;